force-app/main/default/objects/ABCL_Integration_Event__e/ABCL_Integration_Event__e.object-meta.xml
<CustomObject>
    <description>This Platform Event is used for all Non-Case related Integration. 
Always send the RecordId of the Parent Record. Example if the integration happening on Lead record send Lead Id in Record_Id__c field.
Request__c - To store entire payload of the event.
Business_Unit__c - To store the Business Unit, this is useful to separate the orchestration at AWS Layer.</description>
    <label>ABCL Integration Event</label>
    <pluralLabel>ABCL Integration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ABCL_Integration_Event__e/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABCL_Integration_Event__e/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>ObjectApiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABCL_Integration_Event__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABCL_Integration_Event__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <description>Pass Service Name. This is read by AWS EventBridge and then right Lambda to be invoke from AWS Gateway.</description>
    <label>ServiceName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GrossPremium__c.field-meta.xml
<CustomField>
    <fullName>GrossPremium__c</fullName>
    <description>ABHIL</description>
    <label>Gross Premium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/IntermediaryName__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryName__c</fullName>
    <description>ABHIL</description>
    <label>Intermediary Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Next_Premium_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Premium_Date__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Next Premium Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>ABHIL</description>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Proposal_Type__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Type__c</fullName>
    <label>Proposal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STP</fullName>
            </value>
            <value>
                <fullName>NSTP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Sum_Assured__c.field-meta.xml
<CustomField>
    <fullName>Sum_Assured__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Sum Assured</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dialer_Status__c.field-meta.xml
<CustomField>
    <fullName>Dialer_Status__c</fullName>
    <label>Dialer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Call Request Submitted</fullName>
                <default>true</default>
                <label>Schedule Call Request Submitted</label>
            </value>
            <value>
                <fullName>Schedule Call Request Failed</fullName>
            </value>
            <value>
                <fullName>Schedule Call Request Successful</fullName>
            </value>
            <value>
                <fullName>Cancel Call Request Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel Call Request Failed</fullName>
            </value>
            <value>
                <fullName>Cancel Call Request Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <externalId>true</externalId>
    <label>Policy Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RNWL_UbonaIntegrationController.cls
public class RNWL_UbonaIntegrationController {
	
    @TestVisible
    private static Database.SaveResult[] publishResults;
    
    /****************************************************************************************************************
    * @Function - firePlatformEventForUbona
    * @param newOppsList -  list of Opportunities from trigger.new.
    * @return - void .
    * @Description - Invoked from BeforeInsert this method pre-populates fields on Opps from Asset record.
    *****************************************************************************************************************/
    public static void firePlatformEventForUbona(List<Opportunity> newOppsList, Map<Id, Opportunity> oldOpps){
        
        Set<Id> policyIdsSet = new Set<Id>();
        Set<Id> accIdsSet = new Set<Id>();
        Map<Id, Asset> policyIdToAssetMap = new Map<Id, Asset>();
        List<Opportunity> oppsToOperate = new List<Opportunity>();
        
        if(oldOpps != null){
            for(Opportunity opp : newOppsList){
                if(opp.Dialer_Status__c == 'Schedule Call Request Submitted' 
                   && oldOpps.get(opp.Id).Dialer_Status__c ==  'Schedule Call Request Failed'){
                       oppsToOperate.add(opp);
                   } 
            }
        }else{
                oppsToOperate.addAll(newOppsList);
        }
        
        for(Opportunity opp : oppsToOperate){
            policyIdsSet.add(opp.Policy__c); 
            accIdsSet.add(opp.AccountId);
        }
        
        for(Asset asst : getPolicies(policyIdsSet)){
            policyIdToAssetMap.put(asst.Id, asst);
        }
        
        Map<Id, Account> accMap = 
            new Map<Id, Account>([SELECT Id, BillingState,
                       					Name, Phone,
                       					PersonMobilePhone,
                                  		RecordType.Name
                				  FROM Account 
                				  WHERE Id IN :accIdsSet]);
        
        List<ABCL_Integration_Event__e> outboundIntPEList = new List<ABCL_Integration_Event__e>();
        for(Opportunity opp : oppsToOperate){
            ABCL_Integration_Event__e intPE = new ABCL_Integration_Event__e();
            intPE.Business_Unit__c = 'ABHI-RNWL';
            intPE.ObjectApiName__c = 'Opportunity';
            intPE.Record_Id__c = opp.Id;
            intPE.Request__c = formJSONBody(opp, policyIdToAssetMap.get(opp.Policy__c), accMap.get(opp.AccountId));
            intPE.ServiceName__c = 'UbonaScheduleCallServiceRenewal';
            outboundIntPEList.add(intPE);
        }
        
        publishResults = EventBus.publish(outboundIntPEList);
    }
    
    /*****************************************************************************************************************
    *                                     private methods
    *****************************************************************************************************************/
    
    private static String formJSONBody(Opportunity opp, Asset asset, Account acc){
        RNWL_UbonaCalloutWrapper ubonaWrap = new RNWL_UbonaCalloutWrapper();
        RNWL_UbonaCalloutWrapper.Cls_payload payld = new RNWL_UbonaCalloutWrapper.Cls_payload();
        RNWL_UbonaCalloutWrapper.Cls_context contxt = new RNWL_UbonaCalloutWrapper.Cls_context();
        
        ubonaWrap.payloadId = opp.Name;
        ubonaWrap.payloadEncrypted = false;
        payld.requestId = opp.Name;

        payld.scheduledTime = String.valueOf(System.now().getTime());
        payld.agentId = '';
        payld.campaign = System.label.RNWL_UbonaCampaignId;//'85008514';
        if(acc != null){
            payld.msisdn = acc.Phone;
            payld.customerInfo = acc.Name;
            contxt.customerName = acc.Name;
            contxt.state = acc.BillingState; 
        }
        if(asset != null){
            contxt.intermediary = asset.IntermediaryName__c;
            contxt.newChannel = asset.Channel__c;
            contxt.nextPremiumDate = asset.Next_Premium_Date__c;
            contxt.policyDueDate = asset.Maturity_Date__c; 
            contxt.productName = asset.ProductName__c;
        	contxt.renewalGrossPremiumFrom = asset.GrossPremium__c;
            contxt.stp_NSTP = asset.Proposal_Type__c;
        	contxt.sumInsured = asset.Sum_Assured__c != null ? String.valueOf(asset.Sum_Assured__c) : '';
        }
        
        contxt.CRMURL = URL.getOrgDomainURL().toExternalForm() + '/' + opp.Id;
        contxt.policyNumber = opp.Policy_Number__c;
        contxt.rnNumber = opp.Name;

        payld.context = contxt;
        ubonaWrap.payload = payld;
        
        String reqBody = replaceWithActualTags(JSON.serialize(ubonaWrap));
        
        return reqBody;
    }
    
    
    private static String replaceWithActualTags(String reqBody){
        reqBody = reqBody.replace('"customerName":', '"Customer Name":');
        reqBody = reqBody.replace('"intermediary":', '"Intermediary":');
        reqBody = reqBody.replace('"newChannel":', '"New Channel":');
        reqBody = reqBody.replace('"nextPremiumDate":', '"Next Premium Date":');
        reqBody = reqBody.replace('"policyDueDate":', '"Policy Due Date":');
        reqBody = reqBody.replace('"policyNumber":', '"Policy Number":');
        reqBody = reqBody.replace('"productName":', '"Product Name":');
        reqBody = reqBody.replace('"renewalGrossPremiumFrom":', '"Renewal Gross Premium-From":');
        reqBody = reqBody.replace('"rnNumber":', '"RN Number":');
        reqBody = reqBody.replace('"state":', '"State":');
        reqBody = reqBody.replace('"stp_NSTP":', '"STP NSTP":');
        reqBody = reqBody.replace('"sumInsured":', '"SUM INSURED":');
        return reqBody;
    }
    
    /*****************************************************************************************************************
    *                                      Data Getters
    *****************************************************************************************************************/
    
    private static List<Asset> getPolicies(Set<Id> policyIdSet){
        return [SELECT 
                    Id, 
                	IntermediaryName__c,
                	Channel__c,
                	Next_Premium_Date__c,
                	Maturity_Date__c,
                	ProductName__c,
                	GrossPremium__c,
                	Proposal_Type__c,
                	Sum_Assured__c
                FROM Asset 
                WHERE Id IN : policyIdSet];
        
    }
    

}