force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MoveToNext__c.field-meta.xml
<CustomField>
    <fullName>MoveToNext__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MoveToNext</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/No_Auto_Communication__c.field-meta.xml
<CustomField>
    <fullName>No_Auto_Communication__c</fullName>
    <label>No Auto Communication</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DMS_Files__c/DMS_Files__c.object-meta.xml
<CustomObject>
    <label>DMS Files</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>DMS Files Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DMS Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DMS_Files__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>DMS Files</relationshipLabel>
    <relationshipName>DMS_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <externalId>true</externalId>
    <label>ContentVersionId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/DMS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>DMS_External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>DMS External ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Next_Retry__c.field-meta.xml
<CustomField>
    <fullName>Next_Retry__c</fullName>
    <inlineHelpText>Retry will not be attempted if status is success. Also, this field will be nullified on manual retries.</inlineHelpText>
    <label>Next Retry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Retry_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempt__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Attempt</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DMS_Files__c/recordTypes/ABFL.recordType-meta.xml
<RecordType>
    <fullName>ABFL</fullName>
    <active>true</active>
    <label>ABFL</label>
</RecordType>

force-app/main/default/classes/ABCL_RetryDMSFileTransferTest.cls
/**
 * @description       : 
 * @author            : rsinghnagar@salesforce.com
 * @group             : 
 * @last modified on  : 05-02-2024
 * @last modified by  : rsinghnagar@salesforce.com
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   05-02-2024   rsinghnagar@salesforce.com   Initial Version
**/
@IsTest
public class ABCL_RetryDMSFileTransferTest {
    @TestSetup
    static void setupTestData(){
        List<Case> caseRecList = ASF_TestDataFactory.createCaseRecords(2);
        caseRecList[0].MoveToNext__c = true;
        caseRecList[0].Status = 'Closed';
        caseRecList[0].Nature__c = 'Query';
        ASF_TriggerSkipperUtility.markTriggerRun('Case');
        caseRecList[1].MoveToNext__c = true;
        caseRecList[1].Status = 'Closed';
        caseRecList[1].Nature__c = 'Query';
        caseRecList[1].Business_Unit__c = ABFL_Constants.ABFL;
        ASF_TriggerSkipperUtility.markTriggerRun('Case');
        update caseRecList;
    }
    @IsTest 
    static void retryDMSFileTransferTest(){
        List<DMS_Files__c> fileRecList = new List<DMS_Files__c>();
        List<Case> caseRecords = [SELECT Id, No_Auto_Communication__c, AccountId, CCC_External_Id__c, ContactId,IsClosed FROM Case];
        for(integer i=0; i <= 1; i++){
            DMS_Files__c fileRec = new DMS_Files__c();
            fileRec.Case__c = caseRecords[i].Id;
            fileRec.ContentVersionId__c = 'test';
            fileRec.Status__c = ABFL_Constants.PENDING;
			fileRec.Business_Unit__c = ABHFL_Constants.BUSINESS_UNIT_ABHFL;
            DateTime currentDateTime = System.now();
            fileRec.DMS_External_ID__c = String.valueOf(i)+currentDateTime.getTime();
            fileRec.Next_Retry__c = System.now().addMinutes(15);
            fileRec.Retry_Attempt__c = 1;
            fileRecList.add(fileRec);
        }
        insert fileRecList;
        ABCL_RetryDMSFileTransfer.retryDMSFileTransfer(fileRecList);

        List<DMS_Files__c> updatedDMSFilesList = [SELECT Id FROM DMS_Files__c];
		Assert.isTrue(updatedDMSFilesList.size() > 2, 'New DMS files should have been inserted');
    }
    
    @IsTest 
    static void abflRetryDMSFileTransferTest(){
        List<DMS_Files__c> fileRecList = new List<DMS_Files__c>();
        List<Case> caseRecords = [SELECT Id, No_Auto_Communication__c, AccountId, CCC_External_Id__c, ContactId,IsClosed FROM Case];
        for(integer i=0; i <= 1; i++){
            DMS_Files__c fileRec = new DMS_Files__c();
            fileRec.Case__c = caseRecords[i].Id;
            fileRec.ContentVersionId__c = 'test';
            fileRec.Status__c = ABHFL_Constants.PENDING;
            DateTime currentDateTime = System.now();
            fileRec.DMS_External_ID__c = String.valueOf(i)+currentDateTime.getTime();
            fileRec.Next_Retry__c = System.now().addMinutes(15);
            fileRec.Retry_Attempt__c = 1;
            fileRecList.add(fileRec);
        }
        insert fileRecList;
        
        Test.startTest();
        ABCL_RetryDMSFileTransfer.retryDMSFileTransfer(fileRecList);
		Test.stopTest();
        
        List<DMS_Files__c> updatedDMSFilesList = [SELECT Id FROM DMS_Files__c];
		Assert.isTrue(updatedDMSFilesList.size() > 2, 'New DMS files should have been inserted');
    }
}