force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <description>This object is used to track the Survey responses for Case, LAN, and Account.</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Common Client Code. Value to come from API.</description>
    <label>Client Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Primary_Question_NPS__c.field-meta.xml
<CustomField>
    <fullName>Primary_Question_NPS__c</fullName>
    <description>Survey NPS indicator in numbers, 0-10. Value to come from API.</description>
    <label>Primary Question: NPS</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Asf_NpsIndicatiorController.cls
/*********************************************************
*Class        :  Asf_NpsIndicatiorController
*Description  :  Controller class for asf_NdcIndicator LWC
*********************************************************/

public without sharing class Asf_NpsIndicatiorController {
   
    /****************************************************************************************************************
    * @LOB - ALL
    * @Function - genericFetchQuery
    * @param fields - List of fields
    * @param objectName - Object Name
    * @param whereClause - WHERE cluase used in the query.
    * @return - List<SObject>
    * @Description - Generic query to fetch the sobject records.
    *****************************************************************************************************************/
    @AuraEnabled
    public static Map<String, Integer> getCaseCounts(String accountId) {
        Map<String, Integer> counts = new Map<String, Integer>();        
        counts.put('openCases', [SELECT COUNT() FROM Case WHERE AccountID =: accountId and IsClosed = False]);
        counts.put('escalatedCases', [SELECT COUNT() FROM Case WHERE AccountID =: accountId and IsClosed = False and IsEscalated = true]);
        counts.put('complaintCases', [SELECT COUNT() FROM Case WHERE AccountID =: accountId and IsClosed = False and Nature__c = 'Complaint']);
        system.debug('countsasc '+counts);
        return counts;
    }
    @AuraEnabled(cacheable=true)
    public static Map<String,Decimal> getNpsScore(string customerId) {

        Map<String,Decimal> mapOfBusinessUnitToNpsScore = new Map<String,Decimal>();
        List<Survey_Response__c> surveyResp = [SELECT ID,Primary_Question_NPS__c,Business_Unit__c FROM Survey_Response__c WHERE Client_Code__c =: customerId ORDER BY CreatedDate DESC LIMIT 1];

        if(!surveyResp.isEmpty() && surveyResp[0].Primary_Question_NPS__c !=null){
            mapOfBusinessUnitToNpsScore.put(surveyResp[0]?.Business_Unit__c, surveyResp[0].Primary_Question_NPS__c);
        }
        else {
            mapOfBusinessUnitToNpsScore.put(surveyResp[0]?.Business_Unit__c, 0);
        }
        return mapOfBusinessUnitToNpsScore; 
    }
}