force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sent_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Send_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Send_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is used in ASF_Email2CaseHandler based on Priority Email, it will mark Send to EBOT True or False.</description>
    <label>Send to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ABCL_EmailMessageHelper_Test.cls
@isTest
public class ABCL_EmailMessageHelper_Test {

    @isTest
    static void testEbotHandler() {
        Case testCase = new Case(
            Origin = 'ABFL Email',
            Business_Unit__c = 'ABFL',
            Technical_Source__c = 'Email'
        );
        insert testCase;

        EmailMessage testEmail = new EmailMessage(
            ParentId = testCase.Id,
            Subject = 'Test Subject',
            Incoming = true,
            Send_To_Ebot__c = true
        );
        insert testEmail;

        Test.startTest();
        ABCL_EmailMessageHelper.ebotHandler(new Map<Id, sObject>{ testEmail.Id => testEmail });
        Test.stopTest();

        List<Case >testCasse = [SELECT Id, Sent_to_EBOT__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals(1, testCasse.size(),'record found');          
    }

    // Test method for getEligibles
    @isTest
    static void testGetEligibles() {
        // Creating test data: List of EmailMessages
        List<EmailMessage> emails = new List<EmailMessage>();

        Case testCase = new Case();
        insert testCase;

        EmailMessage eligibleEmail = new EmailMessage(
            ParentId = testCase.Id,
            Subject = 'Eligible Subject',
            Incoming = true
        );
        EmailMessage ineligibleEmail = new EmailMessage(
            ParentId = testCase.Id,
            Subject = 'Ineligible Subject',
            Headers = 'In-Reply-To: xyz',
            Incoming = true,
            ReplyToEmailMessageId = '02sBi000001DjQ0AIK'
        );

        emails.add(eligibleEmail);
        emails.add(ineligibleEmail);

        List<EmailMessage> eligibleMessages = ABCL_EmailMessageHelper.getEligibles(emails);

        System.assertEquals(1, eligibleMessages.size(), 'Only one email should be eligible');
        System.assertEquals('Eligible Subject', eligibleMessages[0].Subject, 'Incorrect eligible email subject');
    }
}