force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Prospect_Payload__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Payload__c</fullName>
    <label>Prospect Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/PANNO__c.field-meta.xml
<CustomField>
    <fullName>PANNO__c</fullName>
    <label>PANNO</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ABFL</fullName>
    </customValue>
    <customValue>
        <fullName>ABHFL</fullName>
    </customValue>
    <customValue>
        <fullName>Payments</fullName>
    </customValue>
    <customValue>
        <fullName>ABWM</fullName>
    </customValue>
    <customValue>
        <fullName>ABSLI</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ABFL_CreateCaseProspectHelperTest.cls
@IsTest 
private class ABFL_CreateCaseProspectHelperTest {
    
    @testSetup static void basicDataSetup() {
        // Create common test Leads
        Lead newLead = new lead();
        newLead.FirstName = 'FULLNAM2E';
        newLead.Lastname = 'name';
        newLead.MobilePhone = '1236547899';
        newLead.Email = 'Email2@gmail.com';
        newLead.PANNO__c = 'PANNO2';
        insert newLead;        
    }
    
    @IsTest(seeAllData = false)
    static void beforeInsertMethod_Test() {
        Case newCase = new Case(Business_Unit__c='ABFL');
        newCase.Prospect_payload__c='{"FULLNAME":"FULLNAME","MOBILE":"123654789","PANNO":"PANNO1","Email":"Email@gmail.com"}';
        Case newCase2 = new Case(Business_Unit__c='ABFL');
        newCase2.Prospect_payload__c='{"FULLNAME":"FULLNAM2E name","MOBILE":"1236547899","PANNO":"PANNO2","Email":"Email2@gmail.com"}';
        sObject sObjcase = newCase;
        sObject sObjcase2 = newCase2;
        List<sObject> sList = new List<sObject>();
        sList.add(sObjcase);
        sList.add(sObjcase2);
        System.runAs(new User (Id = UserInfo.getUserId())) {
            Test.StartTest();
            ABFL_CreateCaseProspectHelper.beforeInsertMethod(sList);
            Test.StopTest();   
        }
        List<Lead> ls = [select id from lead];
        System.assertEquals(2,ls.size());
        System.assertnotEquals(1,ls.size());
    }
}