force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <description>This picklist field will contain the lob value to be used in sharing rules</description>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AIF</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>PMS</fullName>
            </value>
            <value>
                <fullName>RE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOBVsAPIChannels__mdt/LOBVsAPIChannels__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata maps Line of Business Vs API Channels and there respective Queue.</description>
    <label>LOBVsAPIChannel</label>
    <pluralLabel>LOBVsAPIChannels</pluralLabel>
</CustomObject>

force-app/main/default/objects/LOBVsAPIChannels__mdt/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABHFL</fullName>
                <default>true</default>
                <label>ABHFL</label>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ONEABC</fullName>
            </value>
            <value>
                <fullName>ABCD</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOBVsAPIChannels__mdt/fields/Queue_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>Queue_DeveloperName__c</fullName>
    <label>Queue DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOBVsAPIChannels__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatbot</fullName>
                <default>true</default>
                <label>Chatbot</label>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABCL_CaseDuplicateCheck.cls
public without sharing class ABCL_CaseDuplicateCheck {
    
    public void runDuplicateCheck(List<Case> newList){
        Map<String,Map<String,String>> mLobToChannelToQueue = new Map<String,Map<String,String>>();
        List<Case> paymentCases = new List<Case>();
        List<LOBVsAPIChannels__mdt> lobToChannelQueue = [SELECT Id, Line_Of_Business__c, Source__c, Queue_DeveloperName__c FROM LOBVsAPIChannels__mdt WITH SYSTEM_MODE];
        Map<String,List<Case>> mChannelVsCases = new Map<String,List<Case>>();
                Set<String> queueDevName = new Set<String>();
        List<Case> abhflCases = new List<Case>();//AM-ABHFL Case DEDUPE
        List<Case> abslamcCases = new List<Case>();
        
        for(LOBVsAPIChannels__mdt mdt : lobToChannelQueue){
            if(!mLobToChannelToQueue.containsKey(mdt.Line_Of_Business__c)){
                mLobToChannelToQueue.put(mdt.Line_Of_Business__c,new Map<String,String>());
            }
            if(!mLobToChannelToQueue.get(mdt.Line_Of_Business__c).containsKey(mdt.Source__c)){
                mLobToChannelToQueue.get(mdt.Line_Of_Business__c).put(mdt.Source__c,mdt.Queue_DeveloperName__c);
                if(mdt.Queue_DeveloperName__c != null){
                    queueDevName.add(mdt.Queue_DeveloperName__c);
                }
            }
        }
        
        
        for(Case c : newList){
            if(mLobToChannelToQueue.containsKey(c.Business_Unit__c)){
                if(mLobToChannelToQueue.get(c.Business_Unit__c).containsKey(c.Technical_Source__c)){
                    if(!mChannelVsCases.containsKey(c.Business_Unit__c)){
                        mChannelVsCases.put(c.Business_Unit__c,new List<Case>());
                    }
                    mChannelVsCases.get(c.Business_Unit__c).add(c);
                }
            }
            if(c.Business_Unit__c=='ABHFL'){//AM-ABHFL Case DEDUPE
                abhflCases.add(c);
            }
             else if(c.Business_Unit__c== ABSLAMC_Constants.ABSLAMCBU){//AM-ABSLAMC Case DEDUPE
                abslamcCases.add(c);
            }
        }
        
        for(String key : mChannelVsCases.keySet()){
            if(key == 'Payments'){
                PAY_CaseDeDupeCheck.runDuplicateCheck(mChannelVsCases.get(key));
            }
            else if(key == 'ABSLI'){
                ABSLI_CasDeDupeCheck.runDuplicateCheck(mChannelVsCases.get(key));
            }
        }
        if(Label.ABHFL_Case_Dedupe_Active=='Active'){//AM-ABHFL Case DEDUPE
        	ABHFL_CTSTHelper.runDuplicateCheck(abhflCases);  
        }
        if(Label.ABSLAMC_Case_Dedupe_Active=='Active'){//AM-ABHFL Case DEDUPE
        	ABSLAMC_CaseCreationDuplicateChecker.runDuplicateCheck2(abslamcCases);
        }
        
    }
    
}