force-app/main/default/objects/Case/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reopen_Days__c.field-meta.xml
<CustomField>
    <fullName>Reopen_Days__c</fullName>
    <description>Number of Days till the case can be reopened after closure.</description>
    <label>Reopen Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_2__c</fullName>
    <label>Stage SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_3__c</fullName>
    <label>Stage SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interaction.recordType-meta.xml
<RecordType>
    <fullName>Interaction</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Interaction</label>
</RecordType>

force-app/main/default/objects/SLA_Threshold_Warning__c/SLA_Threshold_Warning__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>When you change this setting , please note that existing Cases needs to be reedited for new changes to come in.</description>
    <label>SLA Threshold Warning</label>
</CustomObject>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_2__c</fullName>
    <label>Stage SLA Threshold 2</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_3__c</fullName>
    <label>Stage SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ASF_EmailMessageHelperTest.cls
@isTest
public class ASF_EmailMessageHelperTest {
    private final static Profile SYSTEMADMIN_PROFILE = [SELECT Id FROM Profile WHERE name='System Administrator' LIMIT 1];
    @TestSetup
    public static void setup() {
        insert new SLA_Threshold_Warning__c(Case_SLA_Threshold_1__c = 0.5, Case_SLA_Threshold_2__c = 0.7,
                                          Case_SLA_Threshold_3__c = 0.8, Stage_SLA_Threshold_1__c = 0.5,
                                          Stage_SLA_Threshold_2__c = 0.7, Stage_SLA_Threshold_3__c = 0.6);
        Case c = new Case();
        c.Subject = 'Test';
        c.RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName().get('Interaction').getRecordTypeId();
        insert c;

        ASF_TestDataFactory.createCaseCategoryConfig();
        List<Case> caseL = ASF_TestDataFactory.createCaseRecords(1);
    }

    @isTest
    public static void validateIfGoingFromAuthorizedAddress(){
        Case c = [select id from case where recordtypeid = :ASF_Constants.RT_INTERACTION limit 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'test@test.com.invalid'}; 
        mail.setToAddresses(toAddresses);
        mail.setWhatId(c.Id);
        mail.setSubject('Test Email Relay');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setPlainTextBody('This is test email with new name..');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
    } 
    @isTest
    public static void checkAndReopenClosedCasesTest(){
        
        Case c = [select id from case where recordtypeid = :ASF_Constants.RT_FRAMEWORK limit 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'test@test.com.invalid'}; 
        mail.setToAddresses(toAddresses);
        mail.setWhatId(c.Id);
        mail.setSubject('Test Email Relay');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setPlainTextBody('This is test email with new name..');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 

        c.Stage__c = 'Resolved';
        c.Status = 'Closed';
        c.RecordTypeId = ASF_Constants.RT_FRAMEWORK;
        c.Reopen_Days__c = 1;
        update c;
        
        Test.startTest();
        EmailMessage oldMail = [Select MessageIdentifier from EmailMessage LIMIT 1];
        Messaging.SingleEmailMessage mail2 = new Messaging.SingleEmailMessage();
        mail2.setToAddresses(toAddresses);
        mail2.setWhatId(c.Id);
        mail2.setSubject('Test Email Relay');
        mail2.setBccSender(false);
        mail2.setUseSignature(false);
        mail2.setPlainTextBody('This is test email with new name..');
        mail2.setInReplyTo(oldMail.MessageIdentifier);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail2 });
        test.stopTest();
    } 

    @isTest
    public static void checkAndReopenClosedCasesTest2(){
        
        Case c = [select id from case where recordtypeid = :ASF_Constants.RT_FRAMEWORK limit 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'test@test.com.invalid'}; 
        mail.setToAddresses(toAddresses);
        mail.setWhatId(c.Id);
        mail.setSubject('Test Email Relay');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setPlainTextBody('This is test email with new name..');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 

        c.Stage__c = 'Resolved';
        c.Status = 'Closed';
        c.RecordTypeId = ASF_Constants.RT_FRAMEWORK;
        c.Reopen_Days__c = -1;
        update c;
        
        Test.startTest();
        EmailMessage oldMail = [Select MessageIdentifier from EmailMessage LIMIT 1];
        Messaging.SingleEmailMessage mail2 = new Messaging.SingleEmailMessage();
        mail2.setToAddresses(toAddresses);
        mail2.setWhatId(c.Id);
        mail2.setSubject('Test Email Relay');
        mail2.setBccSender(false);
        mail2.setUseSignature(false);
        mail2.setPlainTextBody('This is test email with new name..');
        mail2.setInReplyTo(oldMail.MessageIdentifier);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail2 });
        test.stopTest();
    } 

    @isTest
    public static void checkAndReopenClosedCasesTest3(){
        
        Case c = [select id from case where recordtypeid = :ASF_Constants.RT_FRAMEWORK limit 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'test@test.com.invalid'}; 
        mail.setToAddresses(toAddresses);
        mail.setWhatId(c.Id);
        mail.setSubject('Test Email Relay');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setPlainTextBody('This is test email with new name..');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 

        c.Stage__c = 'Resolved';
        c.Status = 'Closed';
        c.RecordTypeId = ASF_Constants.RT_FRAMEWORK;
        c.Reopen_Days__c = null;
        update c;
        
        Test.startTest();
        EmailMessage oldMail = [Select MessageIdentifier from EmailMessage LIMIT 1];
        Messaging.SingleEmailMessage mail2 = new Messaging.SingleEmailMessage();
        mail2.setToAddresses(toAddresses);
        mail2.setWhatId(c.Id);
        mail2.setSubject('Test Email Relay');
        mail2.setBccSender(false);
        mail2.setUseSignature(false);
        mail2.setPlainTextBody('This is test email with new name..');
        mail2.setInReplyTo(oldMail.MessageIdentifier);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail2 });
        test.stopTest();
    } 
}