force-app/main/default/objects/ABHI_Case_Detail__c/ABHI_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ABHIL</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHI_Case_Detail__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>ABHI Case Details</relationshipLabel>
    <relationshipName>Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CumulativeBonusEarned__c.field-meta.xml
<CustomField>
    <fullName>CumulativeBonusEarned__c</fullName>
    <label>Cumulative Bonus Earned</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>ABSLI Field  - Used to store Customer Segment</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Business Partners</fullName>
            </value>
            <value>
                <fullName>FATCA</fullName>
            </value>
            <value>
                <fullName>FlS</fullName>
            </value>
            <value>
                <fullName>GENERAL</fullName>
            </value>
            <value>
                <fullName>HNI</fullName>
            </value>
            <value>
                <fullName>Non HNI</fullName>
            </value>
            <value>
                <fullName>NRI</fullName>
            </value>
            <value>
                <fullName>Orphan</fullName>
            </value>
            <value>
                <fullName>PEP</fullName>
            </value>
            <value>
                <fullName>PLATINUMHNI</fullName>
            </value>
            <value>
                <fullName>SUPERHNI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Chronic__c.field-meta.xml
<CustomField>
    <fullName>Is_Chronic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Chronic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MMI_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>MMI_Customer_ID__c</fullName>
    <description>ABHIL Field</description>
    <label>MMI Customer ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Office_Email__c.field-meta.xml
<CustomField>
    <fullName>Office_Email__c</fullName>
    <label>Office Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rider_Opted__c.field-meta.xml
<CustomField>
    <fullName>Rider_Opted__c</fullName>
    <label>Rider Opted</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CountOfLives__c.field-meta.xml
<CustomField>
    <fullName>CountOfLives__c</fullName>
    <description>ABHI</description>
    <label>No. of Insured Members</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cover_Type__c.field-meta.xml
<CustomField>
    <fullName>Cover_Type__c</fullName>
    <label>Cover Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GoGreen__c.field-meta.xml
<CustomField>
    <fullName>GoGreen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ABHIL</description>
    <label>Go Green</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GrossPremium__c.field-meta.xml
<CustomField>
    <fullName>GrossPremium__c</fullName>
    <description>ABHIL</description>
    <label>Gross Premium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Intermediary_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Intermediary_Branch_Code__c</fullName>
    <label>Intermediary Branch Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/IntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryCode__c</fullName>
    <description>ABHIL</description>
    <label>Intermediary Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/IntermediaryMobileNumber__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryMobileNumber__c</fullName>
    <description>ABHIL</description>
    <label>Intermediary Mobile Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/IntermediaryName__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryName__c</fullName>
    <description>ABHIL</description>
    <label>Intermediary Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/MasterPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ABHIL</description>
    <label>Master Policy Number</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Mode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <externalId>true</externalId>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_Term__c.field-meta.xml
<CustomField>
    <fullName>Policy_Term__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Policy Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PolicySubStatus__c.field-meta.xml
<CustomField>
    <fullName>PolicySubStatus__c</fullName>
    <description>ABHIL</description>
    <label>Policy Sub Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>ABHIL</description>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ServicingBranchName__c.field-meta.xml
<CustomField>
    <fullName>ServicingBranchName__c</fullName>
    <description>ABHI</description>
    <label>Policy Servicing Branch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>ABHIL</description>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SRMCode__c.field-meta.xml
<CustomField>
    <fullName>SRMCode__c</fullName>
    <label>SRM Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SRMName__c.field-meta.xml
<CustomField>
    <fullName>SRMName__c</fullName>
    <label>Sales Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Sum_Assured__c.field-meta.xml
<CustomField>
    <fullName>Sum_Assured__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Sum Assured</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ZoneOfCover__c.field-meta.xml
<CustomField>
    <fullName>ZoneOfCover__c</fullName>
    <description>ABHIL</description>
    <label>Zone Of Cover</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>ABHIL</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <description>ABHI</description>
    <label>Policy Number</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drop_off_Reason__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_Reason__c</fullName>
    <label>Drop-off Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drop_off_URL__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_URL__c</fullName>
    <label>Drop-off URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Grace_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_End__c</fullName>
    <formula>Grace_Period_Start__c + 30</formula>
    <label>Grace Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Grace_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Start__c</fullName>
    <formula>Policy_Lapse_Date__c + 1</formula>
    <label>Grace Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Plan name formula coming from asset Plan_Name__c</description>
    <formula>Policy__r.Plan_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Inception_Date__c</fullName>
    <label>Policy Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Lapse_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lapse_Date__c</fullName>
    <formula>Policy__r.Maturity_Date__c + 30</formula>
    <label>Policy Lapse Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Lapsed__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lapsed__c</fullName>
    <formula>IF(TODAY() &gt;  Grace_Period_End__c , &apos;Deep Lapsed&apos;, IF(TODAY() &gt;  Policy_Lapse_Date__c , &apos;Lapsed&apos;, &apos;No&apos;))</formula>
    <label>Policy Lapsed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <externalId>true</externalId>
    <label>Policy Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proposal_Number__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Number__c</fullName>
    <description>Child Proposal Number from JARVIS</description>
    <externalId>true</externalId>
    <label>Proposal Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewal In Progress</fullName>
                <default>true</default>
                <label>Renewal In Progress</label>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RNWL_RenewalCustomerPolicyInfo.cls
/**
* @File Name : RNWL_RenewalCustomerPolicyInfo.cls
* @Description :
* @Author : Misbah
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 18, 2024 |   | Initial Version
**/

public with sharing class RNWL_RenewalCustomerPolicyInfo {

    @AuraEnabled(cacheable=true)
    public static Opportunity getOppRec(String recordId){
        return [SELECT Id, 
					Account.Id,
                	Account.FirstName, 
                	Account.LastName, 
					Account.MMI_Customer_ID__c,
					Account.PersonBirthdate,
					Account.PersonGenderIdentity,
					Account.PersonMobilePhone,
					Account.Office_Email__c,
					Account.BillingStreet,
					Account.BillingCity,
					Account.BillingState,
					Account.BillingPostalCode,
					Account.BillingAddress,
					Account.Customer_Segment__c,
					Account.CumulativeBonusEarned__c,
					Account.Rider_Opted__c,
					Account.Is_Chronic__c,
					Account.RecordType.Name,
					Policy__r.Policy_No__c,
					Policy__r.Cover_Type__c,
					Policy__r.Issue_Date__c,
					Policy__r.Maturity_Date__c,
					Policy__r.Policy_Term__c,
					Policy__r.ProductName__c,
					Policy__r.ZoneOfCover__c,
					Policy__r.Sum_Assured__c,
					Policy__r.CountOfLives__c,
					Policy__r.Plan_Name__c,
					Policy__r.Channel__c,
					Policy__r.Mode__c,
					Policy__r.SRMName__c,
					Policy__r.SRMCode__c,
					Policy__r.ServicingBranchName__c,
					Policy__r.IntermediaryName__c,
					Policy__r.IntermediaryMobileNumber__c,
                	Policy__r.Name, 
					Policy__r.Source__c,
					Policy__r.GoGreen__c,
					Policy__r.PolicySubStatus__c,
					Policy__r.GrossPremium__c,
					Policy__r.MasterPolicyNumber__c,
					Policy__r.IntermediaryCode__c, 
					Policy__r.Intermediary_Branch_Code__c,
					Policy__r.SerialNumber,
					Drop_off_Reason__c,
					Drop_off_URL__c,
					Policy_Inception_Date__c, 
					Proposal_Number__c,
					Grace_Period_End__c,
					Grace_Period_Start__c,
					Policy_Lapse_Date__c,
					Policy_Lapsed__c, Policy_Number__c,
					Policy_Renewal_Notice_Day__c,
					Status__c, Propensity_to_Pay__c,
					Preferred_Flag__c, Calling_Source__c,
					Renewal_Calling_Flag__c
                FROM Opportunity 
                WHERE Id = :Id.valueOf(recordId) 
                LIMIT 1];
    }

	@AuraEnabled
	public static Asset getNomineesClaims(String policyId) {
        return [SELECT Id,
               		Name, 
					(SELECT Id, Name, NomineeContactNumber__c FROM PolicyNumber__r),
					(SELECT Id FROM Claims__r WHERE Claim_Status__c != 'Rejected' AND Claim_Status__c != 'Settled')
				FROM Asset WHERE Id = :policyId];
	}
	
}