force-app/main/default/objects/ABHI_Case_Detail__c/ABHI_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ABHIL</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHI_Case_Detail__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please enter Policy Number to view list of available claims</inlineHelpText>
    <label>Claim Number</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Claim__c.Policy_Number__c</field>
            <operation>equals</operation>
            <valueField>$Source.Policy__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>ABHI Case Details</relationshipLabel>
    <relationshipName>ABHI_Case_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABHI_Case_Detail__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>ABHI Case Details</relationshipLabel>
    <relationshipName>Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABHI_Case_Detail__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cashless:Claim process enquiry</fullName>
            </value>
            <value>
                <fullName>Medical Decisions:Medical Decisions</fullName>
            </value>
            <value>
                <fullName>Endorsement:Change in Demographics</fullName>
            </value>
            <value>
                <fullName>Endorsement:Modification in policy profile</fullName>
            </value>
            <value>
                <fullName>Policy related services:Counter offer related</fullName>
            </value>
            <value>
                <fullName>Policy related services:Policy benefits/Inclusion/Exclusion</fullName>
            </value>
            <value>
                <fullName>Reimbursement:Claim process enquiry</fullName>
            </value>
            <value>
                <fullName>Reimbursement:Documents related</fullName>
            </value>
            <value>
                <fullName>Reimbursement:OPD claim</fullName>
            </value>
            <value>
                <fullName>General enquiry:Hospital and Diagnostic Center</fullName>
            </value>
            <value>
                <fullName>General enquiry:Promo related</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABHI_Case_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ABHI</fullName>
            </value>
            <value>
                <fullName>ABSLAMC</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABHI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABHI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABHI Case Detail</label>
    <referenceTo>ABHI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>ABHIL</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABHI_CaseDetailHelper.cls
/*********************************************************
*@Class        :  ABHI_CaseDetailHelper
*@Author       :  Sara Jaipuria
*@Created Date :  31-07-2024
*@Last Modified:  31-07-2024
*@description  :  Class for ABHI Case Detail Object Business Logic
*********************************************************/
public with sharing class ABHI_CaseDetailHelper {
    
    /****************************************************************************************************************
    * @Function - populateABHILCaseDetailFields
    * @param newCaseMap
    * @description - updates Sub_Type__c on Extention object based on Type__c and Sub_Type__c on CCC
    *****************************************************************************************************************/
    @SuppressWarnings('PMD.ApexDoc')
    public void populateABHILCaseDetailFields(List<Case> newCaseList) {
        
        List<String> listOfcccExtIds = new List<String>();
        Map<String, Case> mapofCaseDetailToCase = new Map<String, Case>();
        Map<String, ASF_Case_Category_Config__c> mapOfCCCExtIdIdsToCCCRec = new Map<String, ASF_Case_Category_Config__c>();
        
        for(Case caseRec : newCaseList) {
            if(caseRec.ABHI_Case_Detail__c != null && caseRec.Business_Unit__c == 'ABHI') {
                listOfcccExtIds.add(caseRec.CCC_External_Id__c);
                mapofCaseDetailToCase.put(caseRec.ABHI_Case_Detail__c, caseRec);
            }
        }
        
        if(mapofCaseDetailToCase.keySet().size() > 0) {
            Map<Id, ASF_Case_Category_Config__c> mapOfCCCIdToCCCRec = new Map<Id, ASF_Case_Category_Config__c>([
                SELECT Id, Type__c, Sub_Type__c, CCC_External_Id__c
            	FROM ASF_Case_Category_Config__c
            	WHERE CCC_External_Id__c IN :listOfcccExtIds
            ]);
            
            Map<Id, ABHI_Case_Detail__c> mapOfCaseDetailIdToCaseDetailRec = new Map<Id, ABHI_Case_Detail__c>([
                SELECT Id, Sub_Type__c 
                FROM ABHI_Case_Detail__c
                WHERE Id IN :mapofCaseDetailToCase.keySet()
            ]);
            
            for(ASF_Case_Category_Config__c cccRec : mapOfCCCIdToCCCRec.values()) {
                mapOfCCCExtIdIdsToCCCRec.put(cccRec.CCC_External_Id__c, cccRec);
            }
            
            for(ABHI_Case_Detail__c caseDetailRec : mapOfCaseDetailIdToCaseDetailRec.values()) {
                String cccExtId = mapofCaseDetailToCase.get(caseDetailRec.Id).CCC_External_Id__c;
                String typeOfCCC = mapOfCCCExtIdIdsToCCCRec.get(cccExtId).Type__c;
                String subTypeOfCCC = mapOfCCCExtIdIdsToCCCRec.get(cccExtId).Sub_Type__c;
                caseDetailRec.Sub_Type__c = typeOfCCC+':'+subTypeOfCCC;
            }
            
            if(mapOfCaseDetailIdToCaseDetailRec.size() > 0) {
                update mapOfCaseDetailIdToCaseDetailRec.values();
            }
        }
    } 

    /**
    * Jira Story  - PR1030924-98
    * @param abhiNewCaseList - List of ABHI new cases
    * @param mapOfIdToOldCase - Map of Id to Old Case
    * @param triggerContext  - In which context the method is being called
    * @description - Claim filter based on customer or policy update on CASE
    */
    @SuppressWarnings('PMD.AvoidDeeplyNestedIfStmts,PMD.CognitiveComplexity,PMD.CyclomaticComplexity')
    public void populateCaseOnABHICaseDet(List<Case> abhiNewCaseList, Map<Id, Case> mapOfIdToOldCase, String triggerContext){
        
        List<ABHI_Case_Detail__c> abhiCaseDetList = new List<ABHI_Case_Detail__c>();

        for(Case cs : abhiNewCaseList) {
            
            if(String.isNotBlank(cs.ABHI_Case_Detail__c)) {
                ABHI_Case_Detail__c abhiCaseDetRec = new ABHI_Case_Detail__c();
                if(triggerContext == 'AfterASFCodeInAfterInsert') { 
                    abhiCaseDetRec.Policy__c = cs?.AssetId;
                }
                else if(triggerContext == 'AfterASFCodeInAfterUpdate') {
                    Case oldCase = mapOfIdToOldCase.get(cs.Id);
                    if(String.isNotBlank(cs.AssetId) && cs.AssetId != oldCase.AssetId) {      
                        abhiCaseDetRec.Claim__c = null;
                        abhiCaseDetRec.Policy__c = cs?.AssetId;
                    }
                    else if(String.isBlank(cs.AssetId)) {
                        abhiCaseDetRec.Claim__c = null;
                        abhiCaseDetRec.Policy__c = null;
                    }
                }
                abhiCaseDetRec.Id = cs.ABHI_Case_Detail__c;
                abhiCaseDetList.add(abhiCaseDetRec);
            }
        }

        if(Schema.sObjectType.ABHI_Case_Detail__c.isUpdateable() && abhiCaseDetList.size() > 0) {
            update abhiCaseDetList;
        }
    }
} 