force-app/main/default/objects/ABHFL_Asset_Detail__c/ABHFL_Asset_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Asset Detail</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Asset Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Asset Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Asset_Detail__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABHFL_Asset_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Case Details</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>ABHIL</description>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABHFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABHFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABHFL Case Detail</label>
    <referenceTo>ABHFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Stage_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Stage_Change_Date__c</fullName>
    <label>Case Stage Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABHFL_PreClosureCaseCreation_Test.cls
/*********************************************************
*@Class        :  ABHFL_PreClosureCaseCreation_Test
*@Author       :  Anjali Sharma
*@Created Date :  12/12/2023 
*@Last Modified:  
*@description  :  Class for ABHFL_PreClosureCaseCreation
*********************************************************/

@IsTest
public class ABHFL_PreClosureCaseCreation_Test {
    @TestSetup
    static void createData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];  
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String uid = h.SubString(0,8); 
        User u = new User(Alias = uid, Email= uid + '@testdomain.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_IN', ProfileId = p.Id, 
                          TimeZoneSidKey='Asia/Kolkata', UserName= uid + '@testdomain.com'); 
        insert u;
        PermissionSetGroup psg = [select Id, Status from PermissionSetGroup where DeveloperName='Super_Admin'];
        
        
        if(psg.Status != 'Updated'){
            Test.calculatePermissionSetGroup(psg.Id);
            insert new PermissionSetAssignment(PermissionSetGroupId = psg.Id, AssigneeId = u.Id);
        }


        System.runAs(u){
            Test.startTest();
            Account accRec = ASF_TestDataFactory.insertBusinessAccount('Test_Cmp','Test_1');
            Asset astRec = ASF_TestDataFactory.createAsset(accRec.Id,'Loans');
            astRec.LAN__c = 'Test';
            update astRec;
            ABHFL_Case_Detail__c caseDetail = new ABHFL_Case_Detail__c();
            caseDetail.From_Date__c = Date.newInstance(2023, 02, 04);
            caseDetail.To_Date__c = Date.newInstance(2023, 10, 15);
            insert caseDetail;
            List<Case> caseRecList = ASF_TestDataFactory.createCaseRecords(1);
            caseRecList[0].AssetId = astRec.Id;
            caseRecList[0].AccountId = accRec.Id;
            caseRecList[0].ABHFL_Case_Detail__c = caseDetail.Id;
            caseRecList[0].Case_Stage_Change_Date__c = date.today();
            update caseRecList[0];
            
           //create Asset Detail
            ABHFL_Asset_Detail__c assetDetail = new ABHFL_Asset_Detail__c();
            assetDetail.Asset__c = astRec.Id;
            assetDetail.Case__c = caseRecList[0].Id;
          
            ABHFL_Asset_Detail__c assetDetail1 = new ABHFL_Asset_Detail__c();
            assetDetail1.Asset__c = astRec.Id;
            assetDetail1.Case__c = caseRecList[0].Id;         
           
            insert assetDetail;
            insert assetDetail1;
                
                
            Test.stopTest();
        }
    }

    @IsTest
    static void testEvaluate() {        
        Case caseRec = [SELECT id,Account.Client_Code__c,Source__c,Technical_Source__c,Nature__c FROM case LIMIT 1];
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls = ABHFL_PreClosureCaseCreation.afterStageMovement(new List<Case>{caseRec});

        System.assertEquals('Success', retCls.get(caseRec.Id).Status);
    }
}