force-app/main/default/objects/ABFL_Case_Detail__c/ABFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABFL Case Detail</label>
    <nameField>
        <displayFormat>ABFL-{0000000}</displayFormat>
        <label>ABFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Case_Categorisation__c.field-meta.xml
<CustomField>
    <fullName>Case_Categorisation__c</fullName>
    <label>Case Categorisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect</fullName>
            </value>
            <value>
                <fullName>Correct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Correct_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Correct_Call_Type__c</fullName>
    <label>Correct Call Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Correct_Category__c.field-meta.xml
<CustomField>
    <fullName>Correct_Category__c</fullName>
    <label>Correct Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Correct_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Correct_Sub_Type__c</fullName>
    <label>Correct Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Diputed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Diputed_Amount__c</fullName>
    <label>Diputed Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Financial_Impact__c.field-meta.xml
<CustomField>
    <fullName>Financial_Impact__c</fullName>
    <label>Financial Impact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Grievance_Type__c.field-meta.xml
<CustomField>
    <fullName>Grievance_Type__c</fullName>
    <label>Grievance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>LOB coming from UNFYD</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LOB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Primary_Erring_Unit__c.field-meta.xml
<CustomField>
    <fullName>Primary_Erring_Unit__c</fullName>
    <label>Primary Erring Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Perception</fullName>
            </value>
            <value>
                <fullName>Collections Team</fullName>
            </value>
            <value>
                <fullName>IT team</fullName>
            </value>
            <value>
                <fullName>Call Centre</fullName>
            </value>
            <value>
                <fullName>ASD</fullName>
            </value>
            <value>
                <fullName>Grievance Team</fullName>
            </value>
            <value>
                <fullName>Product Team</fullName>
            </value>
            <value>
                <fullName>Sales/Business</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Policy Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Voice_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Voice_of_Customer__c</fullName>
    <label>Voice of Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ABHI</fullName>
            </value>
            <value>
                <fullName>ABSLAMC</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wealth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABFL Case Detail</label>
    <referenceTo>ABFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>This field will get LOB value from related Asset or Account.</description>
    <formula>IF( ISBLANK( AssetId ) || ISBlank(TEXT(Asset.LOB__c )) , Text( Account.Line_of_Business__c ),  TEXT(Asset.LOB__c ))</formula>
    <label>LOB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not classified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABFL_ComplaintsValidateOnResolvedStage.cls
/*********************************************************
*@Class        :  ABFL_ComplaintsValidateOnResolvedStage 
*@Author       :  Sai Rahul
*@Created Date :  02/09/2024
*@Last Modified:  03/15/2024 - APEX PMD fixes - Code Refactored - Sankashu
*@description  :  Class for Complaints Case Validation for ABFL
*********************************************************/
public with sharing class ABFL_ComplaintsValidateOnResolvedStage {
    
    /****************************************************************************************************************
* @BusinessUnit - ABFL
* @LOBs - 'Retail - Secured','Retail - Unsecured','Corporate','Digital','Not classified'
* @Function - RCA Fields validation on Verification Stage for Complaints Cases except Wealth LOB
* @param  - Case record 
* @description - invoked when tried to Close case without filling RCA fields on Verification Stage
*****************************************************************************************************************/
    public static Map<Id,Set<String>> validateRCAfields(Set<Id> caseIds)
    {   
        Map<Id,Set<String>> mCaseIdVsBlankFields = new Map<Id,Set<String>>();
        
        
        List<String> cccExtIds = new List<String>();
        
        if(!(caseIds.size()>0)){
            return new Map<Id,Set<String>>();
        }
        
        Map<Id,Case> cases = new Map<Id,Case>(ABFL_SOQL_Case.getCasedetails(caseIds));
        
        for(Case c : cases.values()){
            cccExtIds.add(c.CCC_External_Id__c);
        }
        
        List<ASF_Case_Category_Config__c> ccRecords = ASF_CaseQueryHandler.getCaseCategoryConfigs(cccExtIds);
        
        Map<String,ASF_Case_Category_Config__c> mCCCExtIdVsCCCRecord = new Map<String,ASF_Case_Category_Config__c>();
        
        for(ASF_Case_Category_Config__c cccRecord : ccRecords){
            if(!mCCCExtIdVsCCCRecord.containsKey(cccRecord.CCC_External_Id__c))
            {
                mCCCExtIdVsCCCRecord.put(cccRecord.CCC_External_Id__c,cccRecord);
            }
        }
        /*ASF_Case_Category_Config__c cccRec = [select LOB__c,Business_Unit__c 
FROM ASF_Case_Category_Config__c
WHERE CCC_External_Id__c = :caseRec.CCC_External_Id__c WITH SECURITY_ENFORCED];           
*/
        
        for(Case caseR : cases.values()){
            ASF_Case_Category_Config__c cccRec = mCCCExtIdVsCCCRecord.containsKey(caseR.CCC_External_Id__c) ? mCCCExtIdVsCCCRecord.get(caseR.CCC_External_Id__c) : null;
            if(cccRec == null){
                continue;
            }
            if(caseR.Business_Unit__c == ABFL_Constants.ABFL && ABFL_Constants.ABFL_LOB_COMPLAINT_RCA.contains(cccRec.LOB__c))
            {
                Set<String> blankFields = new Set<String>();  
                
                if(String.isBlank(caseR.ABFL_Case_Detail__r.Case_Categorisation__c))
                {
                    blankFields.add('Case Categorization');               
                }
                else if(caseR.ABFL_Case_Detail__r.Case_Categorisation__c == 'Incorrect')
                {   
                    Map<String, String> fieldsExtensionMap1 = new Map<String, String>{
                        'Correct Category' => caseR.ABFL_Case_Detail__r.Correct_Category__c,
                        'Correct Call Type' => caseR.ABFL_Case_Detail__r.Correct_Call_Type__c ,
                        'Correct Sub Type' => caseR.ABFL_Case_Detail__r.Correct_Sub_Type__c 
                    };

                    for(String fieldExt :fieldsExtensionMap1.keySet())
                    {
                        
                        if(String.isBlank(fieldsExtensionMap1.get(fieldExt)))
                        {
                            blankFields.add(fieldExt);
                        }
                    }
                    fieldsExtensionMap1.clear();// emptying the Map
                }

                               
                if(String.isBlank(caseR.ABFL_Case_Detail__r.Voice_of_Customer__c))
                {
                    blankFields.add('Voice of Customer');                    
                }
                if(String.isBlank(caseR.ABFL_Case_Detail__r.Primary_Erring_Unit__c))
                {
                    blankFields.add('Primary Erring Unit');                    
                }                
                
                if(String.isBlank(caseR.ABFL_Case_Detail__r.Financial_Impact__c))
                {
                    blankFields.add('Financial Impact'); 
                }
                else if(caseR.ABFL_Case_Detail__r.Financial_Impact__c == 'Yes')
                {   
                    Map<String, Decimal> fieldsExtensionMap2 = new Map<String, Decimal>{
                        'Diputed Amount' => caseR.ABFL_Case_Detail__r.Diputed_Amount__c,
                        'Refund Amount' => caseR.ABFL_Case_Detail__r.Refund_Amount__c  
                    };
                    
                    for(String field :fieldsExtensionMap2.keySet()){
                        
                        if(fieldsExtensionMap2.get(field) == null)
                        {
                            blankFields.add(field);
                        }
                    }
                    fieldsExtensionMap2.clear();//emptying the Map
                }
                
                if(String.isBlank(caseR.ABFL_Case_Detail__r.Action_Taken__c))
                {
                    blankFields.add('Action Taken');                    
                }
                
                if(String.isBlank(caseR.ABFL_Case_Detail__r.Grievance_Type__c))
                {
                    blankFields.add('Grievance Type');                    
                }
                
                if(!mCaseIdVsBlankFields.containsKey(caseR.Id)){
                    mCaseIdVsBlankFields.put(caseR.Id,blankFields);
                }
                
            }
            
        }
        
        
        return mCaseIdVsBlankFields;            
    }
    
    
}