force-app/main/default/objects/ABFL_Case_Detail__c/ABFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABFL Case Detail</label>
    <nameField>
        <displayFormat>ABFL-{0000000}</displayFormat>
        <label>ABFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN coming from UNFYD</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LAN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Integration__c/fields/STP_API_Identifier__c.field-meta.xml
<CustomField>
    <fullName>STP_API_Identifier__c</fullName>
    <description>This field is used to store identifier for STP API callouts.</description>
    <label>STP API Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Populate</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>UI Card</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>UI Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABFL Case Detail</label>
    <referenceTo>ABFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Framework.recordType-meta.xml
<RecordType>
    <fullName>Framework</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Framework</label>
</RecordType>

force-app/main/default/objects/Case_Integration_Outbound__e/Case_Integration_Outbound__e.object-meta.xml
<CustomObject>
    <label>Case Integration Outbound</label>
    <pluralLabel>Case Integration Outbound</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Case_Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Integration_ID__c</fullName>
    <label>Case Integration ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Request_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_Payload__c</fullName>
    <label>Request Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ABFL_STP_APIImplementation.cls
/*********************************************************
 *Class        :  ABFL_STP_APIImplementation
 *Author       :  Udit Singhal
 *Description  :  STP API implementation class
 *********************************************************/
public class ABFL_STP_APIImplementation{
    /****************************************************************************************************************
     * @LOB - ABFL
     * @Function - callout
     * @param integRec - ASF_Integration__c record from the framework.
     * @param caseRecord - Case record from the framework.
     * @return - void
     * @Description - Invoked from the ABFL_InvokeSTPProcess class
     *****************************************************************************************************************/
    public static void callout(ASF_Integration__c integRec, Case caseRecord){
        System.debug('In ABFL_STP_APIImplementation');
        System.debug('integRec: ' + integRec);
        System.debug('caseRecord: ' + caseRecord);

        Datetime fromDate =  caseRecord.ABFL_Case_Detail__r.From_Date__c != null ? DateTime.newInstance(caseRecord.ABFL_Case_Detail__r.From_Date__c.year(), caseRecord.ABFL_Case_Detail__r.From_Date__c.month(), caseRecord.ABFL_Case_Detail__r.From_Date__c.day()) : null;
        Datetime toDate = caseRecord.ABFL_Case_Detail__r.To_Date__c != null ? DateTime.newInstance(caseRecord.ABFL_Case_Detail__r.To_Date__c.year(), caseRecord.ABFL_Case_Detail__r.To_Date__c.month(), caseRecord.ABFL_Case_Detail__r.To_Date__c.day()) : null;

        switch  on integRec.STP_API_Identifier__c {
            when 'GetDemandAdvice_Corp' {
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'NEXT_DUE_DATE' => new Map<String, Object>{ 'lte' => Datetime.now().format('dd-MMM-yyyy') } };
                performCallout(integRec, caseRecord, filter);
            }
            when 'GetInterestResetLetter_Corp' {
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c };
                performCallout(integRec, caseRecord, filter);
            }
            when 'GetRepaymentSchedule_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'DUEDATE' => new Map<String, Object>{ 'lte' => System.now().format('dd-MMM-yyyy') } };
                performCallout(integRec, caseRecord, filter);
            }
            when 'GetWelcomeLetter_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c };
                performCallout(integRec, caseRecord, filter);
            }
            when 'InterestDebitNote_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'CBD' => new Map<String, Object>{ 'gte' => fromDate.format('dd-MMM-yyyy'), 'lte' => toDate.format('dd-MMM-yyyy') } };
                performCallout(integRec, caseRecord, filter);
            }
            when 'SOA_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'CBD' => new Map<String, Object>{ 'fromDate' => fromDate.format('dd-MMM-yyyy'), 'toDate' => toDate.format('dd-MMM-yyyy') }, 'TRANSACTIONID' => Long.valueOf(System.now().format('ddMMyyyyhhmmss'))};
                performCallout(integRec, caseRecord, filter);
            }
             
        }
    }
     public static Case_Integration_Outbound__e callout(ASF_Integration__c integRec, Case caseRecord, List<ASF_Case_Integration__c> allCaseInts){
        System.debug('In ABFL_STP_APIImplementation');
        System.debug('integRec: ' + integRec);
        System.debug('caseRecord: ' + caseRecord);

        Datetime fromDate =  caseRecord.ABFL_Case_Detail__r.From_Date__c != null ? DateTime.newInstance(caseRecord.ABFL_Case_Detail__r.From_Date__c.year(), caseRecord.ABFL_Case_Detail__r.From_Date__c.month(), caseRecord.ABFL_Case_Detail__r.From_Date__c.day()) : null;
        Datetime toDate = caseRecord.ABFL_Case_Detail__r.To_Date__c != null ? DateTime.newInstance(caseRecord.ABFL_Case_Detail__r.To_Date__c.year(), caseRecord.ABFL_Case_Detail__r.To_Date__c.month(), caseRecord.ABFL_Case_Detail__r.To_Date__c.day()) : null;

        switch  on integRec.STP_API_Identifier__c {
            when 'GetDemandAdvice_Corp' {
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'NEXT_DUE_DATE' => new Map<String, Object>{ 'lte' => Datetime.now().format('dd-MMM-yyyy') } };
                return performCallout(integRec, caseRecord, filter, allCaseInts);
            }
            when 'GetInterestResetLetter_Corp' {
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c };
                return performCallout(integRec, caseRecord, filter, allCaseInts);
            }
            when 'GetRepaymentSchedule_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'DUEDATE' => new Map<String, Object>{ 'lte' => System.now().format('dd-MMM-yyyy') } };
                return performCallout(integRec, caseRecord, filter, allCaseInts);
            }
            when 'GetWelcomeLetter_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c };
                return performCallout(integRec, caseRecord, filter, allCaseInts);
            }
            when 'InterestDebitNote_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'CBD' => new Map<String, Object>{ 'gte' => fromDate.format('dd-MMM-yyyy'), 'lte' => toDate.format('dd-MMM-yyyy') } };
                return performCallout(integRec, caseRecord, filter, allCaseInts);
            }
            when 'SOA_Corp'{
                Map<String, Object> filter = new Map<String, Object>{ 'AGREEMENTNO' => caseRecord.LAN__c, 'CBD' => new Map<String, Object>{ 'fromDate' => fromDate.format('dd-MMM-yyyy'), 'toDate' => toDate.format('dd-MMM-yyyy') }, 'TRANSACTIONID' => Long.valueOf(System.now().format('ddMMyyyyhhmmss'))};
                return performCallout(integRec, caseRecord, filter, allCaseInts);
            } 
        }
        return null;
    }

    /****************************************************************************************************************
     * @LOB - ABFL
     * @Function - performCallout
     * @param integRec - ASF_Integration__c record from the framework.
     * @param caseRecord - Case record from the framework.
     * @return - void
     * @Description - Invoked from the callout method of ABFL_STP_APIImplementation class
     *****************************************************************************************************************/
    public static void performCallout(ASF_Integration__c integRec, Case caseRecord, Map<String, Object> filter){
        System.debug('In performCallout:' + caseRecord.ID);

        List<ASF_Case_Integration__c> caseIntg = ABFL_SOQL_Integration.getCaseIntegrationInfo(caseRecord.Id, '');

        ABFL_STP_Wrapper wrapper = new ABFL_STP_Wrapper(filter, caseRecord);

        Database.SaveResult publishResult = EventBus.publish(new Case_Integration_Outbound__e(
            Business_Unit__c = caseRecord.Business_Unit__c, 
            Case_Integration_ID__c = caseIntg[0]?.Name, 
            Integration_Name__c = integRec.STP_API_Identifier__c,  // STP_API_Identifier__c is the actual name of API to invoke
            Request_Payload__c = JSON.serialize(wrapper)
        ));
    }
     public static Case_Integration_Outbound__e performCallout(ASF_Integration__c integRec, Case caseRecord, Map<String, Object> filter, List<ASF_Case_Integration__c> allCaseInts){
        System.debug('In performCallout:' + caseRecord.ID);

        //List<ASF_Case_Integration__c> caseIntg = ABFL_SOQL_Integration.getCaseIntegrationInfo(caseRecord.Id, '');
        List<ASF_Case_Integration__c> caseIntg = new List<ASF_Case_Integration__c>();
        if(!allCaseInts.isEmpty()){
            for(ASF_Case_Integration__c caseInt : allCaseInts){
                if(caseInt.Status__c == ABFL_Constants.PENDING && caseInt.Type__c == ''){
                    caseIntg.add(caseInt);
                }
            }
        }
        ABFL_STP_Wrapper wrapper = new ABFL_STP_Wrapper(filter, caseRecord);

        //Database.SaveResult publishResult = EventBus.publish(
        return new Case_Integration_Outbound__e(
                Business_Unit__c = caseRecord.Business_Unit__c, 
                Case_Integration_ID__c = caseIntg[0]?.Name, 
                Integration_Name__c = integRec.STP_API_Identifier__c,  // STP_API_Identifier__c is the actual name of API to invoke
                Request_Payload__c = JSON.serialize(wrapper)
        //)
        );
    }

    // Wrapper to send data
    public class ABFL_STP_Wrapper{
        public Map<String, Object> filter;
        public String reportType;
        public String passwordProtectPDF;
        public String pdfPassword;
        public String encryption;

        public ABFL_STP_Wrapper(Map<String, Object> filter, Case caseRecord){
            this.filter = filter;
            this.reportType = 'pdf';
            this.passwordProtectPDF = 'false';
            this.pdfPassword = '';
            this.encryption = 'false';
        }
    }
}