force-app/main/default/objects/ABFL_Case_Detail__c/ABFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABFL Case Detail</label>
    <nameField>
        <displayFormat>ABFL-{0000000}</displayFormat>
        <label>ABFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABFL Case Details</relationshipLabel>
    <relationshipName>ABFL_Case_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Ebot_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Ebot_Feedback__c</fullName>
    <label>Ebot Feedback</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect Categorization</fullName>
            </value>
            <value>
                <fullName>Incorrect Moddstamp</fullName>
            </value>
            <value>
                <fullName>Incorrect Intent</fullName>
            </value>
            <value>
                <fullName>Incorrect Email Description</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Case Details</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABFL Case Detail</label>
    <referenceTo>ABFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/eBOT_Email_Draft__c.field-meta.xml
<CustomField>
    <fullName>eBOT_Email_Draft__c</fullName>
    <description>Field created to store Email body received from UNFYD Gen AI</description>
    <encryptionScheme>None</encryptionScheme>
    <label>eBOT Email Draft</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Text__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Type_Text__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/CRM_to_UNFYD_Feedback_Event__e.object-meta.xml
<CustomObject>
    <label>CRM to UNFYD Feedback Event</label>
    <pluralLabel>CRM to UNFYD Feedbacks Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Unique Case number created by SFDC</description>
    <label>Case Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>descriptive content (by agent)</description>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Ebot_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Ebot_Feedback__c</fullName>
    <description>Multiple values will be there which are comma-separated. (E.g.: “MOOD STAMP INCORRECT”,” INTENT INCORRECT”, etc)</description>
    <label>Ebot Feedback</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Email_Response_Modified__c.field-meta.xml
<CustomField>
    <fullName>Email_Response_Modified__c</fullName>
    <label>Email Response Modified</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Modified_Email_Response__c.field-meta.xml
<CustomField>
    <fullName>Modified_Email_Response__c</fullName>
    <description>Modified email content</description>
    <label>Modified Email Response</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <description>Category: Query/Request/Complaint</description>
    <label>Nature</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <description>Sub Type selected by Agent</description>
    <label>Subtype</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_to_UNFYD_Feedback_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Case Type selected by Agent</description>
    <label>Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABFL_submitFeedbackToUNFYD.cls
/*********************************************************
*Class        :  ABFL_submitFeedbackToUNFYD
*Author       :  nikhil.patewar@in.ey.com
*Created Date :  28/11/2024
*Last Modified:  28/11/2024
*@description  :  Feedback will be sent to UNFYD via platform event
*********************************************************/
public with sharing class ABFL_submitFeedbackToUNFYD {
    public static void sendUNFYDFeedback(String caseId){
        Map<String, String> fieldsMap = New Map<String, String>();
        List<ASF_Case_Integration__c> caseIntegrationList= New List<ASF_Case_Integration__c>();
        Case caseRecord=[Select Id,CaseNumber,Type_Text__c,Sub_Type_Text__c,Nature__c,eBOT_Email_Draft__c FROM Case where Id=:caseId LIMIT 1];
        ABFL_Case_Detail__c caseDetails=[Select Id,Ebot_Feedback__c,Case__c From ABFL_Case_Detail__c where Case__r.Id =:caseRecord.Id LIMIT 1];
        if(caseRecord!= null && caseDetails!=null){
            
            //Insert ASF_Case_Integration__c
            ASF_Case_Integration__c caseInt = new ASF_Case_Integration__c();    
            caseInt.Case__c = caseRecord.Id;
            caseInt.Status__c = 'Pending';
            caseInt.Type__c = 'FEEDBACK';
            caseIntegrationList.add(caseInt);
            
            if(caseIntegrationList.size()>0 && Schema.sObjectType.ASF_Case_Integration__c.isCreateable()){
                insert caseIntegrationList;
            }
            
            fieldsMap.put('Case_Number__c',caseRecord.CaseNumber);
            if(caseDetails.Ebot_Feedback__c.contains('Incorrect Categorization')){
                fieldsMap.put('Nature__c',caseRecord.Nature__c);
            	fieldsMap.put('Type__c',caseRecord.Type_Text__c);
            	fieldsMap.put('Subtype__c',caseRecord.Sub_Type_Text__c);
            }else{
                fieldsMap.put('Nature__c','');
                fieldsMap.put('Type__c','');
            	fieldsMap.put('Subtype__c','');
            }
            fieldsMap.put('Ebot_Feedback__c',getFormattedMultiSelectValues(caseDetails.Ebot_Feedback__c));
            //fieldsMap.put('Description__c','Yes');
            if(String.isNotBlank(caseRecord.eBOT_Email_Draft__c)){
                fieldsMap.put('Email_Response_Modified__c','Yes');
                fieldsMap.put('Modified_Email_Response__c',caseRecord.eBOT_Email_Draft__c);
            }else{
                fieldsMap.put('Email_Response_Modified__c','No');
                fieldsMap.put('Modified_Email_Response__c','');
            }
            
            //Publish the platform event
            Database.SaveResult eventResult = ABHFL_CasePlatformEventHandler.publishPlatformEvent('CRM_to_UNFYD_Feedback_Event__e', fieldsMap);
        }
    }
    
    public static String getFormattedMultiSelectValues(String multiSelectField) {
        if (String.isBlank(multiSelectField)) {
            return ''; // Return empty string if no value is selected
        }
        
        // Split the multi-select values into a list
        List<String> values = multiSelectField.split(';');
        
        // Add double quotes to each value
        List<String> formattedValues = new List<String>();
        for (String value : values) {
            formattedValues.add('"' + value + '"');
        }
        
        // Join the values with commas and return
        return String.join(formattedValues, ', ');
    }
    
}