force-app/main/default/objects/ABFL_Case_Detail__c/ABFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABFL Case Detail</label>
    <nameField>
        <displayFormat>ABFL-{0000000}</displayFormat>
        <label>ABFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>LOB coming from UNFYD</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LOB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Resolution_Comments__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Comments__c</fullName>
    <label>Resolution Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ABFL_Case_Detail__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OneABC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABFL Case Detail</label>
    <referenceTo>ABFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>This field will get LOB value from related Asset or Account.</description>
    <formula>IF( ISBLANK( AssetId ) || ISBlank(TEXT(Asset.LOB__c )) , Text( Account.Line_of_Business__c ),  TEXT(Asset.LOB__c ))</formula>
    <label>LOB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OnCreateCloseSR__c.field-meta.xml
<CustomField>
    <fullName>OnCreateCloseSR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is coming from API, any channel creating case from API just for tracking purpose, going to send this field value as true, post, record creation, SR status is marked to Closed with Stage as Resolved.</description>
    <label>OnCreateCloseSR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution_Comments__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Comments__c</fullName>
    <label>Resolution Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
            <value>
                <fullName>Phone-Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABFL_ValidateRequireFieldOnResolvedStage.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 01-10-2024
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class ABFL_ValidateRequireFieldOnResolvedStage implements ASF_CaseStageClassInvocable {
    
    public static Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> beforeStageMovement(List<Case> cases){
        
        Map<Id,ASF_CaseMovementHelper.CaseStageValidationWrapper> mCaseIdVsretCls = new Map<Id,ASF_CaseMovementHelper.CaseStageValidationWrapper>();
        
        Set<Id> complaintCaseIds = new Set<Id>();
        
        
        for(Case caseRec : cases){
            ASF_CaseMovementHelper.CaseStageValidationWrapper retCls = new ASF_CaseMovementHelper.CaseStageValidationWrapper();
            retCls.status = 'Success';
            retCls.errorMessage = '';
            retCls.updatedCase = caseRec;
            retCls.isCaseUpdated = false;
            
            if(ASF_Constants.RESOLUTIONCOMMENT_REQ_TECHSRC.contains(caseRec.Technical_Source__c) && !caseRec.OnCreateCloseSR__c){
                if((caseRec.ABFL_Case_Detail__r.Resolution_Comments__c == null || caseRec.ABFL_Case_Detail__r.Resolution_Comments__c == '') &&
                   (!(caseRec.Source__c == 'Phone-Inbound' && caseRec.Nature__c == 'Query')) && ((caseRec.LOB__c == 'Wealth') || (caseRec.LOB__c != 'Wealth' && caseRec.Nature__c != 'Complaint')))
                {
                    retCls.status = 'Error';
                    retCls.errorMessage = 'Resolution Comments is required when changing Stage to Resolved.';
                }
            }
            
            if(caseRec.Nature__c == 'Complaint'){     
                complaintCaseIds.add(caseRec.Id);
            }
            
            mCaseIdVsretCls.put(caseRec.Id,retCls);
        }
        
        // //Complaint Nature Cases RCA Validation, exempt for Wealth LOB   
        if(complaintCaseIds.size()>0){
            Map<Id,Set<String>> retVal = ABFL_ComplaintsValidateOnResolvedStage.validateRCAfields(complaintCaseIds);
            
            if(retVal.keySet().size()>0){
                for(Id retCaseId : retVal.keySet()){
                    if(mCaseIdVsretCls.containsKey(retCaseId)){
                        ASF_CaseMovementHelper.CaseStageValidationWrapper retCls = mCaseIdVsretCls.get(retCaseId);
                        retCls.status = 'Error';
                        retCls.errorMessage = 'Please fill the RCA fields on Verification Stage';
                        mCaseIdVsretCls.put(retCaseId,retCls);
                    }
                }
            }
        }
        
        
        return mCaseIdVsretCls;        
    }
    
    public static Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> afterStageMovement(List<Case> cases){
        Map<Id,ASF_CaseMovementHelper.CaseStageValidationWrapper> mCaseIdVsretCls = new Map<Id,ASF_CaseMovementHelper.CaseStageValidationWrapper>();
        
        return mCaseIdVsretCls;
    }
}