force-app/main/default/objects/ASF_Case_Email_Config__c/ASF_Case_Email_Config__c.object-meta.xml
<CustomObject>
    <label>Case Email Config</label>
    <nameField>
        <displayFormat>RSE-{00000000}</displayFormat>
        <label>Regional SMS Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Email Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Email_Config__c/fields/Case_Category_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Category_Config__c</fullName>
    <label>Case Category Config</label>
    <referenceTo>ASF_Case_Category_Config__c</referenceTo>
    <relationshipName>Regional_SMS_Email_Templates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Email_Config__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gujarathi</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Marathi</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Email_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canned Response</fullName>
            </value>
            <value>
                <fullName>Regional Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Reopen_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Is_Reopen_Allowed__c</fullName>
    <description>Determines if Reopened is allowed on the Case</description>
    <formula>AND(IsClosed, !ISNULL(Reopen_Days__c), Reopen_Days__c !=0, TODAY() &lt; DATEVALUE(ClosedDate) + Reopen_Days__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Reopen Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/No_Auto_Communication__c.field-meta.xml
<CustomField>
    <fullName>No_Auto_Communication__c</fullName>
    <label>No Auto Communication</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reopen_Days__c.field-meta.xml
<CustomField>
    <fullName>Reopen_Days__c</fullName>
    <description>Number of Days till the case can be reopened after closure.</description>
    <label>Reopen Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sent_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ASF_EmailMessageQueryHandler.cls
/**
 * @description - EmailMessage query class
 */
public without sharing class ASF_EmailMessageQueryHandler {
    private static List<Case> queriedCases = null;
    public static List<ASF_Case_Email_Config__c> regionalTemplatesList = null;
    
    /**
     * @description - case records from the email message
     * @param caseIds 
     * @return list<Case> cases with the passed ids
     */
    public static List<Case> getCaseRecords(Set<Id> caseIds){
        if(queriedCases == null){
            queriedCases = [SELECT Id, IsClosed, Is_Reopen_Allowed__c, Reopen_Days__c, ClosedDate, Sent_to_EBOT__c,
            CCC_External_Id__c, AccountId, Channel__c, Origin, Priority, RecordTypeId, SuppliedEmail, SuppliedPhone, SuppliedName, No_Auto_Communication__c,
            Technical_Source__c, Nature__c, ContactId,Business_Unit__c,CaseNumber
            FROM Case 
            WHERE Id IN :caseIds WITH SYSTEM_MODE];
        }
        return queriedCases;
    }
    public static List<ASF_Case_Email_Config__c> getRegionalTemplatesList(Set<Id> cccIdList, Set<String> queryFields) {
        if(regionalTemplatesList == null){
            regionalTemplatesList = (List<ASF_Case_Email_Config__c>) Database.query(
                'SELECT Id, Language__c, Case_Category_Config__c, ' +
                String.join(queryFields, ',') +
                ' FROM ASF_Case_Email_Config__c WHERE Case_Category_Config__c IN :cccIdList AND Type__c = \'Regional Template\''
            );

        }
        return regionalTemplatesList;
    }
    

}