force-app/main/default/objects/ABCL_Integrations__mdt/ABCL_Integrations__mdt.object-meta.xml
<CustomObject>
    <label>ABCL Integrations</label>
    <pluralLabel>ABCL Integrations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Messages__mdt/Custom_Messages__mdt.object-meta.xml
<CustomObject>
    <label>Custom Messages</label>
    <pluralLabel>Custom Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Messages__mdt/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Health_Intent__c/Health_Intent__c.object-meta.xml
<CustomObject>
    <label>Health Intent</label>
    <nameField>
        <displayFormat>HI-{0000000}</displayFormat>
        <label>Health Intent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Intents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_Intent__c/fields/Active_on_Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Active_on_Social_Media__c</fullName>
    <label>Active on Social Media</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Steps</fullName>
            </value>
            <value>
                <fullName>Calories</fullName>
            </value>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Non trackable (FA)</fullName>
            </value>
            <value>
                <fullName>None(FA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Do_you_track_these__c.field-meta.xml
<CustomField>
    <fullName>Do_you_track_these__c</fullName>
    <description>ABHI</description>
    <label>Do you track these</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Frequency_in_a_month__c.field-meta.xml
<CustomField>
    <fullName>Frequency_in_a_month__c</fullName>
    <description>ABHI</description>
    <label>Frequency in a month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-2</fullName>
            </value>
            <value>
                <fullName>3-5</fullName>
            </value>
            <value>
                <fullName>6-9</fullName>
            </value>
            <value>
                <fullName>10-13</fullName>
            </value>
            <value>
                <fullName>&gt;13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Health_Return__c.field-meta.xml
<CustomField>
    <fullName>Health_Return__c</fullName>
    <description>ABHI</description>
    <label>Health Return</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/How_do_you_track_your_activity__c.field-meta.xml
<CustomField>
    <fullName>How_do_you_track_your_activity__c</fullName>
    <label>How do you track your activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Google fit</fullName>
            </value>
            <value>
                <fullName>Fitbit</fullName>
            </value>
            <value>
                <fullName>Garmin</fullName>
            </value>
            <value>
                <fullName>Noise</fullName>
            </value>
            <value>
                <fullName>Jawbone</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Applehealth</fullName>
                <label>Apple health</label>
            </value>
            <value>
                <fullName>S health</fullName>
                <label>Samsung health</label>
            </value>
            <value>
                <fullName>Honor</fullName>
            </value>
            <value>
                <fullName>Amazefit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Member_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Health Intents</relationshipLabel>
    <relationshipName>Health_Intents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Preferred_Communication_Mode__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Communication_Mode__c</fullName>
    <description>ABHI</description>
    <label>Preferred Communication Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Letter</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>ABHI</description>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Marathi</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>Kannada</fullName>
            </value>
            <value>
                <fullName>Malayalam</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Tulu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Social_Media_Id__c.field-meta.xml
<CustomField>
    <fullName>Social_Media_Id__c</fullName>
    <label>Social Media Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Waiting_Period_Permanent_Exclusion__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Period_Permanent_Exclusion__c</fullName>
    <label>Waiting Period &amp; Permanent Exclusion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don’t Remember</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/What_activities_are_you_currently_doing__c.field-meta.xml
<CustomField>
    <fullName>What_activities_are_you_currently_doing__c</fullName>
    <label>What activities are you currently doing</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Walking</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Zumba</fullName>
            </value>
            <value>
                <fullName>Cardio @ home Aerobics</fullName>
            </value>
            <value>
                <fullName>Cycling</fullName>
            </value>
            <value>
                <fullName>Dancing</fullName>
            </value>
            <value>
                <fullName>Workouts</fullName>
            </value>
            <value>
                <fullName>Cardio</fullName>
            </value>
            <value>
                <fullName>Swimming</fullName>
            </value>
            <value>
                <fullName>Yoga @ gym</fullName>
            </value>
            <value>
                <fullName>Yoga @ home</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Health_Intent__c/fields/Which_phone_are_you_using__c.field-meta.xml
<CustomField>
    <fullName>Which_phone_are_you_using__c</fullName>
    <label>Which phone are you using</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Android</fullName>
            </value>
            <value>
                <fullName>Basic Phone</fullName>
            </value>
            <value>
                <fullName>Does not use phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABHI_CreateHealthIntent_Inbound.cls
/*********************************************************
*Class        :  ABHI_CreateHealthIntent_Inbound
*Author       :  Shubham Sinha 
*Created Date :  07/08/2024
*Last Modified:  07/08/2024
*@description  :  This webservice is to create health intent records in SFDC.
*********************************************************/
@RestResource(urlMapping='/CreateHealthIntent/*')
global with sharing class ABHI_CreateHealthIntent_Inbound {
    @HttpPost
    global static String processHealthData() {
        ABHI_CreateHealthIntentRequestWrapper.RequestBody requestBody;
        String accountId;
        Boolean hasError = false;
        ABCL_IntegrationCallout.IntegrationResponseWrapper integrationResponse = new ABCL_IntegrationCallout.IntegrationResponseWrapper();
        ABCL_Integrations__mdt integrationMdt = ABCL_IntegrationCallout.getIntegrationMetadata('ABHI_CreateHealthIntent_Inbound');
        integrationResponse.requestBody = RestContext.request.requestBody.toString();

        try {
            // Parsing the JSON request into the RequestBody class
            requestBody = (ABHI_CreateHealthIntentRequestWrapper.RequestBody)JSON.deserialize(RestContext.request.requestBody.toString(), ABHI_CreateHealthIntentRequestWrapper.RequestBody.class);
            
            // Checking for member id 
            try {
                accountId = [SELECT Id, Client_Code__c FROM Account WHERE Client_Code__c = :requestBody.MemberId].Id;
                ABCL_IntegrationCallout.accountId = accountId;
            } catch (Exception e) {
                integrationResponse.responseBody = JSON.serialize(createFailureResponse('100', 'Failure', Custom_Messages__mdt.getInstance('ABHI_MemberID_Not_Found').Message__c));
                hasError = true;
                return integrationResponse.responseBody; 
            }

            // Preparing to collect Health intent records
            List<Health_Intent__c> lsthealthIntent = new List<Health_Intent__c>();
            for (ABHI_CreateHealthIntentRequestWrapper.CategoryDetail category : requestBody.CategoryDetails) {
                for (ABHI_CreateHealthIntentRequestWrapper.ActivityDetail detail : category.ActivityDetails) {
                    Health_Intent__c healthIntentRecord = new Health_Intent__c();
                    healthIntentRecord.Member_Id__c = accountId;
                    healthIntentRecord.Active_on_Social_Media__c = requestBody.ActiveOnSocialMedia;
                    healthIntentRecord.Health_Return__c = requestBody.HealthReturn;
                    healthIntentRecord.Preferred_Communication_Mode__c = requestBody.PreferredCommunicationMode;
                    healthIntentRecord.Preferred_Language__c = requestBody.PreferredLanguage;
                    healthIntentRecord.Social_Media_Id__c = requestBody.SocialMediaId;
                    healthIntentRecord.Source__c = requestBody.Source;
                    healthIntentRecord.Waiting_Period_Permanent_Exclusion__c = requestBody.WaitingPeriodAndExclusive;
                    healthIntentRecord.Which_phone_are_you_using__c = requestBody.WhichPhone;
                    healthIntentRecord.Category__c = category.Category;
                    healthIntentRecord.Do_you_track_these__c = detail.DoYouTrackThese;
                    healthIntentRecord.Frequency_in_a_month__c = detail.FrequencyInMonth;
                    healthIntentRecord.How_do_you_track_your_activity__c = detail.HowDoYouTrackYourActivity;
                    healthIntentRecord.What_activities_are_you_currently_doing__c = detail.WhatActivitiesCurrentlyDoing;
                    lsthealthIntent.add(healthIntentRecord);
                }
            }

            // Inserting the HealthIntent records
            try {
                if (!lsthealthIntent.isEmpty()) {
                    insert lsthealthIntent;
                }
                integrationResponse.responseBody = JSON.serialize(createSuccessResponse(requestBody.MemberId));
            } catch (DmlException e) {
                integrationResponse.responseBody = JSON.serialize(createFailureResponse('100', 'Failure', 'Error in creating healthintent records: ' + e.getMessage()));
                hasError = true;
            }

        } catch (Exception e) {
            integrationResponse.responseBody = JSON.serialize(createFailureResponse('100', 'Failure', Custom_Messages__mdt.getInstance('ABHI_InvalidJson').Message__c));
            hasError = true;
        } finally {
            // Handling response in a single place
            ABCL_IntegrationCallout.handleResponse(integrationMdt, integrationResponse, hasError);
        }

        return integrationResponse.responseBody;
    }

   
    public static ABHI_ResponseWrapper createSuccessResponse(String memberId) {
        ABHI_ResponseWrapper response = new ABHI_ResponseWrapper(
            '200',
            'Success',
            Custom_Messages__mdt.getInstance('ABHI_SuccessMessage').Message__c
        );
        //response.ProposalNumber = memberId; // Assuming you want to assign the memberId to ProposalNumber
        return response;
    }

    public static ABHI_ResponseWrapper createFailureResponse(String statusCode, String statusMessage, String statusRemarks) {
        return new ABHI_ResponseWrapper(statusCode, statusMessage, statusRemarks);
    }
}