force-app/main/default/objects/ABCL_Integrations__mdt/ABCL_Integrations__mdt.object-meta.xml
<CustomObject>
    <label>ABCL Integrations</label>
    <pluralLabel>ABCL Integrations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch_Master__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch_Master__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Last_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Disbursement_Date__c</fullName>
    <label>Last Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Loan_Disbursement_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Disbursement_Status__c</fullName>
    <label>Loan Disbursement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partially</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch_Master__c/Branch_Master__c.object-meta.xml
<CustomObject>
    <label>Branch Master</label>
    <nameField>
        <label>Branch Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Master__c/fields/Branch_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Queue_Id__c</fullName>
    <label>Branch  Queue Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_Master__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>UniqueKey</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABHFL_RoiHistoryTest.cls
@IsTest
public class ABHFL_RoiHistoryTest {
	
    @TestSetup
    static void testData(){
        Account accRec = ASF_TestDataFactory.insertBusinessAccount('ABHFLLLL','Test_1');
        
        Branch_Master__c branchMstr = new Branch_Master__c();
        branchMstr.Branch_Queue_Id__c = [Select Id from Group where Type = 'Queue' LIMIT 1].Id;
        branchMstr.UniqueKey__c = '234234';
        insert branchMstr;

        Asset astRec = ASF_TestDataFactory.createAsset(accRec.Id,'Loans');
        astRec.LAN__c = 'Test12345';
        astRec.Branch__c = branchMstr.Id;
        astRec.Last_Disbursement_Date__c = Date.Today();
        astRec.Loan_Disbursement_Status__c = 'Fully';
        update astRec;
    }
    
    @IsTest
    static void testfetchRoiHistory(){
        ABHFL_RoiHistoryClass.RoiHistoryResponseWrapper wrapper = new ABHFL_RoiHistoryClass.RoiHistoryResponseWrapper();
        Asset ast = [SELECT Id, LAN__c,Loan_Disbursement_Status__c FROM Asset LIMIT 1];
        
        MultiStaticResourceCalloutMock mock = new MultiStaticResourceCalloutMock();
        mock.setStaticResource(ABCL_Integrations__mdt.getInstance('ROI_History_Details').EndPoint__c,'RoiHistoryMockResponse');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        wrapper = ABHFL_RoiHistoryClass.fetchRoiHistory(ast.Id);
        Test.stopTest();
        System.assertEquals('Test12345',ast.LAN__c);
    }
    
}