force-app/main/default/objects/ABCL_Integrations__mdt/ABCL_Integrations__mdt.object-meta.xml
<CustomObject>
    <label>ABCL Integrations</label>
    <pluralLabel>ABCL Integrations</pluralLabel>
</CustomObject>

force-app/main/default/objects/ABCL_Integrations__mdt/fields/Exception_Log__c.field-meta.xml
<CustomField>
    <fullName>Exception_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exception Log</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABCL_Integrations__mdt/fields/Full_Log__c.field-meta.xml
<CustomField>
    <fullName>Full_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Full Log</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABCL_Integrations__mdt/fields/StoreAsAttachment__c.field-meta.xml
<CustomField>
    <fullName>StoreAsAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>StoreAsAttachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Exception_Log__c.field-meta.xml
<CustomField>
    <fullName>Exception_Log__c</fullName>
    <label>Exception Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>This field will be used to store request and re-use them while re-invocation.</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABHI_ResponseWrapper.cls
/*********************************************************
*Class        :  ABHI_ResponseWrapper
*Author       :  Aditee Churiwala
*Created Date :  08/09/2024
*Last Modified:  08/09/2024
*@description :  Create response wrapper
*********************************************************/
public with sharing class ABHI_ResponseWrapper {
    public String ProposalNumber;
    public String StatusCode { get; set; }
    public String StatusMessage { get; set; }
    public String StatusRemarks { get; set; }

    public ABHI_ResponseWrapper(String StatusCode, String StatusMessage, String StatusRemarks) {
        this.StatusCode = StatusCode;
        this.StatusMessage = StatusMessage;
        this.StatusRemarks = StatusRemarks;
    }
     public static ABCL_IntegrationCallout.IntegrationResponseWrapper createLog(ASF_Case_Integration__c integrationLog, ABCL_Integrations__mdt integrationMdt,ABCL_IntegrationCallout.IntegrationResponseWrapper integrationResponse, Boolean hasError){
        if(!hasError){
            integrationLog.Status__c = ABHI_Constants.SUCCESS;
            integrationResponse = ABCL_IntegrationCallout.getStaticResource(integrationMdt,integrationResponse);
        } else {
            integrationLog.Status__c = ABHI_Constants.FAILURE;
        }

        if(!integrationMdt.StoreAsAttachment__c){
            integrationLog.Response__c = integrationResponse.responseBody;
            integrationLog.Request__c = integrationResponse.requestBody;
        }
        
        if(integrationMdt.Full_Log__c || (integrationMdt.Exception_Log__c && hasError)){
            if(Schema.sObjectType.ASF_Case_Integration__c.isCreateable()){
                insert integrationLog;
                ABCL_IntegrationCallout.storeResponseAttachment(integrationMdt,integrationResponse,integrationLog.Id);
            }
        }        
        return integrationResponse;
    }
}