force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <externalId>true</externalId>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABSLI_PolicyDynamicButtonsControllerTest.cls
@isTest
public class ABSLI_PolicyDynamicButtonsControllerTest {
    @isTest
    public static void getServAceUrl(){
        Asset policy = new Asset();
        policy.Name = '000000001';
        policy.Policy_No__c = '000000001';
        policy.LAN__c = 'ABSLI_000000001';
        policy.Business_Unit__c = 'ABSLI';
		
        Test.StartTest();
        insert policy;
        
        ABSLI_PolicyDynamicButtonsController.getServAceUrl(policy.Id);
        ABSLI_PolicyDynamicButtonsController.getCommunicationLink(policy.Id);
        Test.StopTest();
    }

}