force-app/main/default/objects/ASF_CommnunicationLog__e/ASF_CommnunicationLog__e.object-meta.xml
<CustomObject>
    <label>ASF_CommnunicationLog</label>
    <pluralLabel>ASF_CommnunicationLogs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/CCCExternalId__c.field-meta.xml
<CustomField>
    <fullName>CCCExternalId__c</fullName>
    <label>CCCExternalId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/CustomMetadataName__c.field-meta.xml
<CustomField>
    <fullName>CustomMetadataName__c</fullName>
    <label>CustomMetadataName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/PELoggerId__c.field-meta.xml
<CustomField>
    <fullName>PELoggerId__c</fullName>
    <label>PELoggerId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>RecordID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <label>Unique Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>This field will get LOB value from related Asset or Account.</description>
    <formula>IF( ISBLANK( AssetId ) || ISBlank(TEXT(Asset.LOB__c )) , Text( Account.Line_of_Business__c ),  TEXT(Asset.LOB__c ))</formula>
    <label>LOB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Auto_Communication__c.field-meta.xml
<CustomField>
    <fullName>No_Auto_Communication__c</fullName>
    <label>No Auto Communication</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not classified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PE_Logger__c/PE_Logger__c.object-meta.xml
<CustomObject>
    <label>PE Logger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PE Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PE Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PE_Logger__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PE Loggers</relationshipLabel>
    <relationshipName>PE_Loggers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/CCCExternalId__c.field-meta.xml
<CustomField>
    <fullName>CCCExternalId__c</fullName>
    <label>CCCExternalId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/CustomMetadataName__c.field-meta.xml
<CustomField>
    <fullName>CustomMetadataName__c</fullName>
    <label>CustomMetadataName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <label>Email Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/No_Auto_Communication__c.field-meta.xml
<CustomField>
    <fullName>No_Auto_Communication__c</fullName>
    <label>No Auto Communication</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/PE_Name__c.field-meta.xml
<CustomField>
    <fullName>PE_Name__c</fullName>
    <label>PE Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>RecordID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Retry_PE__c.field-meta.xml
<CustomField>
    <fullName>Retry_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry PE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Send_To_Specific_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Specific_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used when Email to be sent to specific email addresses and not to Case Account Contact or related addresses.</description>
    <label>Send To Specific Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Send_To_Specific_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Specific_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To Specific Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Specific_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Specific_To_Address__c</fullName>
    <description>This to be use in combination with Send to Specific Address checkbox.</description>
    <label>Specific To Address</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Specific_To_MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>Specific_To_MobilePhone__c</fullName>
    <label>Specific To MobilePhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <label>Unique Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ASF_SendCustomerCommunication.cls
/**
 * @description - used to send communication to the customer
 */
@SuppressWarnings('PMD.CognitiveComplexity,PMD.CyclomaticComplexity,PMD.AvoidDeeplyNestedIfStmts,PMD.ExcessiveParameterList, PMD.UnusedLocalVariable')
public without sharing class ASF_SendCustomerCommunication {
    /**
     * @description - Sends an communication to specific Email & Mobile
     * @param caseRec - current case record
     * @param emailTemplate - Email template Name
     * @param specificEmailId - Specific email id
     * @param smsCustomMetadataName - Custom metadata name of SMS
     * @param specificMobileNumber - specfic mobile
     */
    public static void sendCustomerCommunicationToSpecificEmailAndMobile(Case caseRec, String emailTemplate, String specificEmailId,String smsCustomMetadataName, String specificMobileNumber){
        PE_Logger__c peLogger = new PE_Logger__c();
        peLogger.AccountId__c = caseRec.AccountId;
        peLogger.CCCExternalId__c = caseRec.CCC_External_Id__c;
        peLogger.Case__c = caseRec.Id;
        peLogger.ContactId__c = caseRec.ContactId;
        peLogger.PE_Name__c = 'CommunicationLog';
        peLogger.RecordID__c = caseRec.Id;
        peLogger.Retry_PE__c = true;
        peLogger.Status__c = 'Pending';
        peLogger.LOB__c = caseRec.Business_Unit__c;
        peLogger.No_Auto_Communication__c = caseRec.No_Auto_Communication__c;
        if(specificMobileNumber != null && specificMobileNumber != ''){
            peLogger.Send_To_Specific_Mobile__c = TRUE;
            peLogger.Specific_To_MobilePhone__c = specificMobileNumber;
            peLogger.CustomMetadataName__c = smsCustomMetadataName;
        }
        peLogger.Send_To_Specific_Emails__c = True;
        peLogger.Specific_To_Address__c = specificEmailId;
        peLogger.Email_Template_Name__c = emailTemplate;
        if(Schema.sObjectType.PE_Logger__c.isCreateable())
        {
            insert peLogger;    
        }
        Database.SaveResult eventResult = invokeCommunicationLogPlatformEvent(caseRec, peLogger); 
    }
    
    /**
     * @description - to invoke the platform event
     * @param caseRec - current case reord
     * @param peLogger - current pelogger record
     * @return Database.SaveResult
     */
    private static Database.SaveResult invokeCommunicationLogPlatformEvent(Case caseRec, PE_Logger__c peLogger){
        ASF_CommnunicationLog__e commEvent = new ASF_CommnunicationLog__e();
        commEvent.CCCExternalId__c = caseRec.CCC_External_Id__c;
        commEvent.PELoggerId__c = peLogger.Id;
        commEvent.RecordID__c = caseRec.Id;
        commEvent.Unique_Id__c = 'CommunicationLog-'+UserInfo.getUserId()+'-'+System.currentTimeMillis();
        Database.SaveResult eventResult = EventBus.publish(commEvent);
        return eventResult;
    }
    
    
}