force-app/main/default/objects/ASF_CommnunicationLog__e/ASF_CommnunicationLog__e.object-meta.xml
<CustomObject>
    <label>ASF_CommnunicationLog</label>
    <pluralLabel>ASF_CommnunicationLogs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/CustomMetadataName__c.field-meta.xml
<CustomField>
    <fullName>CustomMetadataName__c</fullName>
    <label>CustomMetadataName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/PELoggerId__c.field-meta.xml
<CustomField>
    <fullName>PELoggerId__c</fullName>
    <label>PELoggerId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_CommnunicationLog__e/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>RecordID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not classified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Notification_Config__mdt/Customer_Notification_Config__mdt.object-meta.xml
<CustomObject>
    <label>Customer Notification Config</label>
    <pluralLabel>Customer Notifications Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewal In Progress</fullName>
                <default>true</default>
                <label>Renewal In Progress</label>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PE_Logger__c/PE_Logger__c.object-meta.xml
<CustomObject>
    <label>PE Logger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PE Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PE Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PE_Logger__c/fields/CC_Addresses__c.field-meta.xml
<CustomField>
    <fullName>CC_Addresses__c</fullName>
    <description>List of CC addresses to which notification should be sent</description>
    <label>CC Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/CustomMetadataName__c.field-meta.xml
<CustomField>
    <fullName>CustomMetadataName__c</fullName>
    <label>CustomMetadataName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <label>Email Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <description>ID of the renewals opportunity for which notification is being sent</description>
    <label>Opportunity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/PE_Name__c.field-meta.xml
<CustomField>
    <fullName>PE_Name__c</fullName>
    <label>PE Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>RecordID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Send_To_Specific_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Specific_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used when Email to be sent to specific email addresses and not to Case Account Contact or related addresses.</description>
    <label>Send To Specific Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Send_To_Specific_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Specific_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To Specific Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Specific_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Specific_To_Address__c</fullName>
    <description>This to be use in combination with Send to Specific Address checkbox.</description>
    <label>Specific To Address</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Specific_To_MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>Specific_To_MobilePhone__c</fullName>
    <label>Specific To MobilePhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PE_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RNWL_Communications__mdt/RNWL_Communications__mdt.object-meta.xml
<CustomObject>
    <label>RNWL Communications</label>
    <pluralLabel>RNWL Communications</pluralLabel>
</CustomObject>

force-app/main/default/objects/RNWL_Communications__mdt/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RNWL_Communications__mdt/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
                <default>true</default>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RNWL_Communications__mdt/fields/Metadata_Name__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Name__c</fullName>
    <label>Metadata Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RNWL_Communications__mdt/fields/SMS__c.field-meta.xml
<CustomField>
    <fullName>SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RNWL_Communications__mdt/fields/User_Friendly_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Friendly_Name__c</fullName>
    <label>User Friendly Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RNWL_Communications__mdt/fields/WhatsApp__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WhatsApp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RNWL_CommunicationFrameworkController.cls
/************************************************************************************
*Class          :  RNWL_CommunicationFrameworkController
*Author         :  Gaurav Sharma
*Created Date   :  21/10/2024
*Last Modified  :  21/10/2024
*@description   :  Class is used for RNWL communication templates on renewal Request
************************************************************************************/
public with sharing class RNWL_CommunicationFrameworkController {
    
    @AuraEnabled
    public static List<RNWL_Communications__mdt> fetchCommunicationMDT() {
        List<RNWL_Communications__mdt> mdt = [SELECT Id, Email__c, Entity__c, SMS__c, Metadata_Name__c, User_Friendly_Name__c, WhatsApp__c
            FROM RNWL_Communications__mdt
            WHERE Entity__c = 'Opportunity' AND
            Is_Active__c = TRUE
            LIMIT 50000];
        return mdt;
    }

    @AuraEnabled
    public static String notifyUsers(String requestJSON) {
        try {
            RequestWrapper requestInst = (RequestWrapper) JSON.deserialize(requestJSON, RequestWrapper.class);
            if (String.isBlank(requestInst.opportunityId)) {
                return null;
            }
            Opportunity oppRecord = [SELECT Id, AccountId FROM Opportunity WHERE Id = :requestInst.opportunityId];
            Contact contactRecord;
            // LIMIT 1 is used because all ABHI Accounts have only one contact
            for (Contact each : [SELECT Id FROM Contact WHERE AccountId = :oppRecord.AccountId LIMIT 1]) {
                contactRecord = each;
            }
            Customer_Notification_Config__mdt notificationMD = Customer_Notification_Config__mdt.getInstance(requestInst.selectedTemplate);
            PE_Logger__c peLoggerRecord = new PE_Logger__c(AccountId__c = oppRecord.AccountId, ContactId__c = contactRecord.Id, Opportunity_ID__c = oppRecord.Id,
                RecordID__c = oppRecord.Id, PE_Name__c = 'Communication Log', Status__c = 'Pending', LOB__c = 'ABHI Renewals', CustomMetadataName__c = requestInst.selectedTemplate,
                Send_To_Specific_Mobile__c = String.isNotBlank(requestInst.alternateMobile), Specific_To_MobilePhone__c = requestInst.alternateMobile,
                Send_To_Specific_Emails__c = String.isNotBlank(requestInst.toAddresses), Specific_To_Address__c = requestInst.toAddresses,
                CC_Addresses__c = requestInst.ccAddresses, Email_Template_Name__c = notificationMD.Email_Template_Name__c);
            insert peLoggerRecord;
            ASF_CommnunicationLog__e communicationLog = new ASF_CommnunicationLog__e(CustomMetadataName__c = requestInst.selectedTemplate, PELoggerId__c = peLoggerRecord.Id,
                RecordID__c = oppRecord.Id);
            Eventbus.publish(communicationLog);
        } catch (Exception e) {
            AuraHandledException exceptionInst = new AuraHandledException('There was an error initiating this communicaiton. Please reach out to your admin: ' + e.getMessage());
            exceptionInst.setMessage('There was an error initiating this communicaiton. Please reach out to your admin: ' + e.getMessage());
            throw exceptionInst;
        }
        return 'Initiated communication successfully';
    }

    public class RequestWrapper {
        public String selectedTemplate;
        public String notificationMode;
        public String alternateMobile;
        public String toAddresses;
        public String ccAddresses;
        public String opportunityId;
    }
}