force-app/main/default/objects/ASF_Communication_Log__c/ASF_Communication_Log__c.object-meta.xml
<CustomObject>
    <label>Communication Log</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Communication Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Communication_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Communication Logs</relationshipLabel>
    <relationshipName>Communication_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Communication Logs</relationshipLabel>
    <relationshipName>Communication_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Communication Logs</relationshipLabel>
    <relationshipName>Communication_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <defaultValue>&quot;Customer&quot;</defaultValue>
    <label>Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/External_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Template_ID__c</fullName>
    <label>External Template ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/SMS_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Entity_Id__c</fullName>
    <label>SMS Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/SMS_LT_Name__c.field-meta.xml
<CustomField>
    <fullName>SMS_LT_Name__c</fullName>
    <label>SMS LT Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/SMS_Msg_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Msg_Body__c</fullName>
    <label>SMS Msg Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/SMS_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Sender_Id__c</fullName>
    <label>SMS Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Communication_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>SMS Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Not Sent</fullName>
                <default>true</default>
                <label>Not Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch_Master__c/Branch_Master__c.object-meta.xml
<CustomObject>
    <label>Branch Master</label>
    <nameField>
        <label>Branch Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Business_Unit__c,&quot;ABSLI&quot;), &quot;ABSLI&quot;, &quot;&quot;)</defaultValue>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch_Master__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Business_Unit__c,&quot;ABSLI&quot;), &quot;ACTIVE&quot;, &quot;&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>IN-ACTIVE</fullName>
            </value>
            <value>
                <fullName>...</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not classified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Notification_Config__mdt/Customer_Notification_Config__mdt.object-meta.xml
<CustomObject>
    <label>Customer Notification Config</label>
    <pluralLabel>Customer Notifications Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Notification_Config__mdt/fields/external_templateID__c.field-meta.xml
<CustomField>
    <fullName>external_templateID__c</fullName>
    <label>external templateID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Notification_Config__mdt/fields/SMS_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Entity_Id__c</fullName>
    <label>SMS Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Notification_Config__mdt/fields/SMS_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Sender_Id__c</fullName>
    <label>SMS Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Notification_Config__mdt/fields/SMS_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>SMS_Template_Name__c</fullName>
    <label>SMS Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Communication__e/Outbound_Communication__e.object-meta.xml
<CustomObject>
    <label>Outbound Communication</label>
    <pluralLabel>Outbound Communications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Outbound_Communication__e/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Communication__e/fields/LogID__c.field-meta.xml
<CustomField>
    <fullName>LogID__c</fullName>
    <label>LogID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Communication__e/fields/SMS_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Entity_Id__c</fullName>
    <label>SMS Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Communication__e/fields/SMS_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Sender_Id__c</fullName>
    <label>SMS Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Communication__e/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <label>Template ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Communication__e/fields/Txt_Msg__c.field-meta.xml
<CustomField>
    <fullName>Txt_Msg__c</fullName>
    <label>Txt Msg</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Retail - Secured</fullName>
    </customValue>
    <customValue>
        <fullName>Retail - Unsecured</fullName>
    </customValue>
    <customValue>
        <fullName>Wealth</fullName>
    </customValue>
    <customValue>
        <fullName>Not classified</fullName>
    </customValue>
    <customValue>
        <fullName>HFC</fullName>
    </customValue>
    <customValue>
        <fullName>ABHFL</fullName>
    </customValue>
    <customValue>
        <fullName>ABWM</fullName>
    </customValue>
    <customValue>
        <fullName>ABSLI</fullName>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ABSLI_BranchAddressButtonController.cls
public without sharing class ABSLI_BranchAddressButtonController {
    public static final string strMetadataName = 'ABSLI_Branch_Address';
    @AuraEnabled
    public static Branch_Master__c getBranchDetails(String branchId){
        return [SELECT ID,Name,Address__c,Phone__c,City__c,State__c,Pincode__c FROM Branch_Master__c WHERE Id=: branchId LIMIT 1];
    }
    @AuraEnabled(cacheable=true)
    public static String getTemplateBody(String whatId,String branchId){
        Customer_Notification_Config__mdt commMdt= [SELECT ID,SMS_Template_Name__c FROM Customer_Notification_Config__mdt 
                                             WHERE DeveloperName=: strMetadataName ];
        EMAILTemplate eTemplate = [SELECT ID,HTMLValue FROM EMAILTemplate WHERE DeveloperName =: commMdt.SMS_Template_Name__c];
        String retVal = generateMessageBody(eTemplate.Id,UserInfo.getUserId(), branchId,true);
        return retVal;
    }
    private static String generateMessageBody(String templateID, String whoID, String whatID, Boolean isPlainText){
        Messaging.SingleEmailMessage msg = Messaging.renderStoredEmailTemplate(templateID, whoId, whatID, Messaging.AttachmentRetrievalOption.NONE); 
        String richTextMessage = msg.getHtmlBody(); 
        return isPlainText ? richTextMessage.StripHtmlTags() : richTextMessage;
    }
    @AuraEnabled
    public static void sendCommunication(string accountId,string branchId,string unregisteredNumber){
        Contact c = [SELECT ID,MobilePhone,Name FROM Contact WHERE AccountId = : accountId LIMIT 1];
        Customer_Notification_Config__mdt commMdt= [SELECT ID,SMS_Entity_Id__c,
                                                    SMS_Sender_Id__c,SMS_Template_Name__c,external_templateID__c
                                                    FROM Customer_Notification_Config__mdt 
                                             WHERE DeveloperName=: strMetadataName ];
        if(c.MobilePhone != null && c.MobilePhone != ''){
            List<ASF_Communication_Log__c> masterLogs = new List<ASF_Communication_Log__c>();
            String templateBody = getTemplateBody(accountId,branchId);
            ASF_Communication_Log__c cLog = new ASF_Communication_Log__c();
            cLog.Account__c = accountId;
            cLog.Contact__c = c.Id;
            cLog.Contact_Name__c = c.Name;
            cLog.SMS_Entity_Id__c = commMdt.SMS_Entity_Id__c;
            cLog.SMS_Sender_Id__c = commMdt.SMS_Sender_Id__c;
            cLog.SMS_LT_Name__c = commMdt.SMS_Template_Name__c;
            cLog.External_Template_ID__c = commMdt.external_templateID__c;
            cLog.Status__c = 'In Progress';
            cLog.SMS_Msg_Body__c = templateBody;
            cLog.Phone__c = c.MobilePhone;
            if(unregisteredNumber != null && unregisteredNumber != ''){
                cLog.Phone__c = unregisteredNumber;
            }
            
            cLog.LOB__c = 'ABSLI';
            insert cLog;
            System.debug('record Inserted...'+cLog.Id);
            
            List<Outbound_Communication__e> eventList = new List<Outbound_Communication__e>();
            eventList.add(createOutboundCommunication(cLog,'SMS'));
            List<Database.SaveResult> results = EventBus.publish(eventList);
            System.debug(results);
        }
        
        
    }
    private static Outbound_Communication__e createOutboundCommunication(ASF_Communication_Log__c log,String msgType){
        System.debug('***createOutboundCommunication --> ');
        Outbound_Communication__e event = new Outbound_Communication__e(LogID__c  =log.id,
                                                                        Case__c = log.Case__c,
                                                                        Template_ID__c  = log.External_Template_ID__c ,
                                                                        Phone__c  =log.Phone__c,
                                                                        Txt_Msg__c = log.SMS_Msg_Body__c,
                                                                        LOB__c = log.LOB__c,
                                                                        Type__c = msgType,
                                                                        SMS_Entity_Id__c = log.SMS_Entity_Id__c,
                                                                        SMS_Sender_Id__c = log.SMS_Sender_Id__c
                                                                        );
        
        return event;
    }

}