force-app/main/default/objects/ABHFL_Payment__c/ABHFL_Payment__c.object-meta.xml
<CustomObject>
    <description>Object to record Payments associated with a case</description>
    <label>ABHFL Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>ABHFL Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ABHFL_Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Parent Case for the Payment</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Payments</relationshipLabel>
    <relationshipName>ABFL_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ABHFL_Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ABHFL_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Escrow</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>POS-NEFT</fullName>
            </value>
            <value>
                <fullName>POS-UPI</fullName>
            </value>
            <value>
                <fullName>Payment Link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABHFL_Payment__c/fields/Payment_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Payment_Identifier__c</fullName>
    <label>Payment Identifier</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Checklist__c/ASF_Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Checklist__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Checklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABHFL_MultiplePaymentsController_Test.cls
@isTest
public class ABHFL_MultiplePaymentsController_Test {
    
    @TestSetup
    static void setup(){

        ASF_TestDataFactory.createC3WithPrePopulateIntegrations();
        List<Case> cases = ASF_TestDataFactory.createCaseRecords(1);

        Case caseRec = [SELECT Id FROM case LIMIT 1];
        ASF_Checklist__c chk1 = new ASF_Checklist__c(Case__c = caseRec.Id, Status__c ='Pending', Label__c= 'Create Payment');
        insert chk1;

    }

    @IsTest
    static void testGetPaymentsForCase(){

        Case caseRec = [
                        SELECT Id 
                        FROM Case
                        LIMIT 1
                        ];


        List<ABHFL_Payment__c> payments = ABHFL_MultiplePaymentsController.getPaymentsForCase(caseRec.Id);
        // No payments
        system.assertEquals(0, payments.size());

        // Add some Payments
        caseRec.stage__c = 'Open';
        //update caseRec;

        ABHFL_Payment__c payment1 = new ABHFL_Payment__c();
        payment1.Payment_Identifier__c = '2w53423';
        payment1.Amount__c = 34532423;
        payment1.Mode_of_Payment__c = 'Cheque';
        payment1.Date__c = Date.today();
        payment1.Case__c=caseRec.id;
        ABHFL_MultiplePaymentsController.savePayments(caseRec.Id, new List<ABHFL_Payment__c>{payment1});

        List<ABHFL_Payment__c> paymentsAfter = ABHFL_MultiplePaymentsController.getPaymentsForCase(caseRec.Id);
        // No payments
        system.assertEquals(1, paymentsAfter.size());

    }

    @IsTest
    static void testSavePaymentsForCase(){

        Case caseRec = [
                        SELECT Id 
                        FROM Case
                        LIMIT 1
                        ];
        // Add some Payments, with Error
        
        ABHFL_Payment__c payment1 = new ABHFL_Payment__c();
        payment1.Amount__c = 34532423;
        payment1.Mode_of_Payment__c = 'Cheque';
        payment1.Date__c = Date.today();
        payment1.Case__c=caseRec.id;

        try{
            ABHFL_MultiplePaymentsController.savePayments(caseRec.Id, new List<ABHFL_Payment__c>{payment1});
        }
        catch(Exception ex){
            // Since Payment Identifier is Required, should throw exception
            assert.isTrue(true);
        }

    }

    @IsTest
    static void testdeletePaymentRecord(){
         Case caseRec = [
                        SELECT Id 
                        FROM Case
                        LIMIT 1
                        ];

        ABHFL_Payment__c payment1 = new ABHFL_Payment__c();
        payment1.Payment_Identifier__c = '2w53423';
        payment1.Amount__c = 34532423;
        payment1.Mode_of_Payment__c = 'Cheque';
        payment1.Date__c = Date.today();
        payment1.Case__c=caseRec.id;

        insert payment1;
        String result = ABHFL_MultiplePaymentsController.deletePaymentRecord(payment1.Id);
        System.assertEquals('deleted', result);
    }
}