force-app/main/default/objects/ABSLI_IGMS_Document__c/ABSLI_IGMS_Document__c.object-meta.xml
<CustomObject>
    <description>This Object is used to store the IGMS File Details in IGMS to CRM Complaint Inbound API.</description>
    <label>ABSLI IGMS Document</label>
    <nameField>
        <displayFormat>IGMS-DOC-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI IGMS Docuements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This Field to store the Master Detail relation between Case and IGMS Document</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABSLI IGMS Docuements</relationshipLabel>
    <relationshipName>ABSLI_IGMS_Docuements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <description>This field to store the IGMS Document ID in IGMS to CRM Complaint Inbound API</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/IRDA_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>IRDA_Token_Number__c</fullName>
    <description>This field to store the IRDA Token Number in IGMS to Salesforce Complaint Inbound API.</description>
    <label>IRDA Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code_Text__c.field-meta.xml
<CustomField>
    <fullName>Client_Code_Text__c</fullName>
    <label>Z Internal CCC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABSLI_UploadIGMSComplaints_Test.cls
@isTest
public class ABSLI_UploadIGMSComplaints_Test {
	@testSetup
    static void testSetup(){
        
        Id recordTypeId =Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId();
        Account objAccount = new Account();
        objAccount.FirstName = 'TestFirstName';
        objAccount.LastName  = 'TestFirstName';
        objAccount.RecordTypeId = recordTypeId;
        objAccount.Client_Code__c = 'ABSLI001';
        insert objAccount;
        
        Case testCase = new Case();
        testCase.CCC_External_Id__c = 'PNFT007';
        testCase.Business_Unit__c = 'ABSLI';
        testCase.Source__c = 'Email';
        testCase.Client_Code_Text__c = 'ABSLI001';
        testCase.AccountId = objAccount.Id;
        insert testCase;
        
        // Create a ContentVersion record
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Test File',
            PathOnClient = 'TestFile.txt',
            VersionData = Blob.valueOf('This is a test file.')
        );
        insert contentVersion;
        
        // Query the ContentDocument Id from the ContentVersion
        ContentVersion contentVersionQueried = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id = :contentVersion.Id 
            LIMIT 1
        ];
        
        // Create the ContentDocumentLink record
        ContentDocumentLink contentDocumentLink = new ContentDocumentLink(
            ContentDocumentId = contentVersionQueried.ContentDocumentId,
            LinkedEntityId = testCase.Id,
            ShareType = 'V' // Viewer access
        );
        insert contentDocumentLink;
        
        // Verify the ContentDocumentLink record was created
        ContentDocumentLink contentDocumentLinkQueried = [
            SELECT Id, ContentDocumentId, LinkedEntityId, ShareType 
            FROM ContentDocumentLink 
            WHERE Id = :contentDocumentLink.Id 
            LIMIT 1
        ];
        
        ABSLI_IGMS_Document__c doc = new ABSLI_IGMS_Document__c();
        doc.Case__c = testCase.Id;
        doc.IRDA_Token_Number__c = '2';
        doc.Document_Id__c = 'DOC-1234';
        insert doc;
    }
    @isTest
    static void testExecuteQuery() {
		Case caseobj = [Select Id From Case limit 1];
         // Create IGMSDocumentWrapper JSON string
        ABSLI_UploadIGMSComplaintsIntegration.IGMSUploadDocumentWrapper docWrapper = new ABSLI_UploadIGMSComplaintsIntegration.IGMSUploadDocumentWrapper();
        //docWrapper.contentDocumentId = contentDocument.ContentDocumentId;
        docWrapper.fileName = 'Test File.txt';
        String docWrapperJson = JSON.serialize(docWrapper);

        // Call the uploadAttachment method
        Test.startTest();
        List<ABSLI_UploadIGMSComplaintsIntegration.IGMSDocumentWrapper> result = ABSLI_UploadIGMSComplaintsIntegration.executeQuery(caseobj.Id,new List<String>());
        ABSLI_UploadIGMSComplaintsIntegration.ResponseWrapper response = ABSLI_UploadIGMSComplaintsIntegration.uploadAttachment(caseobj.Id, docWrapperJson);
        Test.stopTest();
        
    }

}