force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interaction.recordType-meta.xml
<RecordType>
    <fullName>Interaction</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Interaction</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/SLA_Threshold_Warning__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>When you change this setting , please note that existing Cases needs to be reedited for new changes to come in.</description>
    <label>SLA Threshold Warning</label>
</CustomObject>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Customer_Email_buffer_hours__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email_buffer_hours__c</fullName>
    <label>Customer Email buffer hours</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ABHFL_AssignAccountsToCaseBatch_Test.cls
@isTest
private class ABHFL_AssignAccountsToCaseBatch_Test {
    
     @testSetup
    static void setup() {
        SLA_Threshold_Warning__c slaTw = new SLA_Threshold_Warning__c ();
        slaTw.Customer_Email_buffer_hours__c = 30;
        slaTw.setupOwnerId = System.Userinfo.getOrganizationId();
        slaTw.Case_SLA_Threshold_1__c = 12;
        slaTw.Case_SLA_Threshold_2__c = 12;
        slaTw.Stage_SLA_Threshold_1__c = 12;
        slaTw.Case_SLA_Threshold_3__c = 12;
        Insert slaTw;
    
        RecordType rcdType = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Case' AND Name = 'Interaction' LIMIT 1];
    
        // Create test data
        Case testCase = new Case(
            RecordTypeId = rcdType.Id,
            Status = 'New',
            Technical_Source__c = 'Email',
            Business_Unit__c = 'ABHFL',
            SuppliedEmail = 'test@email.com',
            accountId = null
        );
        insert testCase;
        
        Account testAccount = new Account(
            //RecordTypeId = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Individual' LIMIT 1].Id,
          Name = 'Test Acc'
        );
        insert testAccount;
        
        Contact con = new contact();
        con.LastName = 'Test';
        con.accountId = testAccount.Id;
        con.email = 'test@email.com';
        INSERT Con;
    }

   public static testMethod void testschedule() {
        Test.StartTest();
            ABHFL_AssignAccountsToCaseBatchScheduler testsche = new ABHFL_AssignAccountsToCaseBatchScheduler();
            String sch = '0 0 23 * * ?';
            system.schedule('Test status Check', sch, testsche );
        Test.stopTest();
    }

    @isTest
    static void testBatchExecution() {
        
        // Start the batch job
        Test.startTest();
            ABHFL_AssignAccountsToCaseBatch batchJob = new ABHFL_AssignAccountsToCaseBatch();
            Database.executeBatch(batchJob);
        Test.stopTest();
    
    // Assert results
        account acc = [SELECT Id FROM account limit 1];
        
        List<Case> accountsAssigned = [SELECT Id FROM Case WHERE accountId = :acc.Id];
        System.assertEquals(1, accountsAssigned.size(), 'An account should be assigned to the case');
    }
}