force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not classified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/RM_Assignment__c.field-meta.xml
<CustomField>
    <fullName>RM_Assignment__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>RM Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/RM_Code__c.field-meta.xml
<CustomField>
    <fullName>RM_Code__c</fullName>
    <label>RM Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABFL_AccountTeamMemberBatch.cls
/*********************************************************
*Class        :  ABFL_AccountTeamMemberBatch
*Author       :  Shubham Sinha 
*Created Date :  16/01/2024
*Description  :  This batch class is used to insert AccountTeamMember if RM Code of LAN matches with user for ABFL Sales Role and delete the ATM if doesnt match.
*********************************************************/
public class ABFL_AccountTeamMemberBatch implements Database.Batchable<SObject>  {
    public final String query;
    public ABFL_AccountTeamMemberBatch() {
    this.query = 'SELECT Id, Name, AccountId, RM_Code__c, LOB__c ' +'FROM Asset '+'WHERE RM_Assignment__c = \'Pending\' AND Business_Unit__c = \'ABFL\'';}
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Asset> scope) {
        Map<String, Id> codeToFederationMap = new Map<String, Id>();
        Set<String> accountId = new Set<String>();
        List<AccountTeamMember> accountTeamMembersToInsert = new List<AccountTeamMember>();
        List<AccountTeamMember> accountTeamMembersToDelete = new List<AccountTeamMember>();
        List<Asset> updateRmAssignment = new List<Asset>();
        Map<Id,Set<String>> mapRmCodes = new  Map<Id,Set<String>>();
        for (Asset asset : scope) {
            if(asset.RM_Code__c != null && asset.AccountId != null){
                accountId.add(asset.accountId);
                asset.RM_Assignment__c = 'Processed';
                updateRmAssignment.add(asset);
            }
        }
            for (Asset assetAll : [SELECT ID, AccountId ,RM_Code__c  FROM Asset WHERE AccountId IN:accountId]) {
                codeToFederationMap.put(assetAll.RM_Code__c, null);  
                if (!mapRmCodes.containsKey(assetAll.AccountId)) {
                    mapRmCodes.put(assetAll.AccountId, new Set<String>());
                }
                mapRmCodes.get(assetAll.AccountId).add(assetAll.RM_Code__c);
                system.debug('rmCodes---> '+mapRmCodes);
            }
            // Query for users with matching LAN's RM Code
            for (User user : [SELECT Id, FederationIdentifier FROM User WHERE FederationIdentifier IN :codeToFederationMap.keySet() AND  UserRole.DeveloperName = 'ABFL_Sales']) {
                codeToFederationMap.put(user.FederationIdentifier, user.Id);
            }
            if(!codeToFederationMap.isEmpty()){
                // Iterate through fetched assets and create Account Team Members
                for (Asset asset : scope) {
                    Id userId = codeToFederationMap.get(asset.RM_Code__c);
                    if (userId != null) {
                    AccountTeamMember atm = new AccountTeamMember();
                    atm.AccountId = asset.AccountId;
                    atm.UserId = userId;
                    atm.TeamMemberRole = 'ABFL RM';
                    atm.AccountAccessLevel  = 'Read';
                    atm.CaseAccessLevel = 'Read';
                    accountTeamMembersToInsert.add(atm);
                    }
                }
            }
             if (!accountTeamMembersToInsert.isEmpty()) {
                insert accountTeamMembersToInsert;
            }
            if (!updateRmAssignment.isEmpty()) {
                update updateRmAssignment;
            }
        // Identifying Account Team Members to delete 
        for (AccountTeamMember existingAccountTeamMembers :[SELECT Id, UserId,User.FederationIdentifier, AccountId FROM AccountTeamMember WHERE AccountId IN :accountId]){
            if (mapRmCodes.containsKey(existingAccountTeamMembers.AccountId)) {
                if (!mapRmCodes.get(existingAccountTeamMembers.AccountId).contains(existingAccountTeamMembers.User.FederationIdentifier)) {
                    accountTeamMembersToDelete.add(existingAccountTeamMembers); 
                    system.debug('accountTeamMembersToDelete--> '+accountTeamMembersToDelete); 
                }
            }    
        }
        if (!accountTeamMembersToDelete.isEmpty()) {    
            delete accountTeamMembersToDelete;
        }
    }
    public void finish(Database.BatchableContext BC) {
    }
}