force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Framework.recordType-meta.xml
<RecordType>
    <fullName>Framework</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Framework</label>
</RecordType>

force-app/main/default/objects/Customer/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LAN_Mapping__c/LAN_Mapping__c.object-meta.xml
<CustomObject>
    <label>LAN Mapping</label>
    <nameField>
        <displayFormat>LAN-{0000000000}</displayFormat>
        <label>LAN Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAN Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAN_Mapping__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAN_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>External Id with Client_Code__c</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LAN Mappings</relationshipLabel>
    <relationshipName>LAN_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAN_Mapping__c/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loan Account Number (Asset) object</description>
    <label>Loan Account Number</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>LAN Mappings</relationshipLabel>
    <relationshipName>LAN_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ABFL_LegacyView.cls
/**
 * @description       : 
 * @author            : achuriwala@salesforce.com
 * @group             : 
 * @last modified on  : 04-23-2024
 * @last modified by  : achuriwala@salesforce.com
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   04-23-2024   achuriwala@salesforce.com   Initial Version
 * 2.0	 05-15-2024   achuriwala@salesforce.com   Changes according to the API details
**/
public with sharing class ABFL_LegacyView {
    /* @LOB - ABFL
    * @Function - getLANRelatedAccount
    * @param accRec - Account record from the framework.
    * @return - List<LAN_Mapping__c> 
    * @Description - This method will be used to get LANs related to Account
    *****************************************************************************************************************/
    @AuraEnabled(cacheable = true)
    public static List<OptionsName> getLANRelatedAccount(Id accRec){
        List<OptionsName> optionList = new List<OptionsName>();
        OptionsName option = null;
        for(LAN_Mapping__c lan : [select id,Customer__r.Business_Unit__c, LAN__r.Name, Customer__r.Client_Code__c FROM
                                  LAN_Mapping__c WHERE Customer__c = :accRec WITH SECURITY_ENFORCED]) {
            option = new OptionsName();
            option.label = lan.LAN__r.Name;
            option.value = lan.LAN__r.Name;
            optionList.add(option);
        }
        System.debug('@@lan'+optionList);
        return optionList;
    }
    /* @LOB - ABFL
    * @Function - getLegacyData
    * @param customerId
    * @param lanNumber
    * @param startDate
    * @param endDate
    * @param lob
    * @return  ResponseWrapper 
    * @description  This method will get legacy date and display in SF
    *****************************************************************************************************************/
    @AuraEnabled
    public static ResponseWrapper getLegacyData(String customerId, String lanNumber, String startDate, String endDate, String lob){
        try{
            ResponseWrapper response = null;
            LegacyCaseResponseBodyWrapper legacyCaseResponseWrapper;
            String integrationName = 'ABFL_Legacy_Case';
          	startDate = startDate != null?startDate:'';
            endDate = endDate != null?endDate:'';
            String conPayload =  JSON.serialize(new LegacyViewRequest(customerId, lanNumber, startDate, endDate, lob));
            ABCL_IntegrationCallout.IntegrationResponseWrapper legacyCaseResponse = ABCL_IntegrationCallout.executeCallout(integrationName,conPayload,null);
            if(legacyCaseResponse.statusCode == 200 && String.isNotBlank(legacyCaseResponse.responseBody)) {
                system.debug('legacyCaseResponse.responseBody'+legacyCaseResponse.responseBody);
                legacyCaseResponseWrapper = (LegacyCaseResponseBodyWrapper)JSON.deserialize(legacyCaseResponse.responseBody,LegacyCaseResponseBodyWrapper.class);
            	response = new ResponseWrapper(legacyCaseResponse.statusCode,legacyCaseResponseWrapper.lstDetails);     
                response.returnCode = legacyCaseResponseWrapper?.ReturnCode;
				response.returnMessage = legacyCaseResponseWrapper?.ReturnMessage;
            }
			//If status code is not 200, Sending reponse in string
            else if(String.isNotBlank(legacyCaseResponse.responseBody)) {
            	 response = new ResponseWrapper(legacyCaseResponse.statusCode,legacyCaseResponse.responseBody);
               	 response.returnCode = legacyCaseResponseWrapper?.ReturnCode;
				 response.returnMessage = legacyCaseResponseWrapper?.ReturnMessage;
            }
            //If no response
            else {
				response.returnMessage = Label.ASF_Error_Case_Merge ;
            }
            return response;
        }catch(exception e){
            System.debug('@@ER'+e.getMessage()+' '+e.getLineNumber());
            throw new AuraHandledException('Error : '+e.getMessage()+' '+e.getLineNumber());
        }
    }

    public class LegacyViewRequest{
        String CustomerNumber;
        String HoldingNumber;
        String FromDate;
        String ToDate;
        String LOB;
        LegacyViewRequest(String customerId, String holdingNumber, String fromDate, String toDate, String lob){
            this.CustomerNumber = customerId;
            this.HoldingNumber = holdingNumber;
            this.FromDate = fromDate;
            this.ToDate = toDate;
            this.LOB = lob;
        }
    }

    public Class ResponseWrapper{
        @AuraEnabled public Integer statusCode;
        @AuraEnabled public String returnCode;
        @AuraEnabled public String returnMessage;
        //Will be used only in case of failure
        @AuraEnabled public String response;
        @AuraEnabled public List<LegacyCaseResponseWrapper> legacyCaseResponse;
        public ResponseWrapper(Integer statusCode, List<LegacyCaseResponseWrapper> legacyCaseResponse){
            this.statusCode = statusCode;
            this.legacyCaseResponse = legacyCaseResponse;
        }
        public ResponseWrapper(Integer statusCode, String response){
            this.statusCode = statusCode;
            this.response = response;
        }
    }
    
    public class LegacyCaseResponseWrapper{
        @AuraEnabled public String Customer;
        @AuraEnabled public String CaseID;
        @AuraEnabled public String Category;
        @AuraEnabled public String CaseType;
        @AuraEnabled public String SubType;
        @AuraEnabled public String Source;
        @AuraEnabled public String LoanAccountNo;
        @AuraEnabled public String CreatedOn;
        @AuraEnabled public String CaseStatus;
        @AuraEnabled public String LastUpdatedOn;
        @AuraEnabled public String Owner;
    }
    public class LegacyCaseResponseBodyWrapper{
		public String ReturnCode;
		public String ReturnMessage;
        public List<LegacyCaseResponseWrapper> lstDetails;
        public LegacyCaseResponseWrapper details;
    }
    public class OptionsName {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
    }
}