force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_ButtonCardConfig__mdt/ASF_ButtonCardConfig__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is use for creating group of Buttons and define the dynamic LWC to be invoked based on it.</description>
    <label>ASF_ButtonCardConfig</label>
    <pluralLabel>ASF_ButtonCardConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ASF_ButtonCardConfig__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABSLI</fullName>
                <default>true</default>
                <label>ABSLI</label>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ASF_DynamicButtonsControllerTest.cls
@isTest
public class ASF_DynamicButtonsControllerTest {
    
    @isTest
    public static void getButtonsConfigTest(){
        Test.startTest();

            Id rtId = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId();
            
            Account acc= new Account(
                FirstName='Test FName',
                RecordTypeId = rtId,
                LastName='Test LName',
                PersonMailingStreet='test@yahoo.com',
                PersonMailingPostalCode='12345',
                PersonMailingCity='SFO',
                PersonEmail='test@yahoo.com',
                PersonHomePhone='1234567',
                PersonMobilePhone='91234567890',
                Business_Unit__c = 'ABSLI',
                Client_Code__c = 'CLIENTCODE01'
            );
            insert acc;  
        
        List<ASF_ButtonCardConfig__mdt> btnMetadatas = ASF_DynamicButtonsController.getButtonsConfig('Account',acc.Id);
        System.AssertEquals(btnMetadatas.size()>0,true);
        Test.stopTest();
    }
    
    
}