force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not Classified</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Digital</fullName>
                <isActive>false</isActive>
                <label>Digital</label>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
                <isActive>false</isActive>
                <label>Retail - Secured</label>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
                <isActive>false</isActive>
                <label>Retail - Unsecured</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/ASF_Case_SLA_History__c.object-meta.xml
<CustomObject>
    <label>Case SLA History</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case SLA Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/Breached_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Breached_User_Id__c</fullName>
    <label>Breached User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/BusinessHoursId__c.field-meta.xml
<CustomField>
    <fullName>BusinessHoursId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BusinessHoursId</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>SR_SLA_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case SLA Histories</relationshipLabel>
    <relationshipName>SR_SLA_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/is_Running_Record__c.field-meta.xml
<CustomField>
    <fullName>is_Running_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Running Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/Stage_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_End_Date__c</fullName>
    <label>Stage End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/Stage_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_Start_Date__c</fullName>
    <label>Stage Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LOB_Code__c.field-meta.xml
<CustomField>
    <fullName>LOB_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOB Code</label>
    <referenceTo>LOB_Master__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <description>This picklist field will contain the lob value to be used in sharing rules</description>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AIF</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>PMS</fullName>
            </value>
            <value>
                <fullName>RE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Target_1__c.field-meta.xml
<CustomField>
    <fullName>SLA_Target_1__c</fullName>
    <label>SLA Target 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Target_2__c.field-meta.xml
<CustomField>
    <fullName>SLA_Target_2__c</fullName>
    <label>SLA Target 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Target_3__c.field-meta.xml
<CustomField>
    <fullName>SLA_Target_3__c</fullName>
    <label>SLA Target 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_1__c</fullName>
    <label>Stage SLA 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_2__c</fullName>
    <label>Stage SLA 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_3__c</fullName>
    <label>Stage SLA 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LOB_Master__c/LOB_Master__c.object-meta.xml
<CustomObject>
    <description>Master Data Object to store LOB and related informations.</description>
    <label>LOB Master</label>
    <nameField>
        <displayFormat>LOB-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOB Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LOB_Master__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <description>Store Business Unit</description>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOB_Master__c/fields/LOB_Code__c.field-meta.xml
<CustomField>
    <fullName>LOB_Code__c</fullName>
    <externalId>true</externalId>
    <label>LOB Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/managerGroupId__c.field-meta.xml
<CustomField>
    <fullName>managerGroupId__c</fullName>
    <label>managerGroupId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ASF_TimeBasedSLAAlertHandler_Test.cls
@SuppressWarnings('PMD.MethodNamingConventions')
@isTest
public class ASF_TimeBasedSLAAlertHandler_Test {
    
    private final static Profile SYSTEMADMIN_PROFILE = [SELECT Id FROM Profile WHERE name='System Administrator' LIMIT 1];
    
    @testSetup
    static void setupTestData(){
        
        Group SLAGroup = new Group();
        
        SLAGroup = new Group(Name='SLAManagerGroup', DeveloperName='SLAManagerGroup');
        insert SLAGroup;
        
        group q = new group();
        q.name = 'OCC-Test-Group';
        q.type = 'Queue';
        insert q;
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Payment Base Profile'];
        PermissionSetGroup  ps = [SELECT Id, Status FROM PermissionSetGroup WHERE DeveloperName ='Super_Admin'];
        UserRole ur = [SELECT ID FROM UserRole WHERE DeveloperName='Payments_Service_Agent' LIMIT 1];
        if (ps.Status != 'Updated') {
            Test.calculatePermissionSetGroup(ps.Id);
        }
        
        list<user> userList = new list<User>();
        for(integer i=0;i<3;i++){
            User u = new User(Alias = 'standt', Email='standarduser'+i+'@testorg.com', 
                              EmailEncodingKey='UTF-8', LastName='TestUser5srDetail'+i, LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles',
                              UserName='standarduser@test5srDetail'+i+'.com'+System.now().millisecond(), UserRoleId = ur.Id);
            userList.add(u);
            
        }
        
        insert userList;
        List<PermissionSetAssignment> psAssign = new List<PermissionSetAssignment>();
        for(User u : userList){
            psAssign.add(new PermissionSetAssignment(AssigneeId = u.id, PermissionSetGroupId = ps.Id));
        }
        Insert psAssign;
        
        for(integer i=0;i<3;i++){
            GroupMember gm = new GroupMember(GroupId = SLAGroup.Id, UserOrGroupId = userList.get(i).Id);
            insert gm;
        }
        
        User userRecord1 = new User(Alias = 'standt', Email='stanrduserEmails@testorg.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', ProfileId = SYSTEMADMIN_PROFILE.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='cdefghijk56@gmail.com',
                                    managerGroupId__c=SLAGroup.Id);
        insert userRecord1;
        
        
        system.runAs(userRecord1){
            Account acc= new Account(
                FirstName='Test FName',
                LastName='Test LName',
                PersonMailingStreet='test@yahoo.com',
                PersonMailingPostalCode='12345',
                PersonMailingCity='SFO',
                PersonEmail='test@yahoo.com',
                PersonHomePhone='1234567',
                PersonMobilePhone='12345678',
                RecordTypeId = Schema.sObjectType.Account.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId(),
                Client_Code__c= 'abcd',
                Line_Of_Business__c = 'Payments',
                Business_Unit__c = 'Payments'
            );
            insert acc;  
            LOB_Master__c lob = new LOB_Master__c(LOB_Code__c = 'ABC', BusinessUnit__c = 'Wealth Management');
            insert lob;
            Asset ast = new Asset(Name='AccountFinacial',AccountId=acc.Id, LOB_Code__c = lob.Id,Price=100);
            insert ast;
            
            ASF_TestDataFactory.createCaseCategoryConfig(); 
        }
        
        
    }
    
    @isTest
    public static void SLATestCase(){
        
        Group g = [SELECT ID FROM Group WHERE DeveloperName='SLAManagerGroup'];
        
        User userRecord1 = new User(Alias = 'standt', Email='stanrduserEmails@testorg.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', ProfileId = SYSTEMADMIN_PROFILE.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='cdefghijk567@gmail.com',
                                    managerGroupId__c=g.Id);
        insert userRecord1;
        
        
        system.runAs(userRecord1){
            
            List<Case> caseList = ASF_TestDataFactory.createCaseRecords(1);
            Case c = CaseList.get(0);
            c.ownerid = userInfo.getuserId();
            DateTime cv = System.now();
            update c; 
            List<Id> cList = new List<Id>();
            cList.add(c.Id);
            ASF_CaseSLABroken.sendEmailSLABroke(cList);
            Test.startTest();
            
            System.schedule('TimeBasedSLAHandlerTest', '0 0 * * * ?', new ASF_TimeBasedSLAAlertHandler() ); 
            
            ASF_TimeBasedSLAAlertHandler uca = new ASF_TimeBasedSLAAlertHandler();
            Id batchId = Database.executeBatch(uca);
            c.Stage_SLA_1__c = cv.addHours(-3);
            c.Stage_SLA_2__c = cv.addHours(-2);
            c.Stage_SLA_3__c = cv.addHours(1);
            c.SLA_Target_3__c = 'stanrduserEmails@testorg.com';
            c.SLA_Target_1__c = 'stanrduserEmails@testorg.com';
            c.SLA_Target_2__c = 'stanrduserEmails@testorg.com';
            update c;
            batchId = Database.executeBatch(uca); 
            batchId = Database.executeBatch(uca);
            c.Stage_SLA_1__c = cv.addHours(-3);
            c.Stage_SLA_2__c = cv.addHours(-2);
            c.Stage_SLA_3__c = cv.addHours(-1);
            update c;  
            Test.stopTest();
            
            List<Case> caseLists = [SELECT Id,SLA_Target_2__c FROM Case];
            Assert.areEqual(caseLists[0].SLA_Target_2__c, 'stanrduserEmails@testorg.com');
        }
        
    }    
    
    
    @isTest
    public static void ManagerGroupSLA3Test(){
        Group g = [SELECT ID FROM Group WHERE DeveloperName='SLAManagerGroup'];
        
        User userRecord1 = new User(Alias = 'standt', Email='stanrduserEmails@testorg.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', ProfileId = SYSTEMADMIN_PROFILE.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='cdefghijk567@gmail.com',
                                    managerGroupId__c=g.Id);
        insert userRecord1;
        
        
        system.runAs(userRecord1){
            
            List<Case> caseList = ASF_TestDataFactory.createCaseRecords(1);
            Case c = CaseList.get(0);
            c.ownerid = userInfo.getuserId();
            DateTime cv = System.now();
            BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
            update c; 
            
            ASF_Case_SLA_History__c his = new ASF_Case_SLA_History__c();
            his.Case__c = c.Id;
            his.Stage_Start_Date__c = cv.addDays(-2);
            his.Stage_End_Date__c = null;
            his.BusinessHoursId__c = bh.Id;
            his.Breached_User_Id__c = c.OwnerId;
            his.Stage__c = 'New';
            his.is_Running_Record__c = true;
            insert his;
            
            List<Id> cList = new List<Id>();
            cList.add(c.Id);
            ASF_CaseSLABroken.sendEmailSLABroke(cList);
            Test.startTest();
            
            System.schedule('TimeBasedSLAHandlerTest', '0 0 * * * ?', new ASF_TimeBasedSLAAlertHandler() ); 
            
            ASF_TimeBasedSLAAlertHandler uca = new ASF_TimeBasedSLAAlertHandler();
            Id batchId = Database.executeBatch(uca);
            c.Stage_SLA_1__c = cv.addHours(-3);
            c.Stage_SLA_2__c = cv.addHours(-2);
            c.Stage_SLA_3__c = cv.addHours(1);
            c.SLA_Target_3__c = 'stanrduserEmails@testorg.com';
            c.SLA_Target_1__c = 'stanrduserEmails@testorg.com';
            c.SLA_Target_2__c = 'stanrduserEmails@testorg.com';
            update c;
            batchId = Database.executeBatch(uca); 
            batchId = Database.executeBatch(uca);
            c.Stage_SLA_1__c = cv.addHours(-3);
            c.Stage_SLA_2__c = cv.addHours(-2);
            c.Stage_SLA_3__c = cv.addHours(-1);
            update c;  
            Test.stopTest();
            
            List<Case> caseLists = [SELECT Id,SLA_Target_2__c FROM Case];
            Assert.areEqual(caseLists[0].SLA_Target_2__c, 'stanrduserEmails@testorg.com');
        }
    }
    
    @isTest
    public static void ManagerGroupSLA2Test(){
        Test.startTest();
        
        User u = [Select Id from User where LastName ='Testing' LIMIT 1];
        
        List<Case> caseList = ASF_TestDataFactory.createCaseRecords(1);
        Case c = CaseList.get(0);
        //c.status = 'Closed';
        c.ownerid = u.Id;
        DateTime cv = System.now();
        c.Stage_SLA_1__c = cv.addHours(-3);
        c.Stage_SLA_2__c = cv.addHours(2);
        c.Stage_SLA_3__c = cv.addHours(1);
        update c; 
        List<Id> cList = new List<Id>();
        cList.add(c.Id);
        
        ASF_TimeBasedSLAAlertHandler uca = new ASF_TimeBasedSLAAlertHandler();
        Id batchId = Database.executeBatch(uca);
        c.Stage_SLA_1__c = cv.addHours(-3);
        c.Stage_SLA_2__c = cv.addHours(-2);
        c.Stage_SLA_3__c = cv.addHours(1);
        
        batchId = Database.executeBatch(uca); 
        batchId = Database.executeBatch(uca);
        c.Stage_SLA_1__c = cv.addHours(-3);
        c.Stage_SLA_2__c = cv.addHours(-2);
        c.Stage_SLA_3__c = cv.addHours(3);
        
        Test.stopTest();
        
        List<Case> caseLists = [SELECT Id,Stage_SLA_3__c FROM Case];
        Assert.areEqual(caseLists[0].Stage_SLA_3__c, cv.addHours(1));
    }
}