force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ABHI</fullName>
            </value>
            <value>
                <fullName>ABSLAMC</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ABFL</fullName>
    </customValue>
    <customValue>
        <fullName>ABHFL</fullName>
    </customValue>
    <customValue>
        <fullName>Payments</fullName>
    </customValue>
    <customValue>
        <fullName>ABWM</fullName>
    </customValue>
    <customValue>
        <fullName>ABSLI</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ONEABC_CreateCaseWithTypeHelper.cls
public class ONEABC_CreateCaseWithTypeHelper {
    public static List<ASF_Case_Category_Config__c> filterCTSTBasedOnBULogic(List<ASF_Case_Category_Config__c> cccList,String inpArg){
        List<ASF_Case_Category_Config__c> returnVal = new List<ASF_Case_Category_Config__c>();
        String accountBu = '';
        String reqFrom = '';
        
        if(String.isNotBlank(inpArg)){
            Map<String,String> mInpArg = (Map<String,String>) JSON.deserialize(inpArg, Map<String,String>.Class);
            if(mInpArg.containsKey('accountLOB')){
                accountBu = mInpArg.get('accountLOB');
            }
            if(mInpArg.containsKey('requestFrom')){
                reqFrom = mInpArg.get('requestFrom');
            }
        }
        for(ASF_Case_Category_Config__c cccRec : cccList){ 
            //RETURN CCC THAT MATCHES WITH ACCOUNT'S BU
            if(String.isNotBlank(accountBu)){
                if(cccRec.Business_Unit__c.equalsIgnoreCase(accountBu)){
                returnVal.add(cccRec);
                }
                else if(accountBu != ASF_Constants.ABCD_BU &&
                        cccRec.Business_Unit__c.equalsIgnoreCase(ASF_Constants.ONEABC_BU)){
                    returnVal.add(cccRec);
                }
            } else if(String.isNotBlank(reqFrom)){
                if(reqFrom == 'Lead' && (cccRec.Business_Unit__c.equalsIgnoreCase(ASF_Constants.ONEABC_BU) || 
                                         cccRec.Business_Unit__c.equalsIgnoreCase(ASF_Constants.ABCD_BU))){
                    returnVal.add(cccRec);
                }
            }
        }
        
        
        return returnVal;
        
    }
}