force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code_Text__c.field-meta.xml
<CustomField>
    <fullName>Client_Code_Text__c</fullName>
    <label>Z Internal CCC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ASF_AssocCustomerForAPICases.cls
public without sharing class ASF_AssocCustomerForAPICases {
    public static final List<String> LINE_OF_BUSINESS = new List<String>{'Payments','ABHFL','ABFL'};

    public static void searchAndAssocCustomerForAPICases(List<Case> newList){
        Set<String> accountsClientCode = new Set<String>();
        Map<String,Id> accClientCodeVsAccIds = new Map<String,Id>();
        Set<String> caseLANNo = new Set<String>();
        Map<String,Asset> lanNoVsAsset = new Map<String,Asset>();
        
        for(Case individualCase : newList){
            if(individualCase.Technical_Source__c == 'API' || individualCase.Technical_Source__c == 'Email'){
                if(individualCase.Client_Code_Text__c != null){
                    accountsClientCode.add(individualCase.Client_Code_Text__c); 
                }
                if(individualCase.LAN__c  != null){
                    caseLANNo.add(individualCase.LAN__c); 
                }
            }
        }
        if(accountsClientCode.size()>0){
            for(Account acc : [SELECT ID,Client_Code__c FROM Account WHERE Client_Code__c =: accountsClientCode AND Business_Unit__c =: LINE_OF_BUSINESS]){
                if(!accClientCodeVsAccIds.containsKey(acc.Client_Code__c)){
                    accClientCodeVsAccIds.put(acc.Client_Code__c,acc.Id);
                }
            } 
        }
        if(caseLANNo.size()>0){
            for(Asset ast : [SELECT ID,LAN__c,AccountId  FROM Asset WHERE LAN__c =: caseLANNo AND Business_Unit__c =: LINE_OF_BUSINESS]){
                if(!lanNoVsAsset.containsKey(ast.LAN__c)){
                    lanNoVsAsset.put(ast.LAN__c,ast);
                }
            } 
        }   
        for(Case individualCase : newList){
            if(individualCase.Technical_Source__c == 'API' || individualCase.Technical_Source__c == 'Email'){
                if(individualCase.Client_Code_Text__c != null){
                    if(accClientCodeVsAccIds.containsKey(individualCase.Client_Code_Text__c)){
                        individualCase.AccountId = accClientCodeVsAccIds.get(individualCase.Client_Code_Text__c);
                    }
                }
                if(individualCase.LAN__c != null){
                    if(lanNoVsAsset.containsKey(individualCase.LAN__c)){
                        individualCase.AssetId = lanNoVsAsset.get(individualCase.LAN__c).Id;
                        // in case account id is blank
                        individualCase.AccountId = individualCase.AccountId==null?lanNoVsAsset.get(individualCase.LAN__c).AccountId:individualCase.AccountId;
                    }
                }
            }
        }
        
    }
    
}