force-app/main/default/objects/Account/fields/Chronic_Disease__c.field-meta.xml
<CustomField>
    <fullName>Chronic_Disease__c</fullName>
    <label>Chronic Disease</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PED__c.field-meta.xml
<CustomField>
    <fullName>PED__c</fullName>
    <label>Pre Existing Disease</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ABHI_Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>ABHI_Policy_Id__c</fullName>
    <description>Used to store policy id</description>
    <externalId>true</externalId>
    <label>Policy Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <externalId>true</externalId>
    <label>Policy Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RNWL_EmailMessageTriggerHandlerTest.cls
@isTest public class RNWL_EmailMessageTriggerHandlerTest { 
    
    @isTest static void testValidateEmailCount() {
        
        Account acc=  new Account(name='Test Account' , Client_Code__c = 'PT87552250' , Chronic_Disease__c = 'test', PED__c = 'test');
        insert acc;
        
        Asset objAsset =  new Asset(name='21-24-0000759-02', ABHI_Policy_Id__c='21-24-0000759-02', LAN__c = '21-24-0000759-02');
        insert objAsset;
        
        Opportunity oppRec = new Opportunity();
        oppRec.Name = 'Testabc' ;
        oppRec.Policy__c = objAsset.Id;
        oppRec.AccountId = acc.Id;
        oppRec.CloseDate = Date.today();
        oppRec.StageName = 'In Progress';
        oppRec.Policy_Number__c = '21-24-0000759-02';
        insert oppRec;
          
        List<EmailMessage> emailMessages = new List<EmailMessage>(); 
        for (Integer i = 0; i < 5; i++) { 
            EmailMessage msg = new EmailMessage( RelatedToId = oppRec.Id, Status = '3',Subject = 'Test Email ' + i ); 
            emailMessages.add(msg);
        } 
        insert emailMessages;  
        
        
        Test.startTest(); 
        
        try { 
            EmailMessage msg = new EmailMessage( RelatedToId = oppRec.Id, Status = '3',Subject = 'Test Email ' ); 
            insert msg;  
            System.assert(false, 'Expected a validation error, but did not receive one.'); 
        } catch (DmlException e)
        { 
            System.assert(e.getMessage().contains('You have exceeded the daily limit for sending this notification') || e.getMessage().contains('You have exceeded the overall limit for sending this notification'), 'Unexpected error message: ' + e.getMessage());
        } 
        Test.stopTest(); 
    }
}