force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <description>This object is used to track the Survey responses for Case, LAN, and Account.</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Common Client Code. Value to come from API.</description>
    <label>Client Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Primary_Question_NPS__c.field-meta.xml
<CustomField>
    <fullName>Primary_Question_NPS__c</fullName>
    <description>Survey NPS indicator in numbers, 0-10. Value to come from API.</description>
    <label>Primary Question: NPS</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/managerGroupId__c.field-meta.xml
<CustomField>
    <fullName>managerGroupId__c</fullName>
    <label>managerGroupId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Asf_NpsIndicatiorController_Test.cls
/****************************************************************************************************************
  * 
  * Date         - 27-March-2024
  * @LOB         - All
  * @description -  Test class for Asf_NpsIndicatiorController class.
*****************************************************************************************************************/

@isTest
public  class Asf_NpsIndicatiorController_Test {
private final static Profile SYSTEMADMIN_PROFILE = [SELECT Id FROM Profile WHERE name='System Administrator' LIMIT 1];
    @testSetup
    static void setUpData(){
      Group SLAGroup = new Group();        
        SLAGroup = new Group(Name='SLAManagerGroup', DeveloperName='SLAManagerGroup');
          insert SLAGroup;
        Group g1 = new Group(Name='OCC-Test-Group', type='Queue');
          insert g1;
        User userRecord = new User(Alias = 'standt', Email='stanrduserEmails@testorg.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', ProfileId = SYSTEMADMIN_PROFILE.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='cdefghijk5657123456@gmail.com',
                                    managerGroupId__c=SLAGroup.Id);
        insert userRecord;
        System.runAs(userRecord) {
         Id rtId = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId();
         Account acc= new Account(
            FirstName='Test FName',
            RecordTypeId = rtId,
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678'
        );
            insert acc;  
           Account acc1= new Account(
            FirstName='Test1 FName',
            RecordTypeId = rtId,
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678'
        );
            insert acc1;
          Survey_Response__c surveyResp = new Survey_Response__c();
            surveyResp.Primary_Question_NPS__c = 7;
            surveyResp.Client_Code__c = acc.Id;
          insert surveyResp;
        }
    }
    /****************************************************
       * @description - Test Method for evaluate Method
    *****************************************************/
    
    @isTest 
    static void genericFetchQuery_TestMethod() {
        List<Account> objAcc = [Select Id,FirstName From Account WHERE FirstName = 'Test1 FName' LIMIT 1]; 
        Asf_NpsIndicatiorController.getCaseCounts(objAcc[0].Id);
        System.assertEquals(objAcc.size(), 1,'record found');
    }
      @isTest
    static void getNpsScoreTest(){
        List<Account> objAcc = [Select Id,FirstName From Account WHERE FirstName = 'Test FName' LIMIT 1];
        User usr = [SELECT Id FROM User WHERE Username = 'cdefghijk5657123456@gmail.com' LIMIT 1];
        Survey_Response__c resp = [SELECT Id,Client_Code__c,Primary_Question_NPS__c FROM Survey_Response__c WHERE Client_Code__c =: objAcc[0].Id LIMIT 1];
     system.runAs(usr)
        { 
            Test.startTest(); 
            Asf_NpsIndicatiorController.getNpsScore(objAcc[0].Id);
            System.assertEquals(7, resp.Primary_Question_NPS__c,'record found');          
             Test.stopTest();            
            }
        }
       @isTest
    static void getNpsScoreTestNeg(){
        List<Account> objAcc = [Select Id,FirstName From Account WHERE FirstName = 'Test1 FName' LIMIT 1];
        User usr = [SELECT Id FROM User WHERE Username = 'cdefghijk5657123456@gmail.com' LIMIT 1];
        List<Survey_Response__c> resp = [SELECT Id,Client_Code__c,Primary_Question_NPS__c FROM Survey_Response__c WHERE Client_Code__c =: objAcc[0].Id LIMIT 1];
     system.runAs(usr)
        { 
            Test.startTest(); 
            Asf_NpsIndicatiorController.getNpsScore(objAcc[0].Id);
           System.assertEquals(0, resp.size(),'No record found');          
             Test.stopTest();            
            }
        }
}