force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Since__c.field-meta.xml
<CustomField>
    <fullName>Customer_Since__c</fullName>
    <label>Customer Since</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Health Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Wealth</fullName>
            </value>
            <value>
                <fullName>Not Classified</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Digital</fullName>
                <isActive>false</isActive>
                <label>Digital</label>
            </value>
            <value>
                <fullName>Retail - Secured</fullName>
                <isActive>false</isActive>
                <label>Retail - Secured</label>
            </value>
            <value>
                <fullName>Retail - Unsecured</fullName>
                <isActive>false</isActive>
                <label>Retail - Unsecured</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Since__c.field-meta.xml
<CustomField>
    <fullName>Customer_Since__c</fullName>
    <description>The date-time when the B2C customer is created in Payment System.</description>
    <label>Customer Since</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>LPAD(RIGHT( MobilePhone , 4), LEN(MobilePhone), &apos;X&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/PAY_Staging_Customer_to_Account__e.object-meta.xml
<CustomObject>
    <description>This platform event is for moving Paymets Line of Business Staging Customer record to Account.</description>
    <label>PAY Staging Customer to Account</label>
    <pluralLabel>PAY Stagin Customer to Acount</pluralLabel>
</CustomObject>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/ABC_Cust_Id__c.field-meta.xml
<CustomField>
    <fullName>ABC_Cust_Id__c</fullName>
    <label>ABC Cust Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Customer_Since__c.field-meta.xml
<CustomField>
    <fullName>Customer_Since__c</fullName>
    <label>Customer Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Will be mapped to Accounts record type</description>
    <label>Customer Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <description>To be mapped with Line of Business on Account</description>
    <label>Line of Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Merchant_Contact_Payload__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Contact_Payload__c</fullName>
    <label>Merchant Contact Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Id__c</fullName>
    <label>Merchant Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Merchant_Name__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Name__c</fullName>
    <label>Merchant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAY_Staging_Customer_to_Account__e/fields/STG_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>STG_Customer_Id__c</fullName>
    <description>Unique Identified on Staging Record.</description>
    <label>STG Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STG_Customer__c/STG_Customer__c.object-meta.xml
<CustomObject>
    <label>Staging Customer</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>STG Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/STG_Customer__c/fields/ABC_Cust_Id__c.field-meta.xml
<CustomField>
    <fullName>ABC_Cust_Id__c</fullName>
    <label>ABC Cust Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STG_Customer__c/fields/Customer_Since__c.field-meta.xml
<CustomField>
    <fullName>Customer_Since__c</fullName>
    <label>Customer Since</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/STG_Customer__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Non-Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/STG_Customer__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABCD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/STG_Customer__c/fields/Merchant_Contact_Payload__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Contact_Payload__c</fullName>
    <label>Merchant Contact Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/STG_Customer__c/fields/Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Id__c</fullName>
    <label>Merchant Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STG_Customer__c/fields/Merchant_Name__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Name__c</fullName>
    <label>Merchant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PAY_CustomerCreationListenerTest.cls
@isTest
private class PAY_CustomerCreationListenerTest {

    @isTest
    static void testProcessEvents() {
        PAY_Staging_Customer_to_Account__e event = new PAY_Staging_Customer_to_Account__e();
        event.Merchant_Id__c = 'TestMerchantId';
        event.Merchant_Name__c = 'TestMerchantName';
        event.Line_of_Business__c = 'TestLOB';
        event.Customer_Type__c = 'Individual';
        event.Mobile__c = '1234567890';
        event.Email__c = 'test@example.com';
        event.First_Name__c = 'TestFirstName';
        event.Last_Name__c = 'TestLastName';
        event.Merchant_Contact_Payload__c = '[{"FirstName":"TestContactFirstName","LastName":"TestContactLastName","MobilePhone":"9876543210","Email":"contact@example.com","lineOfBusiness":"TestLOB"}]';

        List<PAY_Staging_Customer_to_Account__e> testEvents = new List<PAY_Staging_Customer_to_Account__e>();
        testEvents.add(event);

        Account existingAccount = new Account(Name = 'ExistingAccount', Client_Code__c = 'TestMerchantId');
        insert existingAccount;

        Contact existingContact = new Contact(
            FirstName = 'ExistingContactFirstName',
            LastName = 'ExistingContactLastName',
            MobilePhone = '9876543210',
            Email = 'existing@example.com',
            AccountId = existingAccount.Id,
            Line_of_Business__c = 'TestLOB'
        );
        insert existingContact;

     

        Test.startTest();
        Database.SaveResult[] results = EventBus.publish(testEvents);
        Test.getEventBus().deliver();
        Test.stopTest();
		Assert.areEqual(true, results[0].isSuccess());

    }
    @isTest
    static void testProcessEventsIndividual() {
        PAY_Staging_Customer_to_Account__e event = new PAY_Staging_Customer_to_Account__e();
        event.ABC_Cust_Id__c = '134223';
        event.Mobile__c = '1111111111';
        event.Last_Name__c ='TestingLNm';
        event.Email__c = 'invalid@invalid.test.com.net';
        event.Customer_Since__c = System.today();
        event.Line_of_Business__c = 'Payments';
        event.Customer_Type__c ='Individual';
        
        STG_Customer__c stgCustomer = new STG_Customer__c();
        insert stgCustomer;
        
		event.STG_Customer_Id__c = stgCustomer.Id;
        List<PAY_Staging_Customer_to_Account__e> testEvents = new List<PAY_Staging_Customer_to_Account__e>();
        testEvents.add(event);


        Test.startTest();
        Database.SaveResult[] results = EventBus.publish(testEvents);
        Test.getEventBus().deliver();
        Test.stopTest();
	
        Assert.areEqual(true, results[0].isSuccess());
    }
    
    @isTest
    static void testProcessEventsNonIndividual() {
        PAY_Staging_Customer_to_Account__e event = new PAY_Staging_Customer_to_Account__e();
        event.ABC_Cust_Id__c = '134223';
        event.Mobile__c = '1111111110';
        event.Last_Name__c ='TestingLNmn';
        event.Email__c = 'invalidity@invalid.test.com.net';
        event.Customer_Since__c = System.today();
        event.Line_of_Business__c = 'Payments';
        event.Customer_Type__c ='Non-Individual';
		/*List<STG_Customer__c> customerStaging = [SELECT Id from STG_Customer__c];
        event.STG_Customer_Id__c = customerStaging[0].Id;*/
        
        List<PAY_Staging_Customer_to_Account__e> testEvents = new List<PAY_Staging_Customer_to_Account__e>();
        testEvents.add(event);


        Test.startTest();
        Database.SaveResult[] results = EventBus.publish(testEvents);
        Test.getEventBus().deliver();
        Test.stopTest();

		Assert.areEqual(true, results[0].isSuccess());
    }
}