force-app/main/default/objects/ASF_Case_Approv__c/ASF_Case_Approv__c.object-meta.xml
<CustomObject>
    <label>Case Request</label>
    <nameField>
        <label>Case Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parallel - All to approve</fullName>
                <default>true</default>
                <label>Parallel - All to approve</label>
            </value>
            <value>
                <fullName>Parallel - First to approve</fullName>
            </value>
            <value>
                <fullName>Sequential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approver_01__c.field-meta.xml
<CustomField>
    <fullName>Approver_01__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 01</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SR_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approver_02__c.field-meta.xml
<CustomField>
    <fullName>Approver_02__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 02</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SR_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approver_03__c.field-meta.xml
<CustomField>
    <fullName>Approver_03__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 03</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SR_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approver_04__c.field-meta.xml
<CustomField>
    <fullName>Approver_04__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 04</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SR_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Approver_05__c.field-meta.xml
<CustomField>
    <fullName>Approver_05__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 05</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SR_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Case_RejectedStageMovement__c.field-meta.xml
<CustomField>
    <fullName>Case_RejectedStageMovement__c</fullName>
    <label>Case Rejected Stage Movement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Is_Recategorization_Request__c.field-meta.xml
<CustomField>
    <fullName>Is_Recategorization_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Recategorization Request?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Parent_Record_Id_For_Update__c.field-meta.xml
<CustomField>
    <fullName>Parent_Record_Id_For_Update__c</fullName>
    <label>Parent Record Id For Update</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/RejectedFieldUpdates__c.field-meta.xml
<CustomField>
    <fullName>RejectedFieldUpdates__c</fullName>
    <label>RejectedFieldUpdates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Requested_CCC_Details__c.field-meta.xml
<CustomField>
    <fullName>Requested_CCC_Details__c</fullName>
    <label>Requested CCC Details</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/Requestor_Comments__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Comments__c</fullName>
    <label>Requestor Comments</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/SR__c.field-meta.xml
<CustomField>
    <fullName>SR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SR Requests</relationshipLabel>
    <relationshipName>SR_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/SuccessFieldsUpdate__c.field-meta.xml
<CustomField>
    <fullName>SuccessFieldsUpdate__c</fullName>
    <label>SuccessFieldsUpdate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Approv__c/fields/SuccessStageMovement__c.field-meta.xml
<CustomField>
    <fullName>SuccessStageMovement__c</fullName>
    <label>Case Success Stage Movement</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Approval_Pending__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval Pending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval_Stage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval Stage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_CCC_Details__c.field-meta.xml
<CustomField>
    <fullName>Requested_CCC_Details__c</fullName>
    <label>Requested CCC Details</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_Recat_Json__c.field-meta.xml
<CustomField>
    <fullName>Requested_Recat_Json__c</fullName>
    <label>Requested Recat Json</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Text__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Type_Text__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/classes/ASF_CaseApprovalTriggerHelper.cls
public without sharing class ASF_CaseApprovalTriggerHelper {
    
    /*
* 1. pending : Move next Stage
*/ 
    
    public void handleSubmitForApproval (List<ASF_Case_Approv__c> newStageList){ 
        List<ASF_Case_Approv__c> submitForApprovalList = new List<ASF_Case_Approv__c>();
        List<Approval.ProcessSubmitRequest> requestLIst = new List<Approval.ProcessSubmitRequest>();
        //Virendra : 6th March 2023 : Added map of CaseApprovalId to Case Id.
        Map<Id,Id> mCaseApprovToCaseId = new Map<Id,Id>();
        
        for(ASF_Case_Approv__c v:newStageList){
            //if (v.TypeOfApproval__c == 'Auto'){
            submitForApprovalList.add(v);
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();          
            req.setComments(v.Requestor_Comments__c);        
            req.setObjectId(v.id);
            requestLIst.add(req);
            
            if(!mCaseApprovToCaseId.containsKey(v.Id)){
                mCaseApprovToCaseId.put(v.Id,v.SR__c);
            }
            
            
            // }
        }
        if(submitForApprovalList.size() > 0){
            List<Approval.ProcessResult> resultList = new List<Approval.ProcessResult>();
            try{
                resultList = Approval.process(requestLIst);   
            }
            catch(DmlException dEx){
                for(integer i=0;i<dEx.getNumDml();i++){
                    System.debug(dEx.getDmlType (i));
                    if(dEx.getDmlType(i).toString() == 'STRING_TOO_LONG'){
                        for(ASF_Case_Approv__c trg : submitForApprovalList){
                            trg.addError('String too large to save.');
                        }
                    }
                    
                }
            }
            //Virendra : 6th March 2023 : Added code below to update the Is_Approval_Pending__c to True on Case record.
            List<Case> cList = new List<Case>();
            
            for(Approval.ProcessResult res : resultList){
                if(res.isSuccess()){
                    if(res.getEntityId() != null){
                        if(mCaseApprovToCaseId.containsKey(res.getEntityId())){
                            Id cId = mCaseApprovToCaseId.get(res.getEntityId());
                            Case c = new Case(Id = cId);
                            c.Is_Approval_Pending__c = true;
                            if(!cList.contains(c)){
                                cList.add(c);
                            }
                            
                        }
                    }
                }
            }
            if(cList.size()>0){
                ASF_TriggerSkipperUtility.markTriggerRun('Case');
                Database.SaveResult[] saveResults = Database.update(cList,false);                
            }
            
        }
    }
    
    public void prepopupateUnpassedUserNames (List<ASF_Case_Approv__c> newStageList){ 
        
        for(ASF_Case_Approv__c  c: newStageList){
            if(c.Approval_Type__c != 'Sequential'){
                if(String.isBlank(c.Approver_02__c)){
                    c.Approver_02__c = c.Approver_01__c;
                }
                if(String.isBlank(c.Approver_03__c)){
                    c.Approver_03__c = c.Approver_01__c;
                }
                if(String.isBlank(c.Approver_04__c)){
                    c.Approver_04__c = c.Approver_01__c;
                }
                if(String.isBlank(c.Approver_05__c)){
                    c.Approver_05__c = c.Approver_01__c;
                }
            }
        } 
    }
    
    public void handleApprovalActions(Map<Id,ASF_Case_Approv__c> oldApproveMap,Map<Id,ASF_Case_Approv__c> newApproveMap){ 
        checkIfApprovalProcessCommentPresent(oldApproveMap,newApproveMap);//Virendra - 8 Feb 2023.
        Set<Id> caseIds = new Set<Id>();
        Set<Id> rejectedCaseIds = new Set<Id>();
        List<Case> rejectedCaseToUpdate = new List<Case>();
        for(ASF_Case_Approv__c  c: newApproveMap.values()){
            ASF_case_Approv__c newRecord = c;
            ASF_case_Approv__c oldRecord = oldApproveMap.get(c.id);
            if(oldrecord.Approval_Status__c != newRecord.Approval_Status__c ){
                /* Aware of for loop Update. This is by design. 
*/ 
                
                if (c.Approval_Status__c == 'Approved'){
                    if(newRecord.Is_Recategorization_Request__c){
                        caseIds.add(newRecord.SR__c);
                    }else{
                        if(String.isNotBlank(newRecord.Parent_Record_Id_For_Update__c)){
                            Id recId = Id.valueOf(newRecord.Parent_Record_Id_For_Update__c);
                            Schema.SObjectType token = recId.getSObjectType();
                            Sobject s = token.newSobject();
                            s.put('Id',newRecord.Parent_Record_Id_For_Update__c );
                            //now decyper Fields and Make it happen
                            List<String> FieldvaluesList = c.SuccessFieldsUpdate__c.split(',');
                            for(String som : FieldvaluesList){
                                String fieldAPIName = som.split('=')[0];
                                String fieldValue = som.split('=')[1];
                                s.put(fieldAPIName,fieldValue);
                            }
                            ASF_TriggerSkipperUtility.markTriggerRun('Case');
                            update s;
                        } 
                        
                        Case cas = new Case(Id =newRecord.SR__c);
                        
                        ASF_TriggerSkipperUtility.markTriggerRun('Case');
                        update cas;
                	}
                    
                }
                else if(c.Approval_Status__c == 'Rejected'){
                    if(String.isNotBlank(newRecord.Parent_Record_Id_For_Update__c)){
                        Id recId = Id.valueOf(newRecord.Parent_Record_Id_For_Update__c);
                        Schema.SObjectType token = recId.getSObjectType();
                        Sobject s = token.newSobject();
                        s.put('Id',newRecord.Parent_Record_Id_For_Update__c );
                        //now decyper Fields and Make it happen
                        List<String> FieldvaluesList = c.RejectedFieldUpdates__c.split(',');
                        for(String som : FieldvaluesList){
                            String fieldAPIName = som.split('=')[0];
                            String fieldValue = som.split('=')[1];
                            s.put(fieldAPIName,fieldValue);
                        }
                        //object name need not be case. it should be ideally be Case Extension1 or 2. But safer side.
                        ASF_TriggerSkipperUtility.markTriggerRun('Case');
                        update s;
                    }
                    /* bel0w record is to update case. */
                    Case cas = new Case(Id =newRecord.SR__c);
                    //Virendra : Commenting below code : 8th March 2023: On Rejetion, no case change is happening, hence no need to change Is_Approval_Stage__c.
                    //cas.Is_Approval_Stage__c = false;
                    ASF_TriggerSkipperUtility.markTriggerRun('Case');
                    update cas;   
                }
                if(c.Is_Recategorization_Request__c && (c.Approval_Status__c == 'Rejected' || c.Approval_Status__c == 'Recalled' || c.Approval_Status__c == 'Cancelled')){
                    rejectedCaseIds.add(newRecord.SR__c);
                }
            }
        }  
        if(!caseIds.isEmpty()){
            Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, CCC_External_Id__c, Requested_Recat_Json__c, Type_Text__c, Sub_Type_Text__c from Case where ID IN: caseIds]);
            ASF_ApprovalRecatController.updateCCCIdBulk(caseMap);
        } 
        else if(!rejectedCaseIds.isEmpty()){
            Map<Id, Case> caseMap = new Map<Id, Case>();
            for(Case caseRec : [SELECT Id, Requested_CCC_Details__c, Requested_Recat_Json__c from Case where ID IN: rejectedCaseIds]){
                caseRec.Requested_CCC_Details__c = '';
                caseRec.Requested_Recat_Json__c = '';
                rejectedCaseToUpdate.add(caseRec);
            }
            ASF_TriggerSkipperUtility.markTriggerRun('Case');
            update rejectedCaseToUpdate;
        }
    }
    
    
    public void moveToSuccessStage(Map<Id,ASF_Case_Approv__c> newApproveMap,Map<Id,ASF_Case_Approv__c> oldApproveMap){  
        list<case> casesToUpdate = new list<Case>();
        Set<id> IsApprovalPendingToUpdate = checkIfLatestRecordIsApproved(newApproveMap,oldApproveMap);
        for(ASF_Case_Approv__c  c: newApproveMap.values()){
            if(newApproveMap.get(c.Id).Approval_Status__c != oldApproveMap.get(c.Id).Approval_Status__c && newApproveMap.get(c.Id).Approval_Status__c=='Approved'){
                case caseRecord = new Case();
                caseRecord.Id = c.SR__c;

                if(c.SuccessStageMovement__c != null){
                    caseRecord.Stage__c = c.SuccessStageMovement__c;
                }
                //Virendra : 6 March 2023 : Added to update Is Approval Pending flag to False, if approval is Approved, Rejected, or Recalled.
                if(IsApprovalPendingToUpdate.contains(c.SR__c)){
                    caseRecord.Is_Approval_Pending__c = false;
                }
                
                casesToUpdate.add(caseRecord);
            }
            if(newApproveMap.get(c.Id).Approval_Status__c != oldApproveMap.get(c.Id).Approval_Status__c && newApproveMap.get(c.Id).Approval_Status__c=='Rejected'){
                case caseRecord = new Case();
                caseRecord.Id = c.SR__c;

                if(c.Case_RejectedStageMovement__c != null){
                    caseRecord.Stage__c = c.Case_RejectedStageMovement__c;
                }

                if(IsApprovalPendingToUpdate.contains(c.SR__c)){
                    caseRecord.Is_Approval_Pending__c = false;
                }
                
                casesToUpdate.add(caseRecord);
            }
            if(newApproveMap.get(c.Id).Approval_Status__c != oldApproveMap.get(c.Id).Approval_Status__c && newApproveMap.get(c.Id).Approval_Status__c=='Recalled'){
                case caseRecord = new Case();
                caseRecord.Id = c.SR__c;
                if(IsApprovalPendingToUpdate.contains(c.SR__c)){
                    caseRecord.Is_Approval_Pending__c = false;
                    casesToUpdate.add(caseRecord);
                }
                
                
            }
        } 
        
        if(casesToUpdate.size() > 0){
            ASF_TriggerSkipperUtility.markTriggerRun('Case');
            update casesToUpdate;
        }
    } 
    
    
    
    private void checkIfApprovalProcessCommentPresent(Map<Id,ASF_Case_Approv__c> oldApproveMap,Map<Id,ASF_Case_Approv__c> newApproveMap){
        Set<Id> caseApprId = new Set<Id>();
        for(ASF_Case_Approv__c ca : newApproveMap.values()){
            System.debug(ca.Approval_Status__c + ' - '+oldApproveMap.get(ca.Id).Approval_Status__c);
            if(ca.Approval_Status__c == 'Rejected' && (ca.Approval_Status__c != oldApproveMap.get(ca.Id).Approval_Status__c)){
                caseApprId.add(ca.Id);
            }
        }
        
        for(ProcessInstance pi : [SELECT TargetObjectId,(SELECT ID,StepStatus, Comments FROM Steps Order By CreatedDate DESC LIMIT 1) FROM ProcessInstance
                                  WHERE TargetObjectId =: caseApprId ORDER BY CreatedDate DESC])
        {
            if((pi.Steps[0].comments == null || pi.Steps[0].Comments.trim().length()==0)){
                //newApproveMap.get(pi.TargetObjectId).addError('Operation Cancelled : Please provide a rejection reason !');
            }
        }
    }
    private static Set<id> checkIfLatestRecordIsApproved(Map<Id,ASF_Case_Approv__c> newApproveMap,Map<Id,ASF_Case_Approv__c> oldApproveMap){
        Map<Id,ASF_Case_Approv__c> mLatestRecord = new Map<Id,ASF_Case_Approv__c>();
        Set<Id> caseIsApprovalPendingFlagTobeUpdated = new Set<Id>();
        
        List<String> validStatus = new List<String>{'Approved','Rejected','Recalled'};
            
            for(ASF_Case_Approv__c ca : [SELECT ID,SR__c,Approval_Status__c FROM ASF_Case_Approv__c WHERE Id =: newApproveMap.keySet() ORDER BY CreatedDate DESC]){
                if(!mLatestRecord.containsKey(ca.Id)){
                    mLatestRecord.put(ca.Id,ca);
                }
            }
        for(ASF_Case_Approv__c ca : mLatestRecord.values()){
            if(ca.Approval_Status__c != oldApproveMap.get(ca.Id).Approval_Status__c){
                if(validStatus.contains(ca.Approval_Status__c)){
                    if(!caseIsApprovalPendingFlagTobeUpdated.contains(ca.SR__c)){
                        caseIsApprovalPendingFlagTobeUpdated.add(ca.SR__c);
                    }
                }
            }
        }
        return caseIsApprovalPendingFlagTobeUpdated;
    }
    
}