force-app/main/default/objects/ASF_Bulk_Upload_Header__c/ASF_Bulk_Upload_Header__c.object-meta.xml
<CustomObject>
    <label>Bulk Upload Header</label>
    <nameField>
        <displayFormat>Head-{00000}</displayFormat>
        <label>Bulk Upload Header #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Upload Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Bulk_Upload_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Upload Completed</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Bulk_Upload_Line_Item__c/ASF_Bulk_Upload_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Bulk Upload Line Item</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Bulk Upload Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Upload Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Bulk_Upload_Line_Item__c/fields/Bulk_Upload_Header__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Upload_Header__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Header</label>
    <referenceTo>ASF_Bulk_Upload_Header__c</referenceTo>
    <relationshipLabel>Bulk Upload Line Items</relationshipLabel>
    <relationshipName>Bulk_Upload_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Bulk_Upload_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Event fired</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ASF_BulkCsvController_Test.cls
/**
 * @description       : 
 * @author            : rsinghnagar@salesforce.com
 * @group             : 
 * @last modified on  : 07-01-2024
 * @last modified by  : rsinghnagar@salesforce.com
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   06-28-2024   rsinghnagar@salesforce.com   Initial Version
**/
@isTest(seeAllData=false)
public class ASF_BulkCsvController_Test {

    @TestSetup
    public static void setupData(){
    	 ASF_TestDataFactory.createCaseRecords(1);   
    }
    
    @isTest
    private static void getMetadataDetailsTest() {
        Test.startTest();
        ASF_BulkCsvController.getMetadataDetails(); 
        Test.stopTest();     
    }
    @isTest
    private static void getCSVTemplateTest() {
        Test.startTest();
            String result = ASF_BulkCsvController.getCSVTemplate('ABHFL_Create_Case');
        	String resultFalse = ASF_BulkCsvController.getCSVTemplate('test');
        	Assert.areNotEqual(result, '');
        Test.stopTest();     
    }
    @isTest
    private static void generateCSVFileWithDataTest() {
        Test.startTest();
        Id caseId = [select Id from case LIMIT 1].Id;
         	Object result = ASF_BulkCsvController.generateCSVFileWithData('ABHFL_Create_Case','test',caseId,'__Recent');
        	Assert.isNotNull(result);
        Test.stopTest();     
    }
    @isTest
    private static void fetchCSVUploadProgressTest() {
        Id caseId = [select Id from case LIMIT 1].Id;
        ASF_Bulk_Upload_Header__c headerRec = new ASF_Bulk_Upload_Header__c(Total_Rows__c=1,Status__c=' Pending',Template_Name__c='ABHFL_Bulk_Create_Case');
        insert headerRec;
        ASF_Bulk_Upload_Line_Item__c bulkItemRec = new ASF_Bulk_Upload_Line_Item__c(Bulk_Upload_Header__c = headerRec.Id, Status__c = 'Failure');
        insert bulkItemRec;
        
        Test.startTest();
        String response = ASF_BulkCsvController.fetchfieldNames(headerRec.Id);
        String response1 = ASF_BulkCsvController.refreshHeader(headerRec.Id);
        ASF_BulkCsvController.CSVProgressWrapper result = ASF_BulkCsvController.fetchCSVUploadProgress(headerRec.Id, new List<Id>{caseId}, true);
        Assert.isNotNull(result);
        Assert.areNotEqual(response, 'Error');
        Object resultObj = ASF_BulkCsvController.downloadUploadResults(headerRec.Id);
        Test.stopTest();     
    }
}