force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Case Details</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/STP_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>STP_Request_Type__c</fullName>
    <description>Used for HFL Inbound API</description>
    <label>STP Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Download</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABHFL_Payment__c/ABHFL_Payment__c.object-meta.xml
<CustomObject>
    <description>Object to record Payments associated with a case</description>
    <label>ABHFL Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>ABHFL Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Parent Case for the Payment</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Payments</relationshipLabel>
    <relationshipName>ABFL_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ABHFL_Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch_Master__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Integration_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Ext_Id__c</fullName>
    <label>Integration Ext Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch_Master__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Last_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Disbursement_Date__c</fullName>
    <label>Last Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Loan_Disbursement_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Disbursement_Status__c</fullName>
    <label>Loan Disbursement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partially</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch_Master__c/Branch_Master__c.object-meta.xml
<CustomObject>
    <label>Branch Master</label>
    <nameField>
        <label>Branch Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Master__c/fields/Branch_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Queue_Id__c</fullName>
    <label>Branch  Queue Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Business_Unit__c,&quot;ABSLI&quot;), &quot;ABSLI&quot;, &quot;&quot;)</defaultValue>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABHFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABHFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABHFL Case Detail</label>
    <referenceTo>ABHFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Master__c.field-meta.xml
<CustomField>
    <fullName>Branch_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Master</label>
    <referenceTo>Branch_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Stage_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Stage_Change_Date__c</fullName>
    <label>Case Stage Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_2__c</fullName>
    <label>Stage SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_3__c</fullName>
    <label>Stage SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/SLA_Threshold_Warning__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>When you change this setting , please note that existing Cases needs to be reedited for new changes to come in.</description>
    <label>SLA Threshold Warning</label>
</CustomObject>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_1_Label__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1_Label__c</fullName>
    <label>Case SLA Threshold 1 Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_2_Label__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2_Label__c</fullName>
    <label>Case SLA Threshold 2 Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_3_Label__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3_Label__c</fullName>
    <label>Case SLA Threshold 3 Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_2__c</fullName>
    <label>Stage SLA Threshold 2</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_3__c</fullName>
    <label>Stage SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ABFL</fullName>
    </customValue>
    <customValue>
        <fullName>ABHFL</fullName>
    </customValue>
    <customValue>
        <fullName>Payments</fullName>
    </customValue>
    <customValue>
        <fullName>ABWM</fullName>
    </customValue>
    <customValue>
        <fullName>ABSLI</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ABHFL_StageApex_Test.cls
@isTest
public class ABHFL_StageApex_Test {
 @TestSetup
	static void testData(){
        //Create Account
        Account accRec = ASF_TestDataFactory.insertBusinessAccount('ABHFLLLL','Test_1');
        Contact  cont = ASF_TestDataFactory.insertContact('Test 1@', '');
        //Create BranchMaster
        Branch_Master__c branchMstr = new Branch_Master__c();
        branchMstr.Branch_Queue_Id__c = [Select Id from Group where Type = 'Queue' LIMIT 1].Id;
        insert branchMstr;
        //Create Asset
        Asset astRec = ASF_TestDataFactory.createAsset(accRec.Id,'Loans');
        astRec.LAN__c = 'Test';
        astRec.Branch__c = branchMstr.Id;
        astRec.Last_Disbursement_Date__c = Date.Today();
        astRec.Loan_Disbursement_Status__c = 'Complete';
        update astRec;
        //Create Case Extension record
        ABHFL_Case_Detail__c caseDetail = new ABHFL_Case_Detail__c();
        caseDetail.STP_Request_Type__c = 'Email';
        insert caseDetail;
       
        //Create Case
        List<Case> caseRecList = ASF_TestDataFactory.createCaseRecords(1);
        caseRecList[0].AssetId = astRec.Id;
        caseRecList[0].ABHFL_Case_Detail__c = caseDetail.Id;
        caseRecList[0].Case_Stage_Change_Date__c = date.today();
       // caseRecList[0].Business_Unit__c = 'ABHFL';
        update caseRecList[0];
        
        ASF_TestDataFactory.createCaseCategoryConfig();

        //create ASF Integration
        ASF_Integration__c integ = new ASF_Integration__c();
        integ.External_Id__c = 'ASF_INT_01';
        integ.Display_Name__c = 'LOD';
        insert integ;
        
        ASF_Case_Integration__c caseInt = new ASF_Case_Integration__c();
        caseInt.Integration_Ext_Id__c = integ.External_Id__c;
        caseInt.Case__c = caseRecList[0].Id;
        insert caseInt;
        //Create document
        ContentVersion content = new ContentVersion();
        content.PathOnClient = 'Response.txt';
        content.Title = 'Response';
        content.VersionData = Blob.valueof('Test');
        insert content;
        //Link document to Case Integration
        ContentVersion conVersion = [Select ContentDocumentId from ContentVersion where id =: content.Id];
        ContentDocumentLink docLink = new ContentDocumentLink();
        docLink.LinkedEntityId = caseInt.Id;
        docLink.ContentDocumentId = conVersion.ContentDocumentId;
        docLink.ShareType = 'V';
        insert docLink;
        SLA_Threshold_Warning__c slaThreshold = SLA_Threshold_Warning__c.getOrgDefaults();
        slaThreshold.Stage_SLA_Threshold_1__c = .5;
        slaThreshold.Stage_SLA_Threshold_2__c = .75;
        slaThreshold.Stage_SLA_Threshold_3__c = 1;
        slaThreshold.Case_SLA_Threshold_1_Label__c = '50%';
        slaThreshold.Case_SLA_Threshold_2_Label__c = '75%';
        slaThreshold.Case_SLA_Threshold_3_Label__c = '100%';
        slaThreshold.Case_SLA_Threshold_1__c = .5;
        slaThreshold.Case_SLA_Threshold_2__c = .75;
        slaThreshold.Case_SLA_Threshold_3__c = 1;
        upsert slaThreshold SLA_Threshold_Warning__c.Id;
	 }
    @IsTest
    static void testPreClsStatementStageApexClass(){
        Case caseRecord = [Select id,Stage__c,CCC_External_Id__c, Previous_Stage__c,ABHFL_Case_Detail__r.As_On_Date__c  from Case limit 1];
        List<ABHFL_Payment__c> dummyPayments = new List<ABHFL_Payment__c>();
    	for (Integer i = 0; i < 5; i++) {  // Create 5 dummy payments
        	ABHFL_Payment__c payment = new ABHFL_Payment__c(
            Case__c = caseRecord.Id,
            Realization_Status__c = 'Bounce',
            Date__c = Date.Today(),
            Amount__c=5000,
            Mode_of_Payment__c='Escrow',
            Payment_Identifier__c='43234234'
            );
        dummyPayments.add(payment);
    	}
        insert dummyPayments;
        //Assertion 
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls =  ABHFL_PreClsStatementStageApex.beforeStageMovement(new List<Case>{caseRecord});
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls1 =  ABHFL_PreClsStatementStageApex.afterStageMovement(new List<Case>{caseRecord});
        System.assertEquals('Success',retCls.get(caseRecord.Id).Status,'Done');
        
	}
    @IsTest
    static void testPreClosureStageApexClass(){
        Case caseRecord = [Select id,Stage__c,CCC_External_Id__c,Short_URL__c,ABHFL_Case_Detail__r.Preferred_Branch__c  from Case limit 1];
        List<ABHFL_Payment__c> dummyPayments = new List<ABHFL_Payment__c>();
    	for (Integer i = 0; i < 5; i++) {  // Create 5 dummy payments
        	ABHFL_Payment__c payment = new ABHFL_Payment__c(
            Case__c = caseRecord.Id,
            Realization_Status__c = 'Bounce',
            Date__c = Date.Today(),
            Amount__c=5000,
            Mode_of_Payment__c='Escrow',
            Payment_Identifier__c='43234234'
            );
        dummyPayments.add(payment);
    	}
        insert dummyPayments;
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls =  ABHFL_PreClosureStageApex.beforeStageMovement(new List<Case>{caseRecord});
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls1 =  ABHFL_PreClosureStageApex.afterStageMovement(new List<Case>{caseRecord});
        System.assertEquals('Success',retCls.get(caseRecord.Id).Status,'Done');
        //for stage Hub location
        caseRecord.Stage__c='Hub Location';
        caseRecord.Stage__c='Branch';
        caseRecord.Stage__c='AOM/ROM';
        update caseRecord;
        
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls2 =  ABHFL_PreClosureStageApex.beforeStageMovement(new List<Case>{caseRecord});
        System.assertEquals('Success',retCls2.get(caseRecord.Id).Status,'Done');
	}
    
    @IsTest
    static void testReqResolvedStageApexClass(){
        Case caseRecord = [Select id,Stage__c,CCC_External_Id__c  from Case limit 1];
        List<ABHFL_Payment__c> dummyPayments = new List<ABHFL_Payment__c>();
    	for (Integer i = 0; i < 5; i++) {  // Create 5 dummy payments
        	ABHFL_Payment__c payment = new ABHFL_Payment__c(
            Case__c = caseRecord.Id,
            Realization_Status__c = 'Bounce',
            Date__c = Date.Today(),
            Amount__c=5000,
            Mode_of_Payment__c='Escrow',
            Payment_Identifier__c='43234234'
            );
        dummyPayments.add(payment);
    	}
        insert dummyPayments;
        //Assertion
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls =  ABHFL_ReqResolvedStageApex.beforeStageMovement(new List<Case>{caseRecord});
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls1 =  ABHFL_ReqResolvedStageApex.afterStageMovement(new List<Case>{caseRecord});
        System.assertEquals('Success',retCls.get(caseRecord.Id).Status,'Done');
        
	}
    @IsTest
    static void testRequestInProgressApexClass(){
        Case caseRecord = [Select id,Stage__c,CCC_External_Id__c, AssetId,Asset.Branch__r.Branch_Queue_Id__c, Source__c  from Case limit 1];
        List<ABHFL_Payment__c> dummyPayments = new List<ABHFL_Payment__c>();
    	for (Integer i = 0; i < 5; i++) {  // Create 5 dummy payments
        	ABHFL_Payment__c payment = new ABHFL_Payment__c(
            Case__c = caseRecord.Id,
            Realization_Status__c = 'Bounce',
            Date__c = Date.Today(),
            Amount__c=5000,
            Mode_of_Payment__c='Escrow',
            Payment_Identifier__c='43234234'
            );
        dummyPayments.add(payment);
    	}
        insert dummyPayments;
        //Assertion
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls =  ABHFL_requestInProgressApexClass.beforeStageMovement(new List<Case>{caseRecord});
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls1 =  ABHFL_requestInProgressApexClass.afterStageMovement(new List<Case>{caseRecord});
        caseRecord.CCC_External_Id__c = 'hfl003';
        update caseRecord;
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls3 =  ABHFL_requestInProgressApexClass.beforeStageMovement(new List<Case>{caseRecord});
        System.assertEquals('Success',retCls.get(caseRecord.Id).Status,'Done');
        
	}
     @IsTest
    static void testsendPaymentLinkMultiLAN(){
        Case caseRecord = [Select id,Stage__c,CCC_External_Id__c,ABHFL_Case_Detail__c  from Case limit 1];
        List<ABHFL_Payment__c> dummyPayments = new List<ABHFL_Payment__c>();
    	for (Integer i = 0; i < 5; i++) {  // Create 5 dummy payments
        	ABHFL_Payment__c payment = new ABHFL_Payment__c(
            Case__c = caseRecord.Id,
            Realization_Status__c = 'Bounce',
            Date__c = Date.Today(),
            Amount__c=5000,
            Mode_of_Payment__c='Escrow',
            Payment_Identifier__c='43234234'
            );
        dummyPayments.add(payment);
    	}
        insert dummyPayments;
        //Assertion
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls =  ABHFL_sendPaymentLinkMultiLAN.beforeStageMovement(new List<Case>{caseRecord});
        Map<Id, ASF_CaseMovementHelper.CaseStageValidationWrapper> retCls1 =  ABHFL_sendPaymentLinkMultiLAN.afterStageMovement(new List<Case>{caseRecord});
        System.assertEquals('Success',retCls.get(caseRecord.Id).Status,'Done');
        
	}
}