force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2015-16</fullName>
            </value>
            <value>
                <fullName>2016-17</fullName>
            </value>
            <value>
                <fullName>2017-18</fullName>
            </value>
            <value>
                <fullName>2018-19</fullName>
            </value>
            <value>
                <fullName>2019-20</fullName>
            </value>
            <value>
                <fullName>2020-21</fullName>
            </value>
            <value>
                <fullName>2021-22</fullName>
            </value>
            <value>
                <fullName>2022-23</fullName>
            </value>
            <value>
                <fullName>2023-24</fullName>
            </value>
            <value>
                <fullName>2024-25</fullName>
            </value>
            <value>
                <fullName>2025-26</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/ABHFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABHFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABHFL Case Detail</label>
    <referenceTo>ABHFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Text__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Framework.recordType-meta.xml
<RecordType>
    <fullName>Framework</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Framework</label>
</RecordType>

force-app/main/default/objects/Case_Integration_Outbound__e/Case_Integration_Outbound__e.object-meta.xml
<CustomObject>
    <label>Case Integration Outbound</label>
    <pluralLabel>Case Integration Outbound</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Case_Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Integration_ID__c</fullName>
    <label>Case Integration ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Request_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_Payload__c</fullName>
    <label>Request Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABHFL_ICAndPIC_IntegrationHelper.cls
/*********************************************************
* @Class        :  ABHFL_ICAndPIC_Integration
* @Author       :  Anirudh Raturi
* @Created Date :  13/12/2023
* @Last Modified:  14/12/2023
* @description  :  Helper Class for Interest Certificate And Provisional Interest Certificate Integration
*********************************************************/

public with sharing virtual class ABHFL_ICAndPIC_IntegrationHelper {

    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - generateRequest
    * @param caseRecord - Case record from the framework.
    * @param typ - Value for one of the key in JSON Structure of IC and PIC Integration
    * @param finYr - Value of Financial Year
    * @return - ABHFL_ICAndPIC_IntegrationRequestWrapper
    * @description - This method is use to create JSON structure for IC And PIC Integration
    *****************************************************************************************************************/
    public ABHFL_ICAndPIC_IntegrationRequestWrapper generateRequest(Case caseRecord, String typ, String finYr) {

        String lan = caseRecord.Asset.LAN__c;
        String integName = String.isNotBlank(getIntegrationName(caseRecord.Sub_Type_Text__c)) ? getIntegrationName(caseRecord.Sub_Type_Text__c) : '';

        ABHFL_ICAndPIC_IntegrationRequestWrapper reqBodyObj = new ABHFL_ICAndPIC_IntegrationRequestWrapper();
        reqBodyObj.caseId        = caseRecord.Id;
        reqBodyObj.souce         = 'CRM';
        reqBodyObj.requestType   = 'View';
        reqBodyObj.lan           = lan;
        reqBodyObj.documentType = 'BinaryData';

        if(integName == 'Interest Certificate') {
            reqBodyObj.financialYear = finYr;
            reqBodyObj.reportName   = ABHFL_Constants.IC_REPORT_NAME;
            
        }
        else if(integName == 'Provisional Interest Certificate') {
            reqBodyObj.reportName    = ABHFL_Constants.PIC_REPORT_NAME;
        }

        return reqBodyObj;
    }

    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - firePlatformEvtForCallout
    * @param caseInteg - Case Integration record from the framework.
    * @param jsonBody - Value for payload request in JSON Structure of IC and PIC Integration
    * @param caseSubType - Value of Case sub Type
    * @description - Firing Platform Event to make Callout for IC or PIC Integration.
*****************************************************************************************************************/
    public void firePlatformEvtForCallout(ASF_Case_Integration__c caseInteg, String jsonBody, String caseSubType) {

        String integName = String.isNotBlank(getIntegrationName(caseSubType)) ? getIntegrationName(caseSubType) : '';
        ASF_Case_Integration__c caseInt = [Select Name from ASF_Case_Integration__c where id =: caseInteg.Id WITH SECURITY_ENFORCED];
        
        Case_Integration_Outbound__e caseIntOut = new Case_Integration_Outbound__e ();
        caseIntOut.ServiceName__c  = ABHFL_Constants.REPORTING_SERVICE;
        caseIntOut.Business_Unit__c  = 'ABHFL';
        caseIntOut.Case_Integration_ID__c = caseInt.Name;
        caseIntOut.Integration_Name__c  = integName;
        caseIntOut.Request_Payload__c  =  jsonBody;
        Database.SaveResult publishResult = EventBus.publish(caseIntOut);
    }

    
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - getIntegrationName
    * @param caseSubType - Value of Case sub Type
    * @return - integName
    * @description - Get the name of the Integration on the basis of Case Sub Type.
*****************************************************************************************************************/
    public String getIntegrationName(String caseSubType) {

        String integName = '';

        if(caseSubType == 'Interest Schedule') {
            integName = 'Interest Certificate';
        }
        else if(caseSubType == 'Provisional Interest Certificate') {
            integName = 'Provisional Interest Certificate';
        }
        return integName;
    }

    
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - getFinancialYr
    * @param caseRecord - Case record from the framework.
    * @return - financialYr
    * @description - Get the Financial Year on the basis of Integration Name.
*****************************************************************************************************************/
    public String getFinancialYr(Case caseRecord) {

        String financialYr = '';

        String caseSubType = caseRecord.Sub_Type_Text__c;
        String integName = String.isNotBlank(getIntegrationName(caseSubType)) ? getIntegrationName(caseSubType) : '';
        financialYr = caseRecord.ABHFL_Case_Detail__r.Financial_Year__c;
        List<String> finYrList = String.isNotBlank(financialYr) ? financialYr.split('-') : new List<String>();

        if(integName == 'Interest Certificate') {
            if(finYrList.size() > 0) {
                Integer addedfinYr = Integer.valueOf(finYrList[0]) + 1;
                financialYr = finYrList[0] + '-' + String.valueOf(addedfinYr);
            }
        }
        return financialYr;
    }


/****************************************************************************************************************
    * @description - This is a wrapper class for  JSON structure of IC And PIC Integration.
*****************************************************************************************************************/
    public class ABHFL_ICAndPIC_IntegrationRequestWrapper {
        public String caseId;
        public String souce;
        public String requestType;
        public String lan;
        public String financialYear;
        public String reportName;
        public String documentType;
    }
}