force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Case Details</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <label>Lead Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>ABHIL</description>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Text__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Type_Text__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/DMS_File_Transfer__e.object-meta.xml
<CustomObject>
    <label>DMS File Transfer</label>
    <pluralLabel>DMS File Transfer</pluralLabel>
</CustomObject>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <label>CaseNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Contact_No__c</fullName>
    <label>Contact No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <label>ContentVersionId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Customer_Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Client_Code__c</fullName>
    <label>Customer Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/DMS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>DMS_External_ID__c</fullName>
    <label>DMS External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Doc_SubType__c.field-meta.xml
<CustomField>
    <fullName>Doc_SubType__c</fullName>
    <label>Doc SubType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Docgroup_Type__c.field-meta.xml
<CustomField>
    <fullName>Docgroup_Type__c</fullName>
    <label>Docgroup Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/File_Extension__c.field-meta.xml
<CustomField>
    <fullName>File_Extension__c</fullName>
    <label>File Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Is_Latest_Version__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Latest Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <label>Lead ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_File_Transfer__e/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <label>Version Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/DMS_Files__c.object-meta.xml
<CustomObject>
    <label>DMS Files</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>DMS Files Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DMS Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DMS_Files__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>DMS Files</relationshipLabel>
    <relationshipName>DMS_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <externalId>true</externalId>
    <label>ContentVersionId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/DMS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>DMS_External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>DMS External ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/File_Extension__c.field-meta.xml
<CustomField>
    <fullName>File_Extension__c</fullName>
    <label>File Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Has_Multiple_Versions__c.field-meta.xml
<CustomField>
    <fullName>Has_Multiple_Versions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Multiple Versions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Is_Latest_Version__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Latest Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Next_Retry__c.field-meta.xml
<CustomField>
    <fullName>Next_Retry__c</fullName>
    <inlineHelpText>Retry will not be attempted if status is success. Also, this field will be nullified on manual retries.</inlineHelpText>
    <label>Next Retry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Retry_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempt__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Attempt</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DMS_Files__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <label>Version Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABCL_RetryDMSFileTransfer.cls
public with sharing class ABCL_RetryDMSFileTransfer {
    /****************************************************************************************************************
    * @LOB - ABCL
    * @Function - retryDMSFileTransfer
    * @param recId - DMS record Id.
    * @description - Initiates File Transfer to DMS
    *****************************************************************************************************************/
    @InvocableMethod(label='Retry DMS File Transfer' description='This Apex is used to invoke the Failed or Pending DMS Integrations')
    public static void retryDMSFileTransfer(List<DMS_Files__c> dmsRecords){

        Set<Id> caseIds = new Set<Id>();
        for(DMS_Files__c dms : dmsRecords){
            if(ASF_Constants.RETRY_ENABLEDSTATUESES.contains(dms.Status__c)){
                caseIds.add(dms.Case__c);
            }
        } 

        if(caseIds.size() < 1){
            return;
        }

        Map<Id,Case> relatedCaseRecords = new Map<ID, Case>([Select id,Business_Unit__c,CaseNumber,Account.Client_Code__c,Type_Text__c,Sub_Type_Text__c,Nature__c,Lead__c,
                                                                CreatedDate,Asset.LAN__c,Asset.Lead_Id__c,Account.Phone,Account.PersonMobilePhone,Account.RecordType.Name  
                                                                from Case where Id in: caseIds]);

        DateTime startOfLast60Mins = System.now().addMinutes(-60);
        DateTime currentTime = System.now();
        Map<Integer,Integer> dmsRecordNoOfAttemptHashMap = new Map<Integer,Integer>();
        
        
        List<DMS_Files__c> oldDMSRecords = new List<DMS_Files__c> ();
        
        if(DMS_Files__c.SObjectType.getDescribe().isAccessible()){
            oldDMSRecords = [SELECT ID,Case__c,ContentVersionId__c FROM DMS_Files__c WHERE Case__c =:caseIds AND Case__r.IsClosed = true AND (CreatedDate > :startOfLast60Mins AND CreatedDate <= :currentTime)];
        }

        for(DMS_Files__c oldDMS : oldDMSRecords){
            
            String tempKey = oldDMS.Case__c+'_'+oldDMS.ContentVersionId__c;
            integer ihashKey = tempKey.hashCode();
            
            
            if(!dmsRecordNoOfAttemptHashMap.containsKey(ihashKey)){
                dmsRecordNoOfAttemptHashMap.put(ihashKey,0);
            }
            integer iTempCounter = dmsRecordNoOfAttemptHashMap.get(ihashKey);
            iTempCounter++;
            dmsRecordNoOfAttemptHashMap.put(ihashKey,iTempCounter);
        }

        List<DMS_Files__c> retryDMSRecords = new List<DMS_Files__c>();
        for(DMS_Files__c dms : dmsRecords){
            if(dms.Case__c != null && ASF_Constants.RETRY_ENABLEDSTATUESES.contains(dms.Status__c)){
                String tempKey = dms.Case__c+'_'+dms.ContentVersionId__c;
                integer ihashKey = tempKey.hashCode();
                Integer noOfAttempts = 0;
                if(dmsRecordNoOfAttemptHashMap.containsKey(ihashKey)){
                    noOfAttempts = dmsRecordNoOfAttemptHashMap.get(ihashKey);
                    if(noOfAttempts <= 2){
                        retryDMSRecords.add(dms);
                    }
                }
            }
        }

        if(retryDMSRecords.size() > 0){
            retryDMSFileTransferIntegration(retryDMSRecords,relatedCaseRecords,dmsRecordNoOfAttemptHashMap);
        }

        if(dmsRecords.size() > 0){
            processOldDMSFileTransferRecords(dmsRecords);
        }
    }
    /****************************************************************************************************************
    * @LOB - ABCL
    * @Function - retryDMSFileTransferIntegration
    * @param dmsRecords - DMS records.
    * @param relatedCaseRecords - Related Case records.
    * @param dmsRecordNoOfAttemptHashMap - DMS records with Attempt Count.
    * @description - Initiates Retry for File Transfer to DMS
    *****************************************************************************************************************/
    private static void retryDMSFileTransferIntegration(List<DMS_Files__c> dmsRecords,Map<Id,Case> relatedCaseRecords,Map<Integer,Integer> dmsRecordNoOfAttemptHashMap){
        List<DMS_Files__c> fileRecList = new List<DMS_Files__c>();
        for(DMS_Files__c file : dmsRecords){
            String tempKey = file.Case__c+'_'+file.ContentVersionId__c;
            integer ihashKey = tempKey.hashCode();
            integer noOfAttempt = 0;
            if(!dmsRecordNoOfAttemptHashMap.containsKey(ihashKey)){
                noOfAttempt = 1;
            }else {
                noOfAttempt = dmsRecordNoOfAttemptHashMap.get(ihashKey);
            }
            if(relatedCaseRecords.containsKey(file.Case__c)){
                DMS_Files__c fileRec = new DMS_Files__c();
                fileRec.ContentDocumentId__c = file.ContentDocumentId__c;
                fileRec.Case__c = file.Case__c;
                fileRec.ContentVersionId__c = file.ContentVersionId__c;
                fileRec.File_Name__c = file.File_Name__c;
                fileRec.Has_Multiple_Versions__c = file.Has_Multiple_Versions__c;
                fileRec.Is_Latest_Version__c = file.Is_Latest_Version__c;
                fileRec.Status__c = ABHFL_Constants.PENDING;
                fileRec.Version_Number__c = file.Version_Number__c;
                fileRec.Business_Unit__c = file.Business_Unit__c;
                DateTime currentDateTime = System.now();
                fileRec.DMS_External_ID__c = file.ContentVersionId__c + '' + currentDateTime.getTime();
                fileRec.File_Extension__c = file.File_Extension__c;
                fileRec.Next_Retry__c = System.now().addMinutes(15);
                fileRec.Retry_Attempt__c = noOfAttempt;
                fileRecList.add(fileRec);
            }
        }
        if(fileRecList.size() > 0){
            insert fileRecList;

            List<DMS_File_Transfer__e> dmsEventList = new List<DMS_File_Transfer__e>();

            for(DMS_Files__c file : fileRecList){

                Case caseRecord = relatedCaseRecords.get(file.Case__c);
                string leadId = '';
                string mobile = '';
                if(caseRecord.Asset.Lead_Id__c != null){
                    leadId = caseRecord.Asset.Lead_Id__c;
                } else if(caseRecord.Lead__c != null){
                    leadId = caseRecord.Lead__c;
                } else {
                    leadId = caseRecord.CaseNumber;
                }
                if(ABHFL_Constants.ACCOUNT_RECORDTYPE_NON_INDIVIDUAL == caseRecord.Account.RecordType.Name){
                    mobile = caseRecord.Account.PersonMobilePhone;
                }else {
                    mobile = caseRecord.Account.Phone;
                }

                dmsEventList.add(new DMS_File_Transfer__e(
                    Business_Unit__c = file.Business_Unit__c,
                    CaseNumber__c = caseRecord.CaseNumber,
                    ContentVersionId__c = file.ContentVersionId__c,
                    Customer_Client_Code__c = caseRecord.Account.Client_Code__c,
                    DMS_External_ID__c = file.DMS_External_ID__c,
                    File_Name__c = file.File_Name__c,
                    Is_Latest_Version__c = file.Is_Latest_Version__c,
                    Version_Number__c = file.Version_Number__c,
                    Application_ID__c = caseRecord.Asset.LAN__c,
                    Document_Type__c = caseRecord.Type_Text__c+'-'+caserecord.Sub_Type_Text__c+'-'+caseRecord.Nature__c,
                    File_Extension__c = file.File_Extension__c,
                    Doc_SubType__c = caseRecord.Sub_Type_Text__c,
                    Docgroup_Type__c = caseRecord.Nature__c.left(1) + '-' + caserecord.Type_Text__c,
                    Lead_ID__c = leadId,
                    Contact_No__c = mobile,
                    Source__c = ASF_Constants.DMS_FILE_TRANSFER_SOURCE
                ));
            }

            if(dmsEventList.size() > 0){
                List<Database.SaveResult> eventResult = EventBus.publish(dmsEventList);
            }
        }
    }
    /****************************************************************************************************************
    * @LOB - ABCL
    * @Function - processOldDMSFileTransferRecords
    * @param dmsRecords - DMS records.
    * @description - Updates older DMS File Transfer Records
    *****************************************************************************************************************/
    private static void processOldDMSFileTransferRecords(List<DMS_Files__c> dmsRecords){
        for(DMS_Files__c file : dmsRecords){
            file.Next_Retry__c = null;
            if(file.Status__c == 'Pending'){
                file.Status__c = 'Canceled';
            }
        }
        update dmsRecords;
    }
}