force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Case Details</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>This field will be used to store request and re-use them while re-invocation.</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Populate</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>UI Card</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>UI Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Bot_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Bot_Feedback__c</fullName>
    <label>Bot Feedback</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Unit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect Classification</fullName>
            </value>
            <value>
                <fullName>Manually case created</fullName>
            </value>
            <value>
                <fullName>Uncategorised</fullName>
            </value>
            <value>
                <fullName>Multiple Intent</fullName>
            </value>
            <value>
                <fullName>Change as per Customer Need</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <description>ABSLI Sub SubType</description>
    <label>Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accrued Bonus Additions Value Related</fullName>
            </value>
            <value>
                <fullName>HOLD Refund- Maturity/ Termination</fullName>
            </value>
            <value>
                <fullName>Leakage Salvage</fullName>
            </value>
            <value>
                <fullName>Leakage Winback</fullName>
            </value>
            <value>
                <fullName>Address/Contact/Email ID Related</fullName>
            </value>
            <value>
                <fullName>Assignment Related</fullName>
            </value>
            <value>
                <fullName>Maturity Related</fullName>
            </value>
            <value>
                <fullName>Medical Center Not Available</fullName>
            </value>
            <value>
                <fullName>Medical Center Service Feedback</fullName>
            </value>
            <value>
                <fullName>Name Change/Correction Related</fullName>
            </value>
            <value>
                <fullName>DOB change procedure</fullName>
            </value>
            <value>
                <fullName>Duplicate Policy Document Related</fullName>
            </value>
            <value>
                <fullName>EIA Account Related</fullName>
            </value>
            <value>
                <fullName>Freelook Information</fullName>
            </value>
            <value>
                <fullName>Overseas Medical test Payment to customer</fullName>
            </value>
            <value>
                <fullName>Loan Related</fullName>
            </value>
            <value>
                <fullName>Name Change Related</fullName>
            </value>
            <value>
                <fullName>Nomination Related</fullName>
            </value>
            <value>
                <fullName>post call- complain</fullName>
            </value>
            <value>
                <fullName>Premium paid certificate / Policy Statement from Chatbot</fullName>
            </value>
            <value>
                <fullName>Product related</fullName>
            </value>
            <value>
                <fullName>Refund Cheque RTGS Related</fullName>
            </value>
            <value>
                <fullName>Tele FMR Medical Report Tagging Status</fullName>
            </value>
            <value>
                <fullName>TDS Related</fullName>
            </value>
            <value>
                <fullName>Withdrawal/Survival Benefit Related</fullName>
            </value>
            <value>
                <fullName>Discontinued Payout Related</fullName>
            </value>
            <value>
                <fullName>DOB change related</fullName>
            </value>
            <value>
                <fullName>Top Up Related</fullName>
            </value>
            <value>
                <fullName>Benefits related</fullName>
            </value>
            <value>
                <fullName>Documentation related</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Recategorisation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Recategorisation_Reason__c</fullName>
    <label>Recategorisation Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Text__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Type_Text__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Framework.recordType-meta.xml
<RecordType>
    <fullName>Framework</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Framework</label>
</RecordType>

force-app/main/default/objects/Case_Integration_Outbound__e/Case_Integration_Outbound__e.object-meta.xml
<CustomObject>
    <label>Case Integration Outbound</label>
    <pluralLabel>Case Integration Outbound</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Case_Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Integration_ID__c</fullName>
    <label>Case Integration ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABCL_EBotFeedback.cls
/*********************************************************
*Class        :  ABCL_EBotFeedback
*Author       :  Anirudh Raturi
*Created Date :  21/12/2023
*Last Modified:  21/12/2023
*Description  :  Class for EBot Feedback Integration
*********************************************************/

public with sharing class ABCL_EBotFeedback implements ASF_IntegrationInvocable{

    public Case getCaseRec(String caseId){
        Case caseRecord = [
            SELECT CaseNumber, Recategorisation_Reason__c, CCC_External_Id__c, Type_Text__c, Sub_Type_Text__c, 
            Source__c, Business_Unit__c, Bot_Feedback__c, Issue_Type__c
            FROM Case
            WHERE Id =:caseId
        ];

        return caseRecord;
    }
    
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - evaluate
    * @param caseRec - Case record from the framework.
    * @return - ASF_IntegrationsController.IntegrationWrapper.
    * @Description - Invoked from the ASF_IntegrationsController class, this method evaluates whether Ebot Feedback Integration should be fired or not.
    *****************************************************************************************************************/
    public ASF_IntegrationsController.IntegrationWrapper evaluate(Case caseRec){
        
        ASF_IntegrationsController.IntegrationWrapper result = new ASF_IntegrationsController.IntegrationWrapper();
        result.status = 'Error';

        String caseRecId = caseRec.Id;
        Case caseRecord = getCaseRec(caseRecId);
        String source = caseRecord.Source__c;
        String bussUnit = caseRecord.Business_Unit__c;

        if(source == 'Email' && (bussUnit == 'ABFL' || bussUnit == 'ABHFL')) {
            result.status = 'Success';
            result.response = 'Ebot Feedback submitted successfully';
        }

        return result;
    }

    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - run
    * @param integ - ASF_Integration record.
    * @param caseRec - Case record from the framework.
    * @return - ASF_IntegrationsController.IntegrationWrapper.
    * @Description - Invoked from the ASF_IntegrationsController class, this method runs the Ebot Feedback Integration and creates Case Integration record.
    *****************************************************************************************************************/
    public ASF_IntegrationsController.IntegrationWrapper run(ASF_Integration__c integ, Case caseRec){
        
        ASF_IntegrationsController.IntegrationWrapper response = new ASF_IntegrationsController.IntegrationWrapper();
        callEbotFeedbackApi(caseRec.Id);
        response.status = 'Success';
        return response;
    }

     /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - processResponse
    * @param caseInteg - ASF_Case_Integration record.
    * @return - void.
    * @Description - Invoked from the Case Integration trigger, this method processes the response of the integration received.
    *****************************************************************************************************************/
    public void processResponse(ASF_Case_Integration__c caseInt){
        
    }

    // @Description - Callout for Ebot Feedback Integration.
    @AuraEnabled
    public static void callEbotFeedbackApi(String caseId){
        
        ABCL_EBotFeedback ebotFeedbackObj = new ABCL_EBotFeedback();

        Case caseRecord = ebotFeedbackObj.getCaseRec(caseId); 
        String cccExtId = caseRecord.CCC_External_Id__c;
        String caseSubType = caseRecord.Sub_Type_Text__c;

        List<ASF_Case_Integration__c> existingCaseIntRecords = [SELECT Id, Status__c FROM ASF_Case_Integration__c
                                                               WHERE Case__c =:caseRecord.Id 
                                                               AND Type__c = 'eBOTFeedback'];

        if(existingCaseIntRecords.size()>0){
        	for(ASF_Case_Integration__c cInt : existingCaseIntRecords){
                cInt.Status__c = 'Canceled';
            }
            update existingCaseIntRecords;            
        }

        String jsonBody = ebotFeedbackObj.generateReqBody(caseRecord);

        system.debug('jsonBody-- '+jsonBody);    
        ASF_Case_Integration__c caseInt = new ASF_Case_Integration__c();
        caseInt.Case__c  = caseRecord.Id;
        caseInt.Type__c = 'eBOTFeedback';
        caseInt.Status__c = 'Pending';
        caseInt.Request__c = jsonBody;
        insert caseInt;

        if(String.isNotBlank(jsonBody)) {
            ebotFeedbackObj.firePlatformEvtForCallout(caseInt, jsonBody, caseSubType);
        }
    }

    // @Description - Preparing JSON body for Ebot Feedback Integration.
    public String generateReqBody(Case caseRecord) {
        
        EBotFeedbackWrapper ebotFeedbackWrappObj = new EBotFeedbackWrapper();
        ebotFeedbackWrappObj.Case_X = caseRecord.CaseNumber;
        ebotFeedbackWrappObj.CATEGORY = caseRecord.CCC_External_Id__c;
        ebotFeedbackWrappObj.TYPE = caseRecord.Type_Text__c;
        ebotFeedbackWrappObj.SUB_TYPE = caseRecord.Sub_Type_Text__c;
        ebotFeedbackWrappObj.DESCRIPTION = String.isNotBlank(caseRecord.Recategorisation_Reason__c) ? caseRecord.Recategorisation_Reason__c : '';
        ebotFeedbackWrappObj.COMMENTS = caseRecord.Bot_Feedback__c;
        if(caseRecord.Business_Unit__c == ASF_Constants.ABSLI_BU){
            ebotFeedbackWrappObj.ISSUE_TYPE = caseRecord.Issue_Type__c;
            ebotFeedbackWrappObj.SOURCE = ABSLI_Constants.ESB_SOURCE_ID;
        }
        String reqBody = JSON.serialize(ebotFeedbackWrappObj);
        String actualReqBody = reqBody.replace('"Case_X":', '"case":');

        return actualReqBody;
    }

    // @Description - Firing Platform Event to make Callout for Ebot Feedback Api.
    public void firePlatformEvtForCallout(ASF_Case_Integration__c caseInteg, String jsonBody, String caseSubType) {

        ASF_Case_Integration__c caseInt = [SELECT Name, Case__r.Business_Unit__c FROM ASF_Case_Integration__c WHERE id =: caseInteg.Id];
        
        Case_Integration_Outbound__e caseIntOut = new Case_Integration_Outbound__e ();
        caseIntOut.Business_Unit__c  = String.isNotBlank(caseInt.Case__r.Business_Unit__c) ? caseInt.Case__r.Business_Unit__c : '';
        caseIntOut.Case_Integration_ID__c = caseInt.Name;
        caseIntOut.Integration_Name__c  = 'Ebot Feedback';
        caseIntOut.ServiceName__c  = 'eBotFeedback';
        caseIntOut.Request_Payload__c  =  jsonBody;
        Database.SaveResult publishResult = EventBus.publish(caseIntOut);
    }

    public class EBotFeedbackWrapper {
        public String Case_X;
        public String CATEGORY;
        public String TYPE;
        public String SUB_TYPE;
        public String DESCRIPTION;
        public String COMMENTS;
        public String ISSUE_TYPE;
        public String SOURCE;
        
    }

    public Map<Id, ASF_IntegrationsController.IntegrationWrapper> evaluate(List<Case> caseRecs){return null;}
    public Map<Id, ASF_IntegrationsController.IntegrationWrapper> run(Map<Id, List<ASF_Integration__c>> integs, List<Case> caseRecs){return null;}

}