force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABHFL Case Details</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Confidence_Score__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Score__c</fullName>
    <description>Used for HFL Inbound API</description>
    <label>Confidence Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Ebot_Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Ebot_Owner_Full_Name__c</fullName>
    <description>Used for HFL Inbound API</description>
    <label>Ebot Owner Full Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABHFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABHFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABHFL Case Detail</label>
    <referenceTo>ABHFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABHFL_CaseIntegrationHelper.cls
/*********************************************************
*Class        :  ABHFL_CaseIntegrationHelper
*Author       :  Siddarth Jaitly
*Created Date :  28/11/2023
*Last Modified:  30/11/2023
*Description  :  Case Integration Trigger Helper for ABHFL LOB
*********************************************************/
public with sharing class ABHFL_CaseIntegrationHelper {
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - eBotHandler
    * @param oldItems - map of cases from trigger.newMap(),newItems - map of cases from trigger.newMap()
    * @return - void .
    * @Description - Processing Ebot Response
    *****************************************************************************************************************/   
    public static void eBotHandler(map<Id, sObject> newItems,map<Id, sObject> oldItems){
        Set<Id> caseIds = new Set<Id>();
        Set<Id> caseIntegrationIds = new Set<Id>();
        List<Case> caseListToUpdate = new List<Case>();
        List<ABHFL_Case_Detail__c> caseDetailList = new List<ABHFL_Case_Detail__c>();
        
        for(ASF_Case_Integration__c recordAfter : (List<ASF_Case_Integration__c>)newItems.values()){
            ASF_Case_Integration__c recordBefore = (ASF_Case_Integration__c)oldItems.get(recordAfter.Id);
            if(String.isNotBlank(recordAfter.Response__c) &&  String.isBlank(recordBefore.Response__c) 
               && recordAfter.Status__c == 'Success' && String.isNotBlank(recordAfter.Case__c)){
                caseIds.add(recordAfter.Case__c);
                caseIntegrationIds.add(recordAfter.Id);
            }
        }
		system.debug('caseIds'+caseIds);
        system.debug('caseIntegrationIds'+caseIntegrationIds);
        Map<Id, Case> caseIdMap = new Map<Id, Case>([Select id,Type, CCC_External_Id__c,Status,Source__c,Origin from Case where id in: caseIds]);
        system.debug('caseIdMap'+caseIdMap);
        if(caseIntegrationIds.size() >  0) {
            for(Id caseIntId : caseIntegrationIds){
                ASF_Case_Integration__c recordAfter = (ASF_Case_Integration__c)newItems.get(caseIntId);
                if(caseIdMap.containsKey(recordAfter.Case__c)){
                    Case integrationCase = caseIdMap.get(recordAfter.Case__c);
                    system.debug(integrationCase);
                    if(String.isBlank(integrationCase.CCC_External_Id__c) && integrationCase.Source__c == 'Email'){
                        ABHFL_EbotWrapper.EbotResponseWrapper ebotResponse = (ABHFL_EbotWrapper.EbotResponseWrapper)JSON.deserialize(recordAfter.Response__c,ABHFL_EbotWrapper.EbotResponseWrapper.class);
                        integrationCase.CCC_External_Id__c = ebotResponse.CASESUBTYPE;
                        integrationCase.Comments = ebotResponse.COMMENT;
                        system.debug(ASF_Constants.RT_FRAMEWORK);
                        integrationCase.RecordTypeId = ASF_Constants.RT_FRAMEWORK;
                        if(integrationCase.Origin == 'ABHFL Email'){
                        	ABHFL_Case_Detail__c caseDetails = new ABHFL_Case_Detail__c();
                            caseDetails.Ebot_Owner_Full_Name__c  = ebotResponse.OWNERFULLNAME;
                            caseDetails.Confidence_Score__c  = Decimal.valueof(ebotResponse.CONFIDENCESCORE);
                            caseDetails.Case__c = integrationCase.Id;
                            caseDetailList.add(caseDetails);
                        }
                        //added by Ashish to test
                        //integrationCase.stage__c ='Open';
                        caseListToUpdate.add(integrationCase);
                    }   
                }
            }
            
            Map<Id,Id> caseIdToCaseDetailIdMap = new Map<Id,Id>();
            if(caseDetailList.size() > 0){
                insert caseDetailList;
                for(ABHFL_Case_Detail__c caseDetail : caseDetailList){
                    caseIdToCaseDetailIdMap.put(caseDetail.Case__c,caseDetail.Id);
                }
                for(Case cs : caseListToUpdate){
                    if(caseIdToCaseDetailIdMap.containsKey(cs.Id)){
                        cs.ABHFL_Case_Detail__c = caseIdToCaseDetailIdMap.get(cs.Id);
                    }
                }
            }
            
            if(caseListToUpdate.size() > 0){
                Database.SaveResult[] updateResult = Database.update(caseListToUpdate,false); 
                System.debug('updateResult'+updateResult);      
                System.debug('updateResult'+updateResult[0].getErrors());  
            }
        }
        transferAttachments(newItems,oldItems);
    }
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - transferAttachments
    * @param oldItems - map of cases from trigger.newMap(),newItems - map of cases from trigger.newMap()
    * @return - void .
    * @Description - Transfers Attachments from ASF_Case_Integration__c to Case
    *****************************************************************************************************************/       
    public static void transferAttachments(map<Id, sObject> newItems,map<Id, sObject> oldItems){
        Set<Id> caseIntegrationIds = new Set<Id>();
        for(ASF_Case_Integration__c recordAfter : (List<ASF_Case_Integration__c>)newItems.values()){
            ASF_Case_Integration__c recordBefore = (ASF_Case_Integration__c)oldItems.get(recordAfter.Id);
            if(String.isNotBlank(recordAfter.Response__c) &&  String.isBlank(recordBefore.Response__c) 
               && recordAfter.Status__c == 'Success' && String.isNotBlank(recordAfter.Case__c)){
					caseIntegrationIds.add(recordAfter.Id);
               }
        }
        List<ContentDocumentLink> relatedAttachments = [Select LinkedEntityId,ContentDocumentId from ContentDocumentLink 
                                                        where LinkedEntityId in: caseIntegrationIds];
        List<ContentDocumentLink> contentLinkToBeInserted = new List<ContentDocumentLink>();
        for(ContentDocumentLink contentLink : relatedAttachments){
            ContentDocumentLink link = new ContentDocumentLink();
            link.LinkedEntityId = ((ASF_Case_Integration__c)newItems.get(contentLink.LinkedEntityId)).Case__c;
            link.ContentDocumentId= contentLink.ContentDocumentId;
            link.ShareType = 'V';
            contentLinkToBeInserted.add(link);
        }
        
        if(contentLinkToBeInserted.size() > 0){
            Database.SaveResult[] upsertResult = Database.insert(contentLinkToBeInserted,false);         
        }
    }
}