force-app/main/default/objects/ABHFL_Case_Detail__c/ABHFL_Case_Detail__c.object-meta.xml
<CustomObject>
    <label>ABHFL Case Detail</label>
    <nameField>
        <displayFormat>ABHFL-{0000000}</displayFormat>
        <label>ABHFL Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABHFL Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Non Delinquent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Case_Categorization__c.field-meta.xml
<CustomField>
    <fullName>Case_Categorization__c</fullName>
    <label>Case Categorization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Correct</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Gap_IT__c.field-meta.xml
<CustomField>
    <fullName>Gap_IT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gap - IT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Gap_People__c.field-meta.xml
<CustomField>
    <fullName>Gap_People__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gap - People</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Gap_Process__c.field-meta.xml
<CustomField>
    <fullName>Gap_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gap - Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Gap_Product__c.field-meta.xml
<CustomField>
    <fullName>Gap_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gap - Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Regulator_Initiated__c.field-meta.xml
<CustomField>
    <fullName>Regulator_Initiated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Regulator Initiated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABHFL_Case_Detail__c/fields/Voice_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Voice_of_Customer__c</fullName>
    <label>Voice of Customer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CEC</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Nodal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>ABHIL</description>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABHFL_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABHFL_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABHFL Case Detail</label>
    <referenceTo>ABHFL_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABHFL_ComplaintCTSTHelper.cls
/*********************************************************
*@Class        :  ABHFL_AmortizationIntegration
*@Author       :  Dhinesh Kumar T
*@Created Date :  12/25/2023
*@Last Modified:  12/27/2023
*@description  :  Class for complaints stage movement helper. 
*********************************************************/
public with sharing class ABHFL_ComplaintCTSTHelper {
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - sendAcknowledgement
    * @param  - Case record 
    * @description - invoked from in progress stage to send acknowledgement mail.
    *****************************************************************************************************************/
    public static void sendAcknowledgement(Case caseRec){
    	Id caseId = caseRec.Id; 
    	Case caseRecord = [SELECT Id, Source__c, AccountId, CCC_External_Id__c, ContactId, OwnerId, CreatedById, Asset.LAN__c, Asset.Account_Status__c
                       FROM Case WHERE Id = :caseId WITH SECURITY_ENFORCED];

    	ASF_Case_Category_Config__c ccc = [SELECT Id, New_Case_Email_Template__c FROM ASF_Case_Category_Config__c 
                                           WHERE CCC_External_Id__c = :caseRecord.CCC_External_Id__c WITH SECURITY_ENFORCED LIMIT 1];

    	ABCL_IntegrationCommonUtility.createPELogAndinvokeCommPEevent(caseRecord, 
                                                                  ccc.New_Case_Email_Template__c, 
                                                                  null, 
                                                                  false);
	}
     /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - isInGrievanceTeam
    * @param  - Case record 
    * @description - invoked from resolved stage to check whether case owner belongs to grievance team
    *****************************************************************************************************************/
    public static boolean isInGrievanceTeam(Case caseRec){
       	Id caseId = caseRec.Id; 
    	Case caseRecord = [SELECT Id,OwnerId FROM Case WHERE Id = :caseId WITH SECURITY_ENFORCED];
        List<GroupMember> queueMemberships = [SELECT Id 
    										  FROM GroupMember 
    										  WHERE UserOrGroupId =: caseRecord.OwnerId 
        									     AND (
            									     group.DeveloperName='ABHFL_CEO_Desk_G' 
            									     OR group.DeveloperName='ABHFL_Express_Resolution_G' 
            									     OR group.DeveloperName='ABHFL_Grievance_G' 
            									     OR group.DeveloperName='ABHFL_Grievance_Head_G'
        										 ) WITH SECURITY_ENFORCED
											  ];
        return !queueMemberships.isEmpty();

    }
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - validateRCAfields
    * @param  - Case record 
    * @description - invoked from resolved stage to check whether RCA fields are filled.
    *****************************************************************************************************************/
    public class FieldValidationResult {
    	public Boolean result { get; set; }
    	public Set<String> blankFields { get; set; }
        public String message { get; set; }
	}

	public static FieldValidationResult validateRCAfields(Case caseRec){
    	Id caseId = caseRec.Id;
    	FieldValidationResult validation = new FieldValidationResult();
    	validation.result = false;
    	validation.blankFields = new Set<String>();

    	Case caseR = [SELECT Id, ABHFL_Case_Detail__r.Case_Categorization__c,
                         ABHFL_Case_Detail__r.Action_Taken__c, 
                         ABHFL_Case_Detail__r.Voice_of_Customer__c,
                         ABHFL_Case_Detail__r.Gap_IT__c,
                         ABHFL_Case_Detail__r.Gap_People__c, 
                         ABHFL_Case_Detail__r.Gap_Process__c,
                         ABHFL_Case_Detail__r.Gap_Product__c,
                         ABHFL_Case_Detail__r.Regulator_Initiated__c 
                  	  FROM Case 
                  	  WHERE Id = :caseId WITH SECURITY_ENFORCED];

    	Map<String, Schema.SObjectField> caseDetailFields = Schema.SObjectType.ABHFL_Case_Detail__c.fields.getMap();
    	Schema.DescribeFieldResult caseCategorizationField = caseDetailFields.get('Case_Categorization__c').getDescribe();
    	Schema.DescribeFieldResult actionTakenField = caseDetailFields.get('Action_Taken__c').getDescribe();
    	Schema.DescribeFieldResult voiceOfCustomerField = caseDetailFields.get('Voice_of_Customer__c').getDescribe();

    	if(String.isBlank(caseR.ABHFL_Case_Detail__r.Case_Categorization__c)) {
        	validation.blankFields.add(caseCategorizationField.getLabel());
        	validation.result = true;
    	}	
    	if(String.isBlank(caseR.ABHFL_Case_Detail__r.Action_Taken__c)) {
        	validation.blankFields.add(actionTakenField.getLabel());
        	validation.result = true;
    	}
    	if(String.isBlank(caseR.ABHFL_Case_Detail__r.Voice_of_Customer__c)) {
        	validation.blankFields.add(voiceOfCustomerField.getLabel());
        	validation.result = true;
    	}
         if(!caseR.ABHFL_Case_Detail__r.Gap_IT__c && 
       		!caseR.ABHFL_Case_Detail__r.Gap_People__c && 
       		!caseR.ABHFL_Case_Detail__r.Gap_Process__c && 
       		!caseR.ABHFL_Case_Detail__r.Gap_Product__c && 
       		!caseR.ABHFL_Case_Detail__r.Regulator_Initiated__c){
        		validation.result = true;
                validation.blankFields.add('Any one of GAP or Regulator Initiated.');
    	}
    
    	// Set the message within the wrapper
    	if(validation.result && !validation.blankFields.isEmpty()) {
        	String message = 'The following fields are mandatory to complete RCA : ';
        	for(String fieldLabel : validation.blankFields) {
            	message += fieldLabel + ', ';
        	}
        	message = message.removeEnd(', ');
        	validation.message = message;
    	}	
        
     	return validation;
	}	




}