force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Acknowledgement_contacted__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_contacted__c</fullName>
    <description>Complaints Resolution Field</description>
    <label>Acknowledgement contacted</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/IGMS_Complaint_Status__c.field-meta.xml
<CustomField>
    <fullName>IGMS_Complaint_Status__c</fullName>
    <description>This field is used in IRDAI to Salesforce Complaint Creation Inbound API.
This field is used in Salesforce to IRDAI Complaint Update Outbound API.</description>
    <label>IGMS Complaint Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Acknowledged</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Resolved</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Escalated</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Re-open</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Investigation_Comment__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Comment__c</fullName>
    <description>Complaints Resolution Field</description>
    <label>Investigation Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Unresolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution Comments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque payout processed and would be dispatched within next 4 working days</fullName>
            </value>
            <value>
                <fullName>Email sent to Customer</fullName>
            </value>
            <value>
                <fullName>Informatory email/letter</fullName>
            </value>
            <value>
                <fullName>Letter sent to customer</fullName>
            </value>
            <value>
                <fullName>NEFT payout processed and it will be credited to the customer’s account within next 5 working days</fullName>
            </value>
            <value>
                <fullName>Policy has been reinstated</fullName>
            </value>
            <value>
                <fullName>Request has been processed</fullName>
            </value>
            <value>
                <fullName>Age Proof not clear</fullName>
            </value>
            <value>
                <fullName>Age Proof not submitted</fullName>
            </value>
            <value>
                <fullName>Assignment for a MWP policy not allowed</fullName>
            </value>
            <value>
                <fullName>Assignment form is incomplete</fullName>
            </value>
            <value>
                <fullName>Assignment form is not duly signed by the witness</fullName>
            </value>
            <value>
                <fullName>Assignment form not submitted</fullName>
            </value>
            <value>
                <fullName>Assignment is not for a MWP policy</fullName>
            </value>
            <value>
                <fullName>Bank Account Details in cheque/passbook and request form is not matching</fullName>
            </value>
            <value>
                <fullName>Board resolution is not received</fullName>
            </value>
            <value>
                <fullName>Cancelled cheque not clear</fullName>
            </value>
            <value>
                <fullName>Cancelled cheque not submitted</fullName>
            </value>
            <value>
                <fullName>Case pending for investigation with grievance team, resolution will be provided by the grievance t</fullName>
            </value>
            <value>
                <fullName>Certificate of Insurability for Top up is not submitted</fullName>
            </value>
            <value>
                <fullName>Cheque already encashed</fullName>
            </value>
            <value>
                <fullName>COVID Questionnaire is not clear</fullName>
            </value>
            <value>
                <fullName>COVID Questionnaire is not submitted</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
            <value>
                <fullName>Deed of Relinquishment is incomplete/not received</fullName>
            </value>
            <value>
                <fullName>Details already available</fullName>
            </value>
            <value>
                <fullName>Discrepancy in Certificate of Insurability</fullName>
            </value>
            <value>
                <fullName>DOB on the Photo id proof and the DOB proof submitted does not match</fullName>
            </value>
            <value>
                <fullName>Duplicate request received</fullName>
            </value>
            <value>
                <fullName>Incomplete NRI details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Resolution_Comments__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Comments__c</fullName>
    <label>Resolution Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Resolve_case__c.field-meta.xml
<CustomField>
    <fullName>Resolve_case__c</fullName>
    <description>Complaints Resolution Field</description>
    <label>Resolve case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/ABSLI_IGMS_Document__c.object-meta.xml
<CustomObject>
    <description>This Object is used to store the IGMS File Details in IGMS to CRM Complaint Inbound API.</description>
    <label>ABSLI IGMS Document</label>
    <nameField>
        <displayFormat>IGMS-DOC-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI IGMS Docuements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This Field to store the Master Detail relation between Case and IGMS Document</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABSLI IGMS Docuements</relationshipLabel>
    <relationshipName>ABSLI_IGMS_Docuements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/recordTypes/Upload.recordType-meta.xml
<RecordType>
    <fullName>Upload</fullName>
    <active>true</active>
    <label>Upload</label>
</RecordType>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution_Comments__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Comments__c</fullName>
    <label>Resolution Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ABSLI_CTSTHelper.cls
/**
 * @description       : ABSLI CTST Helper
 * @author            : dhinesh.t@salesforce.com
 * @group             : 
 * @last modified on  : 07-11-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   06-05-2024   dhinesh.t@salesforce.com   Initial Version
**/
public with sharing class ABSLI_CTSTHelper {
    /****************************************************************************************************************
     * @LOB - ABSLI
     * @class - WrapperClass
     *****************************************************************************************************************/
     public class FieldValidationResult {
    	public Boolean result { get; set; }
    	public Set<String> blankFields { get; set; }
        public String message { get; set; }
	}
    /****************************************************************************************************************
     * @LOB - ABSLI
     * @Function validateResolutionfields - Requests
     * @param List<Case> caseRecs  
     * @return Map<Id, FieldValidationResult>
     * @description - To validate Resolution Fields
     *****************************************************************************************************************/
    public static Map<Id, FieldValidationResult> validateResolutionfields(List<Case> caseRecs){
    	//Id caseId = caseRec.Id;
        Map<Id, FieldValidationResult> resultsMap = new Map<Id, FieldValidationResult>();
        for(Case caseRec : caseRecs){
            FieldValidationResult validation = new FieldValidationResult();
            validation.result = false;
            validation.blankFields = new Set<String>();
            resultsMap.put(caseRec.Id, validation);
        }

    	Map<String, Schema.SObjectField> caseDetailFields = Schema.SObjectType.ABSLI_Case_Detail__c.fields.getMap();
        Schema.DescribeFieldResult caseOutcomeField = caseDetailFields.get('Outcome__c').getDescribe();
    	Schema.DescribeFieldResult caseResolutionField = caseDetailFields.get('Resolution__c').getDescribe();
        for(Case caseR : caseRecs){
            FieldValidationResult validation = resultsMap.get(caseR.Id);
            if(String.isBlank(caseR.ABSLI_Case_Detail__r.Outcome__c)) {
                validation.blankFields.add(caseOutcomeField.getLabel());
                validation.result = true;
            }
            if(String.isBlank(caseR.ABSLI_Case_Detail__r.Resolution__c)) {
                validation.blankFields.add(caseResolutionField.getLabel());
                validation.result = true;
            }
            System.debug(caseR.ABSLI_Case_Detail__r.Outcome__c);
            if (caseR.ABSLI_Case_Detail__r.Outcome__c == 'Unresolved') {
            	validation.result = true;
            	validation.message = 'Team Resolution Status cannot be "Unresolved" to resolve a Case.';
        	}
            
            // Set the message within the wrapper
            if(validation.result && !validation.blankFields.isEmpty()) {
                String message = 'The following fields are mandatory to Resolve Requests : ';
                for(String fieldLabel : validation.blankFields) {
                    message += fieldLabel + ', ';
                }
                message = message.removeEnd(', ');
                validation.message = message;
            }
            resultsMap.put(caseR.Id, validation);
        }
        
     	return resultsMap;
	}
    /****************************************************************************************************************
     * @LOB - ABSLI
     * @Function validateResolutionfieldComplaints
     * @param List<Case> caseRecs  
     * @return Map<Id, FieldValidationResult>
     * @description - To validate Resolution Fields
     *****************************************************************************************************************/
    public static Map<Id, FieldValidationResult> validateResolutionfieldComplaints(List<Case> caseRecs){
    	//Id caseId = caseRec.Id;
        Map<Id, FieldValidationResult> resultsMap = new Map<Id, FieldValidationResult>();
        for(Case caseRec : caseRecs){
            FieldValidationResult validation = new FieldValidationResult();
            validation.result = false;
            validation.blankFields = new Set<String>();
            resultsMap.put(caseRec.Id, validation);
        }

    	Map<String, Schema.SObjectField> caseDetailFields = Schema.SObjectType.ABSLI_Case_Detail__c.fields.getMap();
        Schema.DescribeFieldResult resolveCaseField = caseDetailFields.get('Resolve_case__c').getDescribe();
        Schema.DescribeFieldResult resolutionCommentsField = caseDetailFields.get('Resolution_Comments__c').getDescribe();
        Schema.DescribeFieldResult investigationCommentsField = caseDetailFields.get('Investigation_Comment__c').getDescribe();
        Schema.DescribeFieldResult acknowledgementConField = caseDetailFields.get('Acknowledgement_contacted__c').getDescribe();
        
        //IGMS Documents 
        Map<Id, List<ABSLI_IGMS_Document__c>> documentMap = new Map<Id, List<ABSLI_IGMS_Document__c>>();
        for (ABSLI_IGMS_Document__c doc : [
            SELECT Id, Case__c, RecordType.Name, Status__c 
            FROM ABSLI_IGMS_Document__c 
            WHERE Case__c IN :caseRecs
        ]) {
            if (!documentMap.containsKey(doc.Case__c)) {
                documentMap.put(doc.Case__c, new List<ABSLI_IGMS_Document__c>());
            }
            documentMap.get(doc.Case__c).add(doc);
        }
        
        for(Case caseR : caseRecs){
            FieldValidationResult validation = resultsMap.get(caseR.Id);
            if(String.isBlank(caseR.ABSLI_Case_Detail__r.Resolve_case__c)) {
                validation.blankFields.add(resolveCaseField.getLabel());
                validation.result = true;
            }
			if(String.isBlank(caseR.ABSLI_Case_Detail__r.Resolution_Comments__c)) {
                validation.blankFields.add(resolutionCommentsField.getLabel());
                validation.result = true;
            }
            if(String.isBlank(caseR.ABSLI_Case_Detail__r.Investigation_Comment__c)) {
                validation.blankFields.add(investigationCommentsField.getLabel());
                validation.result = true;
            }
            if(String.isBlank(caseR.ABSLI_Case_Detail__r.Acknowledgement_contacted__c)) {
                validation.blankFields.add(acknowledgementConField.getLabel());
                validation.result = true;
            }
            List<Task> openTasks = [SELECT id,Status FROM Task WHERE WhatId =: caseR.Id];
            for(Task relatedtask : openTasks){
                if(relatedtask.Status != 'Completed'){
                  	validation.result = true;
            		validation.message = 'Please complete required tasks to resolve the case.';  
                }
            }
            // Set the message within the wrapper
            if(validation.result && !validation.blankFields.isEmpty()) {
                String message = 'Below Resolution Fields are mandatory to close Complaints : ';
                for(String fieldLabel : validation.blankFields) {
                    message += fieldLabel + ', ';
                }
                message = message.removeEnd(', ');
                validation.message = message;
            }
            
            Boolean showDocError = false;
            if (caseR.ABSLI_Case_Detail__r.IGMS_Complaint_Status__c == '5' || caseR.ABSLI_Case_Detail__r.IGMS_Complaint_Status__c == '6') {
                showDocError = true;
                if(documentMap.containsKey(caseR.Id)){
                    for (ABSLI_IGMS_Document__c doc : documentMap.get(caseR.Id)) {
                    System.debug('hasValidDoc'+doc.RecordType.Name);
                    System.debug('prevStage'+caseR.ABSLI_Case_Detail__r.IGMS_Complaint_Status__c);
                    if (doc.RecordType.Name == 'Upload' && doc.Status__c == 'Success') {
                        showDocError = false;
                        break;
                    	}
                	}
                 }
            }
            if (showDocError) {
                validation.result = true;
                validation.message = 'Please upload at least one document to IGMS to resolve an escalated case.';
            }
            
            resultsMap.put(caseR.Id, validation);
        }
        
     	return resultsMap;
	}	
}