force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Status_Valid_For_STP__c.field-meta.xml
<CustomField>
    <fullName>Status_Valid_For_STP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used in conditional STP.</description>
    <label>Status Valid For STP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Integration_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Ext_Id__c</fullName>
    <label>Integration Ext Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Is_Validation_Success__c.field-meta.xml
<CustomField>
    <fullName>Is_Validation_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Validation Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>This field will be used to store request and re-use them while re-invocation.</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <description>LAN Number</description>
    <externalId>true</externalId>
    <label>Loan Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <externalId>true</externalId>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>ABHIL</description>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FTR__c.field-meta.xml
<CustomField>
    <fullName>FTR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FTR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MoveToNext__c.field-meta.xml
<CustomField>
    <fullName>MoveToNext__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MoveToNext</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Framework.recordType-meta.xml
<RecordType>
    <fullName>Framework</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Framework</label>
</RecordType>

force-app/main/default/objects/Case_Integration_Outbound__e/Case_Integration_Outbound__e.object-meta.xml
<CustomObject>
    <label>Case Integration Outbound</label>
    <pluralLabel>Case Integration Outbound</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Case_Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Integration_ID__c</fullName>
    <label>Case Integration ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Request_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_Payload__c</fullName>
    <label>Request Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Messages__mdt/Custom_Messages__mdt.object-meta.xml
<CustomObject>
    <label>Custom Messages</label>
    <pluralLabel>Custom Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Messages__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
                <default>true</default>
                <label>Payments</label>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ABHI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Messages__mdt/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Customer/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABSLI_TaxCertificateIntegration.cls
/**
 * @description Tax Certificate Download Outbound Integration From Salesforce to Ingenium
 * Customer Portal Provides Tax Certification Download feature at Portal End because of the same reason, this case become FTR
 * Service Agent to Click on the button initiate the integration. On Successful response, case to be marked as Closed
 *
 * @author Abinash Panigrahi
 * @date 2024-05-17
 */
public with sharing class ABSLI_TaxCertificateIntegration implements ASF_IntegrationInvocable {
	/**
	 * @description Invoked from the ASF_IntegrationsController class, this method evaluates whether integration should be fired or not
	 *
	 * @param caseRecs - List of Case record from the framework
	 * @return Map<Id, ASF_IntegrationsController.IntegrationWrapper>
	 */
	public Map<Id, ASF_IntegrationsController.IntegrationWrapper> evaluate(List<Case> caseRecs) {
		Map<Id, ASF_IntegrationsController.IntegrationWrapper> resultMap = new Map<Id, ASF_IntegrationsController.IntegrationWrapper>();

		List<Case> caseRecords = new List<Case>();
		for (Case caseRec : caseRecs) {
			caseRecords.add(ASF_IntegrationsController.queriedCasesForIntegration.get(caseRec.Id));
		}

		for (Case caseRecord : caseRecords) {
			ASF_IntegrationsController.IntegrationWrapper result = new ASF_IntegrationsController.IntegrationWrapper();

			result.status = ABSLI_Constants.ERROR;
			result.response = result.response = Custom_Messages__mdt.getInstance(
					ABSLI_Constants.TAXCERTIFICATE_EVALUATION_ERROR
				)
				.Message__c;
            //Customer Portal and Status_Valid_For_STP__c is false 
            if(caseRecord.Source__c == ABSLI_Constants.CUSTOMER_PORTAL && caseRecord.ABSLI_Case_Detail__r.Status_Valid_For_STP__c == false){
            	result.status = ABSLI_Constants.ERROR;
            	result.response = Custom_Messages__mdt.getInstance('ABSLI_CustomerPortal_STPFalse_Err').Message__c;
            }else{
                if (
                    (caseRecord.Technical_Source__c == 'API' && caseRecord.FTR__c) ||
                    caseRecord.Technical_Source__c == 'LWC'
                ) {
                    result.status = ABSLI_Constants.SUCCESS;
                    result.response = ABSLI_Constants.EVALUATION_SUCCESS;
                }
            }
            resultMap.put(caseRecord.Id, result);
            
        }
		return resultMap;
	}

	/**
	 * @description Invoked from the ASF_IntegrationsController class, this method runs the integration and creates Case Integration record
	 *
	 * @param integs - List of ASF_Integration record
	 * @param caseRecs - List of Case record from the framework
	 * @return Map<Id, ASF_IntegrationsController.IntegrationWrapper>
	 */
	public Map<Id, ASF_IntegrationsController.IntegrationWrapper> run(
		Map<Id, List<ASF_Integration__c>> integs,
		List<Case> caseRecs
	) {
		Map<Id, ASF_IntegrationsController.IntegrationWrapper> resultMap = new Map<Id, ASF_IntegrationsController.IntegrationWrapper>();

		//Before Initiating new Integration callout, cancel existing running request
		cancelPendingCaseIntegrationRequests(integs, caseRecs);

		List<Case> caseRecords = new List<Case>();
		for (Case caseRec : caseRecs) {
			caseRecords.add(ASF_IntegrationsController.queriedCasesForIntegration.get(caseRec.Id));
		}

		List<ASF_Case_Integration__c> newCaseIntegrations = new List<ASF_Case_Integration__c>();
		Map<Integer, Case_Integration_Outbound__e> peMap = new Map<Integer, Case_Integration_Outbound__e>();
		Integer index = 0;
		Map<Integer, Id> indexToCaseId = new Map<Integer, Id>();

		for (Case caseRecord : caseRecords) {
			string requestBody = JSON.serialize(
				new TCDRequestWrapper(
					caseRecord.Asset?.Policy_No__c == null ? caseRecord.LAN__c : caseRecord.Asset?.Policy_No__c,
					ABCL_IntegrationCommonUtility.dateFormat(
						caseRecord.ABSLI_Case_Detail__r?.From_Date__c,
						'dd/MM/YYYY'
					),
					ABCL_IntegrationCommonUtility.dateFormat(caseRecord.ABSLI_Case_Detail__r?.To_Date__c, 'dd/MM/YYYY')
				)
			);
			for (ASF_Integration__c intSpec : integs.get(caseRecord.Id)) {
				if (intSpec.Processing_Class__c == ABSLI_TaxCertificateIntegration.class.getName()) {
					ASF_Case_Integration__c caseInteg = new ASF_Case_Integration__c();
					caseInteg.Integration_Ext_Id__c = intSpec.External_Id__c;
					caseInteg.Case__c = caseRecord.Id;
					caseInteg.Status__c = ABSLI_Constants.PENDING;
					caseInteg.Request__c = requestBody;
					caseInteg.Response__c = ABSLI_Constants.WAITING_API_RESPONSE;
					caseInteg.Is_Validation_Success__c = true;
					newCaseIntegrations.add(caseInteg);

					Case_Integration_Outbound__e caseIntOut = new Case_Integration_Outbound__e();
					caseIntOut.Business_Unit__c = caseRecord.Business_Unit__c;
					caseIntOut.Request_Payload__c = requestBody;
					caseIntOut.Integration_Name__c = ABSLI_Constants.TAXCERTIFICATE_SERVICE_NAME;
					caseIntOut.ServiceName__c = ABSLI_Constants.TAXCERTIFICATE_SERVICE_NAME;
					peMap.put(index, caseIntOut);
					indexToCaseId.put(index, caseRecord.Id);
				}
				index++;
			}
		}

		index = 0;

		List<Database.SaveResult> results = Database.insert(newCaseIntegrations, false, AccessLevel.SYSTEM_MODE);
		Map<Id, ASF_Case_Integration__c> caseIntegrations = new Map<Id, ASF_Case_Integration__c>(
			ABSLI_IntegrationQueryHelper.getCaseIntegrations(newCaseIntegrations)
		);
		for (Database.SaveResult sr : results) {
			if (sr.isSuccess()) {
				Case_Integration_Outbound__e caseIntOut = peMap.get(index);
				caseIntOut.Case_Integration_ID__c = caseIntegrations.get(sr.getId()).Name;
				peMap.put(index, caseIntOut);
			} else {
				ASF_IntegrationsController.IntegrationWrapper wrap = new ASF_IntegrationsController.IntegrationWrapper();
				wrap.status = ABSLI_Constants.ERROR;
				resultMap.put(indexToCaseId.get(index), wrap);
				peMap.remove(index);
				indexToCaseId.remove(index);
			}
			index++;
		}

		List<Database.SaveResult> publishResults = EventBus.publish(peMap.values());
		index = 0;
		for (Database.SaveResult publishResult : publishResults) {
			if (publishResult.isSuccess()) {
				ASF_IntegrationsController.IntegrationWrapper wrap = new ASF_IntegrationsController.IntegrationWrapper();
				wrap.status = ABSLI_Constants.SUCCESS;
				wrap.response = Custom_Messages__mdt.getInstance(ABSLI_Constants.TAXCERTIFICATE_SUCCESS_MESSAGE)
					.Message__c;
				resultMap.put(indexToCaseId.values()[index], wrap);
			} else {
				ASF_IntegrationsController.IntegrationWrapper wrap = new ASF_IntegrationsController.IntegrationWrapper();
				wrap.status = ABSLI_Constants.ERROR;
				wrap.response = Custom_Messages__mdt.getInstance(ABSLI_Constants.TAXCERTIFICATE_FAILURE_MESSAGE)
					.Message__c;
				resultMap.put(indexToCaseId.values()[index], wrap);
			}
			index++;
		}

		return resultMap;
	}

	/**
	 * @description Before Initiating new Integration callout, cancel existing running request
	 *
	 * @param integs - List of Integration configs
	 * @param caseRecs - List of Case record from the framework
	 */
	public void cancelPendingCaseIntegrationRequests(Map<Id, List<ASF_Integration__c>> integs, List<Case> caseRecs) {
		Set<String> intIds = new Set<String>();
		for (Case caseRec : caseRecs) {
			for (ASF_Integration__c integ : integs.get(caseRec.Id)) {
				if (integ.Processing_Class__c == ABSLI_TaxCertificateIntegration.class.getName()) {
					intIds.add(integ.External_Id__c);
				}
			}
		}

		List<ASF_Case_Integration__c> existingCaseIntegrations = new List<ASF_Case_Integration__c>();
		for (ASF_Case_Integration__c caseInt : ABSLI_IntegrationQueryHelper.getCaseIntegrations(caseRecs, intIds)) {
			if (integs.containsKey(caseInt.Case__c)) {
				for (ASF_Integration__c integ : integs.get(caseInt.Case__c)) {
					if (
						integ.External_Id__c == caseInt.Integration_Ext_Id__c &&
						caseInt.Status__c == ABSLI_Constants.PENDING
					) {
						caseInt.Status__c = ABSLI_Constants.CANCELED;
						existingCaseIntegrations.add(caseInt);
					}
				}
			}
		}

		ASF_TriggerSkipperUtility.markTriggerRun('ASF_Case_Integration__c');
		Database.update(existingCaseIntegrations, AccessLevel.SYSTEM_MODE);
		ASF_TriggerSkipperUtility.resetTriggerRun('ASF_Case_Integration__c');
	}

	/**
	 * @description Invoked from the Case Integration trigger, this method processes the response of the integration received
	 *
	 * @param caseInteg - ASF_Integration record
	 */
	public void processResponse(ASF_Case_Integration__c caseInteg) {
		try {
			if (caseInteg.Status__c == ABSLI_Constants.SUCCESS) {
				Case caseRecord = ABSLI_IntegrationQueryHelper.getCaseInfo(caseInteg.Case__c);

				// TODO : Response Attribute Reference to determine
				TCDResponseWrapper jsonMap = (TCDResponseWrapper) JSON.deserialize(
					caseInteg.Response__c,
					TCDResponseWrapper.class
				);

				caseRecord.MoveToNext__c = true;
				Database.update(caseRecord, AccessLevel.SYSTEM_MODE);
			}
		} catch (Exception e) {
			System.debug('@@@mess' + e.getMessage() + ' ' + e.getLineNumber());
			ABCL_Logger.enableExceptionLogging();
			ABCL_Logger.push('ABSLI_TaxCertificateIntegration.processResponse');
			ABCL_Logger.message(e.getMessage());
			ABCL_Logger.emit();
		}
	}


	/**
	 * @description Invoked from the ASF_IntegrationsController class, this method evaluates whether integration should be fired or not
	 *
	 * @param caseRec - Case record from the framework
	 * @return ASF_IntegrationsController.IntegrationWrapper
	 */
	public ASF_IntegrationsController.IntegrationWrapper evaluate(Case caseRec) {
		ASF_IntegrationsController.IntegrationWrapper result = new ASF_IntegrationsController.IntegrationWrapper();
		result = evaluate(new List<Case>{ caseRec }).get(caseRec.Id);
		return result;
	}

	/**
	 * @description Invoked from the ASF_IntegrationsController class, this method runs the integration and creates Case Integration record
	 *
	 * @param caseInteg - ASF_Integration record
	 * @param caseRec - Case record from the framework
	 * @return ASF_IntegrationsController.IntegrationWrapper
	 */
	public ASF_IntegrationsController.IntegrationWrapper run(ASF_Integration__c caseInteg, Case caseRec) {
		ASF_IntegrationsController.IntegrationWrapper result = new ASF_IntegrationsController.IntegrationWrapper();
		result = run(
				new Map<Id, List<ASF_Integration__c>>{ caseRec.Id => new List<ASF_Integration__c>{ caseInteg } },
				new List<Case>{ caseRec }
			)
			.get(caseRec.Id);
		return result;
	}

	/**
	 * @description Tax Certificate Download (TCD) Wrapper Class to build Integration Request Body JSON
	 */
	@SuppressWarnings('PMD.VariableNamingConventions,PMD.FieldNamingConventions')
	public class TCDRequestWrapper {
		public RqReq RqReq { get; set; }

		public TCDRequestWrapper(String policyID, String startDate, String endDate) {
			this.RqReq = new RqReq();
			RqReq.details = new Details(policyID, startDate, endDate);
		}
	}

	public class RqReq {
		public Details Details { get; set; }
	}

	@SuppressWarnings('PMD.VariableNamingConventions,PMD.FieldNamingConventions')
	public class Details {
		public String POLICYID;
		public String SOURCE;
		public String STARTDATE;
		public String ENDDATE;
		public String AGENTCODE;
		public String OutputFormat;

		public Details(String policyID, String startDate, String endDate) {
			this.POLICYID = policyID;
			this.SOURCE = ABSLI_Constants.ESB_SOURCE_ID;
			this.STARTDATE = startDate;
			this.ENDDATE = endDate;
			this.AGENTCODE = ABSLI_Constants.TAXCERTIFICATE_AGENT_CODE;
			this.OutputFormat = ABSLI_Constants.TAXCERTIFICATE_OUTPUT_FORMAT;
		}
	}

	/**
	 * @description Tax Certificate Download (TCD) Wrapper Class to follow through Response Body JSON
	 */
	@SuppressWarnings('PMD.VariableNamingConventions,PMD.FieldNamingConventions')
	public class TCDResponseWrapper {
		public String URL;
		public String outputFormat;
	}
}