force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Bulk_Upload_Header__c/ASF_Bulk_Upload_Header__c.object-meta.xml
<CustomObject>
    <label>Bulk Upload Header</label>
    <nameField>
        <displayFormat>Head-{00000}</displayFormat>
        <label>Bulk Upload Header #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Upload Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Bulk_Upload_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Upload Completed</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Bulk_Upload_Line_Item__c/ASF_Bulk_Upload_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Bulk Upload Line Item</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Bulk Upload Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Upload Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Bulk_Upload_Line_Item__c/fields/Bulk_Upload_Header__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Upload_Header__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Header</label>
    <referenceTo>ASF_Bulk_Upload_Header__c</referenceTo>
    <relationshipLabel>Bulk Upload Line Items</relationshipLabel>
    <relationshipName>Bulk_Upload_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Bulk_Upload_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Event fired</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Last_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Disbursement_Date__c</fullName>
    <label>Last Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <externalId>true</externalId>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/SLA_Threshold_Warning__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>When you change this setting , please note that existing Cases needs to be reedited for new changes to come in.</description>
    <label>SLA Threshold Warning</label>
</CustomObject>

force-app/main/default/classes/ABHI_BulkAssignCaseConverterUtilityTest.cls
/**
* @File Name : ABHI_BulkAssignCaseConverterUtilityTest.cls
* @Description : Test Class for ABHI_BulkAssignCaseConverterUtility
* @Author : Salesforce
* @Last Modified By : Aditya Jawadekar
* @Last Modified On : October 12, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 12, 2024 | Aditya Jawadekar  | Initial Version
**/
@SuppressWarnings('PMD.ApexSOQLInjection,PMD.CyclomaticComplexity,PMD.StdCyclomaticComplexity,PMD.CognitiveComplexity,PMD.ExcessivePublicCount,PMD.IfStmtsMustUseBraces,PMD.IfElseStmtsMustUseBraces,PMD.AvoidDeeplyNestedIfStmts,PMD.ExcessiveParameterList,PMD.NcssMethodCount,PMD.ClassNamingConventions,PMD.FieldNamingConventions,PMD.VariableNamingConventions')
@isTest
public class ABHI_BulkAssignCaseConverterUtilityTest {
    
    /****************************************************************************************************************
    * @LOB - ABHI
    * @Function - setupTestData
    * @description - This method will be used to create testdata setup
    *****************************************************************************************************************/
    @testSetup
    static void setupTestData(){
        List<sObject> ls = Test.loadData(SLA_Threshold_Warning__c.sObjectType, 'testSLAThreshold');
        Account accRec = ASF_TestDataFactory.insertBusinessAccount('ABHI','Test_1');
        accRec.Client_Code__c = '352344';
        accRec.Business_Unit__c = 'ABHI';
        update accRec;
        Asset astRec = ASF_TestDataFactory.createAsset(accRec.Id,'Loans');
        astRec.Policy_No__c = 'LAN1234';
        astRec.Business_Unit__c = 'ABHI';
        astRec.Last_Disbursement_Date__c = Date.Today();
        update astRec;
        ABSLI_Case_Detail__c relRec = new ABSLI_Case_Detail__c(Address_Line_1__c = 'test');
        insert relRec;
        ASF_TestDataFactory.createCaseCategoryConfig();
        ASF_TestDataFactory.createC3WithPrePopulateIntegrations();
        ASF_TestDataFactory.createCaseRecords(0);
        Case caseRec = [Select CaseNumber from Case LIMIT 1];
        caseRec.ABSLI_Case_Detail__c = [Select Id from ABSLI_Case_Detail__c LIMIT 1].Id;
        update caseRec;
    }
    
    /****************************************************************************************************************
    * @LOB - ABHI
    * @Function - testconvertJSONRows
    * @description - Test method to test convertJSONRows - Happy path
    *****************************************************************************************************************/
    @IsTest
    static void testconvertJSONRows(){
        ASF_Bulk_Upload_Header__c headObj = new ASF_Bulk_Upload_Header__c();
        headObj.Template_Name__c = 'test';
        headObj.Total_Rows__c = 1;
        headObj.Status__c = 'Pending';
        insert headObj;
        ASF_Bulk_Upload_Line_Item__c lineitem = new ASF_Bulk_Upload_Line_Item__c();
        lineitem.Bulk_Upload_Header__c = headObj.Id;
        insert lineitem;
        case caserec = [select CaseNumber from Case LIMIT 1];
        String newOwner = [select id,name from group where type = 'Queue' and developerName LIKE 'ABHI_%' LIMIT 1].name;
        Map<Id, String> jsonRows = new Map<Id, String>();
        jsonRows.put(lineitem.Id, '{"Case number":"'+caserec.CaseNumber+'","New Owner":"'+newOwner+'", "Internal comments":"Owner change"}');
        ABHI_BulkAssignCaseConverterUtility utility = new ABHI_BulkAssignCaseConverterUtility();
        Test.startTest();
        ASF_BulkCaseProcessorUtility.ConvertionResult objRes = utility.convertJSONRows(jsonRows);
        System.assert(objRes != null, 'Bulk JSON is null');
        Test.stopTest();
    }
    
    /****************************************************************************************************************
    * @LOB - ABHI
    * @Function - testconvertJSONRowsResolved
    * @description - Test method to test convertJSONRows - multiple scenarios check
    *****************************************************************************************************************/
    @IsTest
    static void testconvertJSONRowsResolved(){
        ASF_Bulk_Upload_Header__c headObj = new ASF_Bulk_Upload_Header__c();
        headObj.Template_Name__c = 'test';
        headObj.Total_Rows__c = 1;
        headObj.Status__c = 'Pending';
        insert headObj;
        ASF_Bulk_Upload_Line_Item__c lineitem = new ASF_Bulk_Upload_Line_Item__c();
        lineitem.Bulk_Upload_Header__c = headObj.Id;
        insert lineitem;
        case caserec = [select CaseNumber,status from Case LIMIT 1];
        Map<Id, String> jsonRows = new Map<Id, String>();
        jsonRows.put(lineitem.Id, '{"Case number":"'+caserec.CaseNumber+'","New Owner":"newOwner", "Internal comments":"Owner change"}');
        ABHI_BulkAssignCaseConverterUtility utility = new ABHI_BulkAssignCaseConverterUtility();
        Test.startTest();
        utility.convertJSONRows(jsonRows);
        jsonRows.put(lineitem.Id, '{"Case number":"1234","New Owner":"newOwner", "Internal comments":"Owner change"}');
        utility.convertJSONRows(jsonRows);
        jsonRows.put(lineitem.Id, '{"Case number":"","New Owner":"newOwner", "Internal comments":"Owner change"}');
        utility.convertJSONRows(jsonRows);
        jsonRows.put(lineitem.Id, '{"Case number":"1234","New Owner":"", "Internal comments":"Owner change"}');
        utility.convertJSONRows(jsonRows);
        ASF_TriggerSkipperUtility.markTriggerRun('Case');
        caserec.status = 'Resolved';
        update caserec;
        jsonRows.put(lineitem.Id, '{"Case number":"'+caserec.CaseNumber+'","New Owner":"newOwner", "Internal comments":"Owner change"}');
        ASF_BulkCaseProcessorUtility.ConvertionResult objRes = utility.convertJSONRows(jsonRows);
        System.assert(objRes != null, 'Bulk JSON is null');
        Test.stopTest();
    }
    
    /****************************************************************************************************************
    * @LOB - ABHI
    * @Function - testprepareDownloadTemplate
    * @description - Test method to test prepareDownloadTemplate
    *****************************************************************************************************************/
    @IsTest
    static void testprepareDownloadTemplate() {        
        List<String> columnNames = new List<String>{'Case number','New Owner', 'Internal comments'};
            Case caserec = [Select Id from Case LIMIT 1];
        Test.startTest();
        ABHI_BulkAssignCaseConverterUtility utility = new ABHI_BulkAssignCaseConverterUtility();
        List<Map<String,String>> lstRes = utility.prepareDownloadTemplate(columnNames, 'Case', null, new List<String>{caserec.Id});
        System.assert(!lstRes.isEmpty(), 'List records for template download is null');
        List<Map<String,String>> lstResPctst = utility.prepareCtstData(new List<String>{'Id'},'ABSLI');
        System.assert(lstResPctst.isEmpty(), 'List records for ctst download is not null');
        Test.stopTest();
        
    }
    
    /****************************************************************************************************************
    * @LOB - ABHI
    * @Function - testprepareDownloadTemplate2
    * @description - Test method to test prepareCtstData
    *****************************************************************************************************************/
    @IsTest
    static void testprepareDownloadTemplate2() {        
        List<String> columnNames = new List<String>{'Case number','New Owner', 'Internal comments'};
            ListView lv = [Select Id, SobjectType, DeveloperName from ListView where SobjectType = 'Case' and DeveloperName = 'RecentlyViewedCases' LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new ASF_ListViewAPIMock());
        Test.startTest();
        ABHI_BulkAssignCaseConverterUtility utility = new ABHI_BulkAssignCaseConverterUtility();
        List<Map<String,String>> lstResPdt = utility.prepareDownloadTemplate(columnNames, 'Case', lv.Id, null);
        List<Map<String,String>> lstResPctst = utility.prepareCtstData(new List<String>(), '');
        System.assert(!lstResPdt.isEmpty(), 'List records for template download is null');
        System.assert(lstResPctst.isEmpty(), 'List records for ctst download is not null');
        Test.stopTest();
        
    }
    
}