force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/IRDAI_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>IRDAI_Token_Number__c</fullName>
    <description>Complaints IGMS Field</description>
    <label>IRDAI Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Resolved_Date__c.field-meta.xml
<CustomField>
    <fullName>Resolved_Date__c</fullName>
    <description>Complaints IGMS History Field</description>
    <label>Resolved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/ABSLI_IGMS_Document__c.object-meta.xml
<CustomObject>
    <description>This Object is used to store the IGMS File Details in IGMS to CRM Complaint Inbound API.</description>
    <label>ABSLI IGMS Document</label>
    <nameField>
        <displayFormat>IGMS-DOC-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI IGMS Docuements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Attachment_Source__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Source__c</fullName>
    <description>This field to store the IGMS to Salesforce Source in IGMS to Salesforce Complaint Inbound API.</description>
    <label>Attachment Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This Field to store the Master Detail relation between Case and IGMS Document</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ABSLI IGMS Docuements</relationshipLabel>
    <relationshipName>ABSLI_IGMS_Docuements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <label>ContentDocumentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>This field to store the File Name (Doc Name) from IGMS to CRM in Complaint Inbound API</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/IRDA_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>IRDA_Token_Number__c</fullName>
    <description>This field to store the IRDA Token Number in IGMS to Salesforce Complaint Inbound API.</description>
    <label>IRDA Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Policy_No_Text__c.field-meta.xml
<CustomField>
    <fullName>Policy_No_Text__c</fullName>
    <description>This field to store the Policy No coming from IGMS to Salesforce Complaint Inbound API.</description>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>52768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_IGMS_Document__c/recordTypes/Upload.recordType-meta.xml
<RecordType>
    <fullName>Upload</fullName>
    <active>true</active>
    <label>Upload</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <externalId>true</externalId>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IRDAI_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>IRDAI_Token_Number__c</fullName>
    <description>This field is used in ABSLI Complaint Creation Flow from RegisterComplaintIGMSToCRM Inbound call
This field is used in ABSLI Complaint Creation Flow from UpdateComplaintIGMSToCRM Inbound call</description>
    <label>IRDAI Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/Case_Integration_Outbound__e.object-meta.xml
<CustomObject>
    <label>Case Integration Outbound</label>
    <pluralLabel>Case Integration Outbound</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Case_Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Integration_ID__c</fullName>
    <label>Case Integration ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/Request_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_Payload__c</fullName>
    <label>Request Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Integration_Outbound__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABSLI_UploadIGMSComplaintsIntegration.cls
public with sharing class ABSLI_UploadIGMSComplaintsIntegration {
    public static Set<String> allowedFileTypeForIGMS = new Set<String>{'jpeg', 'pdf', 'jpg', 'png'};
    /****************************************************************************************************************
    * @param caseId
    * @return List<IGMSDocumentWrapper> 
    * @description - created to build the query and fetch the records for datatable
    *****************************************************************************************************************/ 
    @AuraEnabled
    public static List<IGMSDocumentWrapper> executeQuery(String caseId, List<String> clickedIds) {
        List<IGMSDocumentWrapper> igmsDocumentList = new List<IGMSDocumentWrapper>();
        List<ContentDocumentLink> contentLinks = [Select ContentDocumentId from ContentDocumentLink where LinkedEntityId =: caseId];
        if(contentLinks.size() > 0){
            Set<Id> contentDocumentIds = new Set<Id>();
            for(ContentDocumentLink conLink : contentLinks){
                 contentDocumentIds.add(conLink.ContentDocumentId);
            }
            List<ContentVersion> contentVersion = [Select Id, ContentDocumentId, Title,FileExtension,PathonClient,ContentSize
                                                    from ContentVersion where ContentDocumentId in: contentDocumentIds];

            List<ABSLI_IGMS_Document__c> igmsDocuments = [Select id,ContentDocumentId__c,Status__c
                                                         from ABSLI_IGMS_Document__c where Case__c =: caseId order by createddate asc];

            List<Case> caseRecords = [Select id,IsClosed from case where id =: caseId];

            Map<String,ABSLI_IGMS_Document__c> contentDocumentIdIGMSDocumentMap = new Map<String,ABSLI_IGMS_Document__c>();
            for(ABSLI_IGMS_Document__c doc : igmsDocuments){
                 contentDocumentIdIGMSDocumentMap.put(doc.ContentDocumentId__c, doc);
            }
            
            for(ContentVersion content : contentVersion){
                integer fileSize = content.contentSize/1024/1024;
                if(allowedFileTypeForIGMS.contains(content.FileExtension) && fileSize < ABSLI_Constants.IGMS_MAX_FILE_SIZE){
                IGMSDocumentWrapper docWrapper = new IGMSDocumentWrapper();
                docWrapper.fileName = content.Title +'.' + content.FileExtension;
                docWrapper.contentDocumentId = content.ContentDocumentId;
                docWrapper.Status = contentDocumentIdIGMSDocumentMap.containsKey(content.ContentDocumentId) ? contentDocumentIdIGMSDocumentMap.get(content.ContentDocumentId).Status__c : docWrapper.Status;
                if(docWrapper.Status == ABSLI_Constants.SUCCESS || caseRecords[0].IsClosed || (clickedIds.contains(content.contentDocumentId) && docWrapper.Status != ABSLI_Constants.FAILURE)){
                    docWrapper.allowUpload = true;
                }
                docWrapper.contentVersionID = content.Id;
                docWrapper.igmsDocumentId = contentDocumentIdIGMSDocumentMap.containsKey(content.ContentDocumentId) ? contentDocumentIdIGMSDocumentMap.get(content.ContentDocumentId).Id : null;
                igmsDocumentList.add(docWrapper);
            }
        }
        }
        return igmsDocumentList;
    }

    @AuraEnabled
    public static ResponseWrapper uploadAttachment(string recId, string rowWrapper){
        try {
            Boolean isSuccess = true;
            String errorResponse = '';
            IGMSDocumentWrapper docWrapper = new IGMSDocumentWrapper();
            List<Case> caseRecord = [Select id,CaseNumber,IRDAI_Token_Number__c,Business_Unit__c,Asset.Policy_No__c,
                                     ABSLI_Case_Detail__r.Resolved_Date__c
                                    from Case where id =: recId limit 1];

            if(String.isNotBlank(rowWrapper)){
                docWrapper = (IGMSDocumentWrapper)JSON.deserialize(rowWrapper, IGMSDocumentWrapper.class);
            }                                    
            if(caseRecord.size() > 0 && docWrapper != null){
                ABSLI_IGMS_Document__c igmsDocument = new ABSLI_IGMS_Document__c();
                igmsDocument.Status__c = ABSLI_Constants.PENDING;
                igmsDocument.ContentDocumentId__c = docWrapper.contentDocumentId;
                igmsDocument.Case__c = caseRecord[0].Id;
                igmsDocument.File_Name__c = docWrapper.fileName;
                igmsDocument.IRDA_Token_Number__c = caseRecord[0].IRDAI_Token_Number__c;
                igmsDocument.Attachment_Source__c = 'CRM to IRDA';
                igmsDocument.Policy_No_Text__c = caseRecord[0].Asset.Policy_No__c;
                igmsDocument.RecordTypeId = Schema.sObjectType.ABSLI_IGMS_Document__c.getRecordTypeInfosByDeveloperName().get('Upload').getRecordTypeId();
                IGMSUploadDocumentWrapper downloadWrapper = new IGMSUploadDocumentWrapper();
                downloadWrapper.caseId = caseRecord[0].CaseNumber;
                downloadWrapper.IRDA_Token_Number = caseRecord[0].IRDAI_Token_Number__c;
                downloadWrapper.fileName = docWrapper.fileName;
                if(caseRecord[0].ABSLI_Case_Detail__r.Resolved_Date__c != null){
                    downloadWrapper.isFRRDoc = true;
                }else{
                    downloadWrapper.isFRRDoc = false;
                }
                downloadWrapper.contentVersionID = docWrapper.contentVersionId;
                igmsDocument.Request__c = JSON.serialize(downloadWrapper);
                Database.SaveResult result = Database.insert(igmsDocument);
                if(result.isSuccess()){
                    Case_Integration_Outbound__e caseIntOut = new Case_Integration_Outbound__e();
                    caseIntOut.Business_Unit__c = caseRecord[0].Business_Unit__c;
                    caseIntOut.Request_Payload__c = JSON.serialize(downloadWrapper);
                    caseIntOut.Integration_Name__c = ABSLI_Constants.IGMS_UPDATECOMPLAINT_UPLOAD_SRV_NAME;
                    caseIntOut.ServiceName__c = ABSLI_Constants.IGMS_UPDATECOMPLAINT_UPLOAD_SRV_NAME;
                    caseIntOut.Case_Integration_ID__c = igmsDocument.Id;
                    Database.SaveResult publishResults = EventBus.publish(caseIntOut);
                    if(!publishResults.isSuccess()){
                        isSuccess = false;
                        errorResponse = publishResults.getErrors()[0].getMessage();
                    }
                }else{
                    isSuccess = false;
                    errorResponse = result.getErrors()[0].getMessage();
                }
            }

            return new ResponseWrapper(isSuccess,errorResponse,docWrapper.contentDocumentId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public class IGMSDocumentWrapper{
        @AuraEnabled
        public String fileName;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String contentDocumentId;
        @AuraEnabled
        public Boolean allowUpload; 
        @AuraEnabled
        public String uploadFileLabel;
        @AuraEnabled
        public string contentVersionID;
        @AuraEnabled
        public string igmsDocumentId;
        IGMSDocumentWrapper(){
            this.status = 'Not Started';
            this.allowUpload = false;
            this.uploadFileLabel = 'Upload File';
        }
    }

    public class IGMSUploadDocumentWrapper{
        public string IRDA_Token_Number;
        public string fileName;
        public boolean isFRRDoc;
        public string contentVersionID;
        public string caseId;
    }

    public Class ResponseWrapper{
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String errorMsg;
        @AuraEnabled
        public String contentDocumentId;
        /**
         * @description Custom constructor for the wrapper class
         * @param isSuccess
         * @param errorMsg
         **/
        public ResponseWrapper(Boolean isSuccess, String errorMsg, String contentDocumentId){
            this.isSuccess = isSuccess;
            this.errorMsg = errorMsg;
            this.contentDocumentId = contentDocumentId;
        }
    }
}