force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>To Store Phone number related to Mobile Update request.</description>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Status_Valid_For_STP__c.field-meta.xml
<CustomField>
    <fullName>Status_Valid_For_STP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used in conditional STP.</description>
    <label>Status Valid For STP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <externalId>true</externalId>
    <label>Client Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <description>This field is used to store PAN No.</description>
    <label>PAN No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN_Number__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number__c</fullName>
    <description>PAN Number</description>
    <label>PAN Number</label>
    <length>20</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Non_Individual.recordType-meta.xml
<RecordType>
    <fullName>Non_Individual</fullName>
    <active>true</active>
    <label>Non-Individual</label>
</RecordType>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Integration__c/fields/Query_Fields__c.field-meta.xml
<CustomField>
    <fullName>Query_Fields__c</fullName>
    <label>Query Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>Account.Client_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <externalId>true</externalId>
    <label>Policy No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <formula>IF(
    ISPICKVAL(Business_Unit__c, &apos;ABML&apos;),
    IF(
        ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Branch&apos;),
        Account.ABML_Branch_Code__c,
        IF(
            ISPICKVAL(Account.ABML_Contact_Type__c, &apos;Franchisee&apos;),
            Account.ABML_Franchisee_Code__c,
            Account.ABML_Client_ID__pc
        )
    ),
    Account.Client_Code__c
)</formula>
    <label>Client Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is default true when contact is created.</description>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ABSLI_NSDLPANVerificationTest.cls
@IsTest
public class ABSLI_NSDLPANVerificationTest {
    @TestSetup
    static void createTestData(){
        Account accRec = ASF_TestDataFactory.insertPersonAccount('First Name','Last Name','Test_1');
        Account accBussRec = ASF_TestDataFactory.insertBusinessAccount('Test_Cmp','Test_1');
        accBussRec.RecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get('Non_Individual').getRecordTypeId();
        update accBussRec;
        Contact conRec = ASF_TestDataFactory.insertContact('Test Contact','abcl@test.com');
        conRec.AccountId = accBussRec.Id;
        conRec.Primary__c = true;
        update conRec;
        ABSLI_Case_Detail__c caseDetail = new ABSLI_Case_Detail__c();
        caseDetail.PAN_Number__c = 'CYIPP8888A';
        insert caseDetail;
        List<Case> caseRecList = ASF_TestDataFactory.createCaseRecords(2);
        caseRecList[0].AccountId = accRec.Id;
        caseRecList[1].AccountId = accBussRec.Id;
        caseRecList[0].ABSLI_Case_Detail__c = caseDetail.Id;
        caseRecList[1].ABSLI_Case_Detail__c = caseDetail.Id;
        update caseRecList;
        ASF_TestDataFactory.createC3WithPrePopulateIntegrations();
        List<ASF_Integration__c> integs = [Select id from ASF_Integration__c];
        for(ASF_Integration__c integ : integs){
            integ.Processing_Class__c = 'ABSLI_PanUpdateIntegration';
            integ.Query_Fields__c = 'ABSLI_Case_Detail__r.Status_Valid_For_STP__c,CaseNumber,Account.Client_Code__c,ABSLI_Case_Detail__r.Mobile_Number__c,Business_Unit__c,Asset.Policy_No__c,Account.PAN__c';
        }
        update integs;
    }
    @IsTest
    static void getPanVerificationDetailsTest(){
        List<Case> caseList = [Select id,Account.IsPersonAccount from Case];
        for(Case caseRec : caseList){
            if(caseRec.Account.IsPersonAccount){
                ABSLI_NSDLPANVerification.PANVerificationWrapper personAccountresponse = ABSLI_NSDLPANVerification.getPanVerificationDetails(caseRec.Id);
                System.assertEquals('First Name Last Name',personAccountresponse.name);
                try{
                    ABSLI_NSDLPANVerification.PANVerificationWrapper errorResponse = ABSLI_NSDLPANVerification.getPanVerificationDetails(null);
                }catch(Exception ex){}
                Test.startTest();
                personAccountresponse.dob = system.today();
                /*StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
                mock.setStaticResource('PANVerificationMockResponse');
                mock.setStatusCode(200);
                mock.setHeader('Content-Type', 'application/json');*/
                Test.setMock(HttpCalloutMock.class, new ABSLI_NSDLPANResponseGenerator());
                ABSLI_NSDLPANVerification.PANVerificationResponseWrapper verificationResponse = ABSLI_NSDLPANVerification.verifyPAN(JSON.serialize(personAccountresponse)
                                                                                                                                    ,String.valueof(caseRec.Id)
                                                                                                                                    ,'test');
                ABSLI_NSDLPANVerification.PANVerificationResponseWrapper verificationResponse1 = ABSLI_NSDLPANVerification.verifyPANDetails(JSON.serialize(personAccountresponse)
                                                                                                                                    ,String.valueof(caseRec.Id));
                Test.stopTest();
                System.assertEquals(true,verificationResponse.isSuccess);
                ABSLI_NSDLPANVerification.PANVerificationResponseWrapper updatePanResponse = ABSLI_NSDLPANVerification.updatePAN(caseRec.Id);
                System.assertEquals(true,updatePanResponse.isSuccess);
                
            }else{
                ABSLI_NSDLPANVerification.PANVerificationWrapper bussAccountresponse = ABSLI_NSDLPANVerification.getPanVerificationDetails(caseRec.Id);
                System.assertNotEquals('Test_Cmp',bussAccountresponse.name);
            }           
        }
    }
    
    public class ABSLI_NSDLPANResponseGenerator implements HttpCalloutMock {
        /**
            * @description  Mocking failure response
            * @param req
            ** @return HTTPResponse
        */ 
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
			String s = '{}';
            res.setBody(s);
            res.setStatusCode(200);
            return res;
        }
    }
    
}