force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Before_3_PM__c.field-meta.xml
<CustomField>
    <fullName>Before_3_PM__c</fullName>
    <label>Before 3 PM?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Branch_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Branch_Receive_Date__c</fullName>
    <label>Branch Receive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Complaint_Category__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Category__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
                <default>true</default>
                <label>Information</label>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/IGMS_type_of_policy__c.field-meta.xml
<CustomField>
    <fullName>IGMS_type_of_policy__c</fullName>
    <description>Complaints IGMS Field</description>
    <label>IGMS type of policy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Conventional Life Insurance Policy</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Health Insurance Policy</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Unit Linked Insurance Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/IRDAI_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>IRDAI_Token_Number__c</fullName>
    <description>Complaints IGMS Field</description>
    <label>IRDAI Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Resolve_case__c.field-meta.xml
<CustomField>
    <fullName>Resolve_case__c</fullName>
    <description>Complaints Resolution Field</description>
    <label>Resolve case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ABHI</fullName>
            </value>
            <value>
                <fullName>ABSLAMC</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LWC</fullName>
                <default>true</default>
                <label>LWC</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Checklist__c/ASF_Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Checklist__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>ABSLI : 14 May 2024 - Created for ABSLI Asset Data Model requirement etc.</description>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FTR__c.field-meta.xml
<CustomField>
    <fullName>FTR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FTR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IGMS_Complaint_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>IGMS_Complaint_Type_Code__c</fullName>
    <description>This field is used in IGMS to Salesforce Complaint Creation Inbound API.</description>
    <label>IGMS Complaint Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IRDAI_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>IRDAI_Token_Number__c</fullName>
    <description>This field is used in ABSLI Complaint Creation Flow from RegisterComplaintIGMSToCRM Inbound call
This field is used in ABSLI Complaint Creation Flow from UpdateComplaintIGMSToCRM Inbound call</description>
    <label>IRDAI Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MoveToNext__c.field-meta.xml
<CustomField>
    <fullName>MoveToNext__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MoveToNext</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Technical_Source__c.field-meta.xml
<CustomField>
    <fullName>Technical_Source__c</fullName>
    <label>Technical Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Framework.recordType-meta.xml
<RecordType>
    <fullName>Framework</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Framework</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Interaction.recordType-meta.xml
<RecordType>
    <fullName>Interaction</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Interaction</label>
</RecordType>

force-app/main/default/classes/ABSLI_BeforeUpdateTriggerLogic.cls
/**
* @description       : BSLI BeforeUpdateTrigger Logic Before ASF Code
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 09-02-2024
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class ABSLI_BeforeUpdateTriggerLogic {
    /**
* @description This method is called from ASF_CaseTriggerBUSpecificHandler whenever a case is
* updated. This is the parent method
* @param newMap
* @param oldMap
*/
    public Static Map<Id, Case> absliCasesAdditionalFields;
    public static void executeBeforeLogic(Map<Id, Case> newMap, Map<Id, Case> oldMap){
        Id frameworkRTId = ASF_Constants.RT_FRAMEWORK;
        Map<Id,Case> mAbsliCases = new Map<Id,Case>();
        Map<ID,List<Case>> mRecordTypeVsCases = ASF_CaseDistributionBasedOnRT.getCaseByRecordType((List<Case>)newMap.values());
        if(mRecordTypeVsCases.containsKey(frameworkRTId)){
            Map<Id,Case> frameworkCases = new Map<Id,Case>(mRecordTypeVsCases.get(frameworkRTId));
            for(Case caseRec : frameworkCases.values()){
                if(caseRec.Business_Unit__c == ASF_Constants.ABSLI_BU){
                        mAbsliCases.put(caseRec.Id,caseRec);
                    }
            }
        }
        
        if(!mAbsliCases.isEmpty()){
            absliCasesAdditionalFields = new Map<Id, Case>([SELECT Id,Asset.Issue_Date__c,ABSLI_Case_Detail__c,CCC_External_Id__c, 
                                                            ABSLI_Case_Detail__r.To_date__c, ABSLI_Case_Detail__r.From_date__c,CaseNumber,ABSLI_Case_Detail__r.IRDAI_Token_Number__c,Nature__c,Stage__c,Technical_Source__c,
                                                            ABSLI_Case_Detail__r.Complaint_Category__c,ABSLI_Case_Detail__r.Resolve_case__c,IRDAI_Token_Number__c,IGMS_Complaint_Type_Code__c ,FTR__c,ABSLI_Case_Detail__r.IGMS_type_of_policy__c,ABSLI_Case_Detail__r.Before_3_PM__c,ABSLI_Case_Detail__r.Branch_Receive_Date__c
                                                            FROM Case 
                                                            WHERE Id IN :mAbsliCases.keySet()]);
            System.debug('Inside ABSLI before Update Trigger logic');
            System.debug(absliCasesAdditionalFields);
            //ABSLI_BeforeUpdateTriggerLogic.autoResolveFtrCases(mAbsliCases.values(), oldMap);
            ABSLI_BeforeUpdateTriggerLogic.validateFromDateToDate(mAbsliCases.values(), oldMap, newMap);
            ABSLI_BeforeUpdateTriggerLogic.validateTasks(mAbsliCases.values(), oldMap, newMap);
            ABSLI_BeforeUpdateTriggerLogic.checkIfMandatoryChecklistNotCompleted(mAbsliCases, oldMap);
            ABSLI_BeforeUpdateTriggerLogic.checkComplaintApplicability(newMap.values(), oldMap, newMap);
        }  
    }
    /**
* @description This method is called from ASF_CaseTriggerBUSpecificHandler whenever a case is
* updated. If the case is marked as FTR, the case status is updated to 'Resolved'
* @param absliCases
* @param oldMap

public static void autoResolveFtrCases(List<Case> absliCases, Map<Id, Case> oldMap){
if(!absliCases.isEmpty()){
for(Case caseRec : absliCases){
if(caseRec.MoveToNext__c != oldMap.get(caseRec.Id).MoveToNext__c 
&& caseRec.MoveToNext__c == true && caseRec.FTR__c == true){
caseRec.MoveToNext__c = false;
caseRec.Status = ASF_Constants.ONCREATECLOSESTATUS;
caseRec.Stage__c = ASF_Constants.ONCREATECLOSESTAGE;
}
}
}   
}*/
    
    /**
     * @description This method is called from ASF_CaseTriggerBUSpecificHandler whenever a case is
     * moved to next stage and skip to stage. It validates if any open checklist is pending and throws validation error
     * @param newMap
     * @param oldMap
     */
    public static void validateTasks(List<Case> absliCases, Map<Id, Case> oldMap, Map<Id, Case> newMap){
        Map<Id, Case> eligibleCases = new Map<Id, Case>();
        if(!absliCases.isEmpty()){
            for(Case caseRec : absliCases){
                if((caseRec.MoveToNext__c != oldMap.get(caseRec.Id).MoveToNext__c && caseRec.MoveToNext__c == true) 
                   || (caseRec.MoveToNext__c == oldMap.get(caseRec.Id).MoveToNext__c && caseRec.MoveToNext__c == false
                       && caseRec.CCC_External_Id__c == oldMap.get(caseRec.Id).CCC_External_Id__c
                       && caseRec.Reopened_DateTime__c == oldMap.get(caseRec.Id).Reopened_DateTime__c
                       && caseRec.Reject_Case__c == oldMap.get(caseRec.Id).Reject_Case__c
                       && caseRec.Is_Duplicate__c == oldMap.get(caseRec.Id).Is_Duplicate__c
                       && caseRec.Stage__c != oldMap.get(caseRec.Id).Stage__c
                       && caseRec.pending_clarification__c == false)){
                           
                           eligibleCases.put(caseRec.Id, caseRec);
                       }
            }
            Map<Id,AggregateResult> mCountOfNotCompletedTaskOnCase = new Map<Id,AggregateResult>(
                [SELECT WhatId Id, COUNT(ID) FROM Task 
                 WHERE Status NOT IN ('Completed','Rejected')
                 AND WhatId =: eligibleCases.keySet()
                 GROUP BY WhatId
                 HAVING COUNT(ID) > 0]);
            
            for(Case caseRec : eligibleCases.values()){
                Map<Id, Set<String>> skipperFlagMap = ASF_CaseTriggerModularHelper.getSkipperFlagMap();
                if(mCountOfNotCompletedTaskOnCase.containsKey(caseRec.Id) && 
                   !(skipperFlagMap.containsKey(caseRec.Id) && skipperFlagMap.get(caseRec.Id).contains(ASF_Constants.SKIP_VALIDATE_TASKS))){
                       Case caseError = newMap.get(caseRec.Id);
                       caseError.addError(System.Label.Incomplete_Tasks_Error_Message);
                       newMap.put(caseRec.Id,caseError);
                   }
            }
        }   
    }
    
    /**
* @description This method is called from ASF_CaseTriggerBUSpecificHandler whenever a case is
* updated. From Date and To Date Validation.
* @param absliCases
* @param oldMap
*/
    public static void validateFromDateToDate(List<Case> absliCases, Map<Id, Case> oldMap, Map<Id, Case> newMap){
        List<String> validSubTypes = new List<String>{'PEMT042', 'PEMT024'};
        List<String> validSubTypesBefore3PM = new List<String>{'PNFT042','PPAY001','PPAY008'};
                if(!absliCases.isEmpty()){
                    for (Case caseRec : absliCasesAdditionalFields.values()) {
                        System.debug(caseRec.ABSLI_Case_Detail__r.To_date__c);
                        System.debug(caseRec.ABSLI_Case_Detail__r.From_date__c);
                        // Check if the Case record is related to ABSLI business unit
                        if (caseRec.ABSLI_Case_Detail__c != null  && validSubTypes.contains(caseRec.CCC_External_Id__c)) {
                            System.debug('Inside validate date: ' + caseRec.Asset.Issue_Date__c);
                            Date issueDate = caseRec.Asset.Issue_Date__c;
                            Date toDate = caseRec.ABSLI_Case_Detail__r.To_date__c;
                            Date fromDate = caseRec.ABSLI_Case_Detail__r.From_date__c;
                            
                            // Validate dates
                            if (toDate < issueDate || fromDate < issueDate) {
                                // Add an error message to the Case record
                                Case caseError = newMap.get(caseRec.Id);
                                caseError.addError('To Date/From Date should be greater than or equal to the Policy Issued Date');
                                newMap.put(caseRec.Id,caseError);
                            }
                            if (fromDate > toDate) {
                                // Add an error message to the Case record
                                Case caseError = newMap.get(caseRec.Id);
                                caseError.addError('From Date should not be greater than To Date');
                                newMap.put(caseRec.Id,caseError);
                            }

                        }
                        //Validate before3PM scenario
                        if (caseRec.ABSLI_Case_Detail__c != null  && validSubTypesBefore3PM.contains(caseRec.CCC_External_Id__c) && caseRec.Stage__c == 'Open') {
                            Date today = Date.today();
                            String before3PM = caseRec.ABSLI_Case_Detail__r.Before_3_PM__c;
                            Date branchReceiveDate = caseRec.ABSLI_Case_Detail__r.Branch_Receive_Date__c;
                            Case caseError = newMap.get(caseRec.Id);
                            if(before3PM != null && branchReceiveDate != null){
                                switch on before3PM {
                                    when 'No' {
                                        Date expectedDate = today.addDays(1);
                                        if (branchReceiveDate != expectedDate) {
                                            caseError.addError('Branch received Date should be next day, if after 3PM');
                                        }
                                    }
                                    when 'Yes' {
                                        if (branchReceiveDate != today) {
                                            caseError.addError('Branch received Date should be Today, if before 3PM');
                                        }
                                    }
                                    when else {
                                        caseError.addError('Invalid value for Before 3 PM');
                                    }
                                }  
                            }
                        }
                   }  
                }
    }
    /**
* @description This method is called from ASF_CaseTriggerBUSpecificHandler whenever a case is
* updated. This marks case as Unresolved based on the checklist value for certain "Request" cases
* @param mAbsliCases
* @param oldMap
*/
	public static void checkIfMandatoryChecklistNotCompleted(Map<Id, Case> mAbsliCases, Map<Id, Case> oldMap){
        Map<Id, Case> eligibleCases = new Map<Id, Case>();
        if(mAbsliCases.keyset().size()>0){
            for(Case c : mAbsliCases.values()){
                System.debug('Dhin'+oldMap.get(c.Id).MoveToNext__c );
                System.debug('2'+c.MoveToNext__c);
                if(c.MoveToNext__c != oldMap.get(c.Id).MoveToNext__c && c.MoveToNext__c == true && c.Technical_Source__c != 'API' && c.Nature__c == 'Request'){
                    eligibleCases.put(c.Id, c);
                }
            }
        }
        // CHECK IF OPEN CHECKLIST.
        // IF COUNT OF RECORD IS > 0, SET REJECT_CASE__C to TRUE
        if(!eligibleCases.isEmpty()){
            Map<Id,AggregateResult> mCountOfNotCompletedChecklistOnCase = new Map<Id,AggregateResult>(
                [SELECT Case__c Id, COUNT(ID) FROM ASF_Checklist__c 
                 WHERE Status__c IN: ABSLI_Constants.CHECKLIST_FAILURE_STATUS
                                                      AND Case__c =: eligibleCases.keySet()
                                                      AND Mandatory__c = TRUE
                 GROUP BY Case__c
                 HAVING COUNT(ID) > 0]);
            for(Case c : eligibleCases.values()){
                if(mCountOfNotCompletedChecklistOnCase.containsKey(c.Id)){
                        c.Reject_Case__c = true;
                        c.Auto_Rejected__c = true;
                        c.MoveToNext__c = false;
                }
            }
        }              
    }
    
    /**
* @description This method is called from ASF_CaseTriggerBUSpecificHandler whenever a case is
* updated. To Restrict Complaint Category Type for Non-IGMS Complaints.
* @param absliCases
* @param oldMap
*/
    public static void checkComplaintApplicability(List<Case> absliCases, Map<Id, Case> oldMap, Map<Id, Case> newMap) {
        Set<String> externalIds = new Set<String>();
        for (Case caseRec : absliCasesAdditionalFields.values()) {
            if (caseRec.CCC_External_Id__c != null) {
                externalIds.add(caseRec.CCC_External_Id__c);
            }
        }
        
        // Query ASF_Case_Category_Config__c using the external IDs
        Map<String, ASF_Case_Category_Config__c> configMap = new Map<String, ASF_Case_Category_Config__c>();
        for (ASF_Case_Category_Config__c config : [SELECT Id, CCC_External_Id__c, IGMS_Code__c FROM ASF_Case_Category_Config__c WHERE CCC_External_Id__c IN :externalIds]) {
            configMap.put(config.CCC_External_Id__c, config);
        }
        Map<String,Map<String,Set<String>>> mClassificationIGMS = ABSLI_IGMSClassificationUtility.getIGMSClassification();
        for (Case caseRec : absliCasesAdditionalFields.values()) {
            if (caseRec.CCC_External_Id__c != null && configMap.containsKey(caseRec.CCC_External_Id__c)) {
                ASF_Case_Category_Config__c config = configMap.get(caseRec.CCC_External_Id__c);
                System.debug(config.IGMS_Code__c);
                System.debug(caseRec.ABSLI_Case_Detail__r.Resolve_case__c);
                System.debug(caseRec.ABSLI_Case_Detail__r.Complaint_Category__c);
                if (config.IGMS_Code__c == '#N/A' &&
                    caseRec.ABSLI_Case_Detail__r.Complaint_Category__c == 'Complaint' &&
                    caseRec.Nature__c == 'Complaint' && 
                    caseRec.Technical_Source__c != 'API') {
                        Case caseError = newMap.get(caseRec.Id);
                        caseError.addError('Category Type of "Complaint" is not applicable for Non-IGMS cases');
                        newMap.put(caseRec.Id,caseError);
                    }
                if (config.IGMS_Code__c != '#N/A' &&
                    caseRec.ABSLI_Case_Detail__r.Complaint_Category__c != 'Complaint' &&
                    caseRec.ABSLI_Case_Detail__r.IRDAI_Token_Number__c != null &&
                    caseRec.Nature__c == 'Complaint' && 
                    caseRec.Technical_Source__c != 'API') {
                        Case caseError = newMap.get(caseRec.Id);
                        caseError.addError('Category type cannot be changed for IGMS Synced cases');
                        newMap.put(caseRec.Id,caseError);
                    }
                if(caseRec.IGMS_Complaint_Type_Code__c != null &&
                   caseRec.Nature__c == 'Complaint' && 
                    caseRec.ABSLI_Case_Detail__r.IRDAI_Token_Number__c != null && 
                   caseRec.Technical_Source__c != 'API'){
                	ABSLI_IGMSClassificationUtility.validationWrapper returnWrapper= ABSLI_IGMSClassificationUtility.validateCurrentSelection(mClassificationIGMS, caseRec);
                	if(returnWrapper.bErrorOccured){
                           Case caseError = newMap.get(caseRec.Id);
                    	String errorMessage = returnWrapper.errorMessage;
                    	caseError.addError(errorMessage);
                       }
                       
                   }
            }
        }
    }
    
    public static void checkCreateCaseValidations(List<Case> absliCases, Map<Id, Case> oldMap){
        Set<String> issueCodes = new Set<String>();
        List<Case> validCases = new List<Case>();
        Map<Id,Asset> caseIdVsPolicy = new Map<Id,Asset>();
        Set<Id> policyIds = new Set<Id>();
        Id interactionRecTypeId = Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName().get('Interaction').getRecordTypeId();
        Id frameworkRecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName().get('Framework').getRecordTypeId();
        for(Case c: absliCases){
            if(c.Business_Unit__c=='ABSLI' && c.Technical_Source__c=='LWC' && c.RecordTypeId==frameworkRecordTypeId && 
               oldMap.get(c.Id).RecordTypeId == interactionRecTypeId && c.Preframework_to_Framework_FromUI__c == true){
                   issueCodes.add(c.CCC_External_Id__c);
                   validCases.add(c);
                   policyIds.add(c.AssetId);
               }
        }
        Map<Id, Asset> policyMap = new Map<Id, Asset>([SELECT Id, Status FROM Asset WHERE Id IN :policyIds]);
        for(Case c: validCases){
            if(policyMap.containsKey(c.AssetId)){
                caseIdVsPolicy.put(c.Id,policyMap.get(c.AssetId));
            }
        }
        if(issueCodes.size()>0 && !caseIdVsPolicy.isEmpty()){
            Map<String, ABSLI_Create_Case_Validations__mdt> issueCodeVsMdt = new Map<String, ABSLI_Create_Case_Validations__mdt>();
            List<ABSLI_Create_Case_Validations__mdt> validationMdtList = [SELECT Label,Business_Unit__c,Issue_Code__c,
                                                                          Operator__c,Asset_Values__c,Error_Message__c
                                                                          FROM ABSLI_Create_Case_Validations__mdt
                                                                          WHERE Business_Unit__c ='ABSLI'
                                                                          AND Issue_Code__c IN :issueCodes];
            for (ABSLI_Create_Case_Validations__mdt record : validationMdtList) {
                issueCodeVsMdt.put(record.Issue_Code__c, record);
            }
            
            for(Case cs: validCases){
                if(issueCodeVsMdt.containsKey(cs.CCC_External_Id__c) &&
                   issueCodeVsMdt.get(cs.CCC_External_Id__c).Business_Unit__c=='ABSLI')
                {
                    List<String> policyStatuses = issueCodeVsMdt.get(cs.CCC_External_Id__c).Asset_Values__c.split(':');
                    String oprtr = issueCodeVsMdt.get(cs.CCC_External_Id__c).Operator__c;
                    switch on oprtr{
                        when 'IN'{
                            if((caseIdVsPolicy.get(cs.Id).Status!=null) && (!policyStatuses.contains(caseIdVsPolicy.get(cs.Id).Status.replaceAll('\\s*,\\s*', ',')))){
                                cs.addError(issueCodeVsMdt.get(cs.CCC_External_Id__c).Error_Message__c);
                            }
                        }
                        when 'NOT IN'{
                            if((caseIdVsPolicy.get(cs.Id).Status!=null) && (policyStatuses.contains(caseIdVsPolicy.get(cs.Id).Status.replaceAll('\\s*,\\s*', ',')))){
                                cs.addError(issueCodeVsMdt.get(cs.CCC_External_Id__c).Error_Message__c);
                            }
                        }
                    }
                }
            }
            
        }
    }
    
    //custom exception class
    public class MyCustomException extends Exception {}
}