force-app/main/default/objects/ABSLI_Case_Detail__c/ABSLI_Case_Detail__c.object-meta.xml
<CustomObject>
    <description>This is extension object specific for ABSLI Business Unit.</description>
    <label>ABSLI Case Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABSLI Case Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABSLI_Case_Detail__c/fields/Status_Valid_For_STP__c.field-meta.xml
<CustomField>
    <fullName>Status_Valid_For_STP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used in conditional STP.</description>
    <label>Status Valid For STP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <description>This field is used to store PAN No.</description>
    <label>PAN No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN_Number__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number__c</fullName>
    <description>PAN Number</description>
    <label>PAN Number</label>
    <length>20</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Integration_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Ext_Id__c</fullName>
    <label>Integration Ext Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/ASF_Case_Stage_Config__c.object-meta.xml
<CustomObject>
    <label>Case Stage Config</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Stage Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Case_Category_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Category_Config__c</fullName>
    <label>Case Category Config</label>
    <referenceTo>ASF_Case_Category_Config__c</referenceTo>
    <relationshipLabel>Case Stage Configs</relationshipLabel>
    <relationshipName>Case_Stage_Configs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Query_Fields__c.field-meta.xml
<CustomField>
    <fullName>Query_Fields__c</fullName>
    <label>Query Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Integration__c/fields/Auto_Run_on_Load__c.field-meta.xml
<CustomField>
    <fullName>Auto_Run_on_Load__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Run on Load</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Case_Stage_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Stage_Config__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Stage Config</label>
    <referenceTo>ASF_Case_Stage_Config__c</referenceTo>
    <relationshipLabel>ASF Integrations</relationshipLabel>
    <relationshipName>ASF_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Mandatory_At_Stage_Movement__c.field-meta.xml
<CustomField>
    <fullName>Mandatory_At_Stage_Movement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory At Stage Movement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Query_Fields__c.field-meta.xml
<CustomField>
    <fullName>Query_Fields__c</fullName>
    <label>Query Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Run_Integration_From_LWC__c.field-meta.xml
<CustomField>
    <fullName>Run_Integration_From_LWC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to be set to True, if expectation is to run the integration for Technical_Source__c = LWC.</description>
    <label>Run Integration From LWC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_API_Identifier__c.field-meta.xml
<CustomField>
    <fullName>STP_API_Identifier__c</fullName>
    <description>This field is used to store identifier for STP API callouts.</description>
    <label>STP API Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_Config_External_Id__c.field-meta.xml
<CustomField>
    <fullName>STP_Config_External_Id__c</fullName>
    <description>This field is used to check if any child case needs to be created on closure of Case. Used in STP Flows</description>
    <label>STP Config External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_Processing_Class__c.field-meta.xml
<CustomField>
    <fullName>STP_Processing_Class__c</fullName>
    <label>STP Processing Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_Template__c.field-meta.xml
<CustomField>
    <fullName>STP_Template__c</fullName>
    <label>STP Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Populate</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>UI Card</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>UI Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/UI_Component__c.field-meta.xml
<CustomField>
    <fullName>UI_Component__c</fullName>
    <label>UI Component</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Visibility_Class__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Class__c</fullName>
    <label>Visibility Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/When_to_Appear__c.field-meta.xml
<CustomField>
    <fullName>When_to_Appear__c</fullName>
    <label>When to Appear</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage Entry</fullName>
            </value>
            <value>
                <fullName>During Stage</fullName>
            </value>
            <value>
                <fullName>Stage Exit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ABSLI_Case_Detail__c.field-meta.xml
<CustomField>
    <fullName>ABSLI_Case_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the ABSLI Case Detail record Id.</description>
    <label>ABSLI Case Detail</label>
    <referenceTo>ABSLI_Case_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is default true when contact is created.</description>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ABSLI_NSDLPANVerification.cls
public with sharing class ABSLI_NSDLPANVerification {

    @AuraEnabled(cacheable=true)
    public static PANVerificationWrapper getPanVerificationDetails(string caseId){
        try {
            PANVerificationWrapper panWrapper = new PANVerificationWrapper();

            Case caseRecord = [Select id,AccountId,ABSLI_Case_Detail__r.Status_Valid_For_STP__c,Account.Name,
                               Account.IsPersonAccount,Account.PAN__c,Account.PersonBirthdate,ABSLI_Case_Detail__r.PAN_Number__c	
                               from Case where id =: caseId limit 1];
            
            if(caseRecord.Account.IsPersonAccount){
                panWrapper.name = caseRecord.Account.Name;
                String panFromCaseExt = caseRecord.ABSLI_Case_Detail__r.PAN_Number__c;
                panWrapper.pan = panFromCaseExt != null  && panFromCaseExt != '' ? panFromCaseExt : '';
                panWrapper.dob = caseRecord.Account.PersonBirthdate;
                panWrapper.panValidationStatus = caseRecord.ABSLI_Case_Detail__r.Status_Valid_For_STP__c;
                panWrapper.caseExtId = caseRecord.ABSLI_Case_Detail__c;
            }else{
                List<Contact> contactRecord = [Select id,Name,Birthdate,Account.PAN__c from Contact where Primary__c = true and AccountId = :caseRecord.AccountId limit 1];
                if(contactRecord.size() > 0){
                    panWrapper.name = contactRecord[0].Name;
                    //panWrapper.pan = caseRecord.Account.PAN__c;
                    panWrapper.dob = contactRecord[0].Birthdate; 
                    panWrapper.panValidationStatus = caseRecord.ABSLI_Case_Detail__r.Status_Valid_For_STP__c;   
                    panWrapper.caseExtId = caseRecord.ABSLI_Case_Detail__c;
                }
            }

            return panWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void updateSTPFlagOnCaseDetail(String caseExtId, boolean flagVal){
        ABSLI_Case_Detail__c caseExtRec = new ABSLI_Case_Detail__c(Id = caseExtId);
        caseExtRec.Status_Valid_For_STP__c = flagVal;
        update caseExtRec;
    }
    
    @AuraEnabled
    public static PANVerificationResponseWrapper verifyPANDetails(String panInputWrapperStr, String caseId){
        try {
            PANVerificationResponseWrapper panResponseWrapper = new PANVerificationResponseWrapper();
            panResponseWrapper.isSuccess = false;
            PANRequestWrapper panRequest = new PANRequestWrapper();
            PANInputWrapper panInputWrapper = (PANInputWrapper)JSON.deserialize(panInputWrapperStr,PANInputWrapper.class);
            panRequest.SOURCE = System.label.ABSLI_ESB_SOURCE_VAL;
            Date dob = Date.valueof(panInputWrapper.dob);
            DateTime dobDateTime = DateTime.newInstance(dob.year(), dob.month(),dob.day());
            panInputWrapper.dob =  dobDateTime.Format('dd/MM/yyyy');
            panInputWrapper.fathername = '';
            panRequest.inputData = new List<PANInputWrapper>{panInputWrapper};
            ABCL_IntegrationCallout.IntegrationResponseWrapper nsdlResponse = ABCL_IntegrationCallout.executeCallout(ABSLI_Constants.PAN_VERIFICATION_INTEGRATION_METADATA,
                                                                                                                    JSON.serialize(panRequest),
                                                                                                                    null);
            if(String.isNotBlank(nsdlResponse.responseBody)){
                PANResponseWrapper responseWrapper = (PANResponseWrapper)JSON.deserialize(nsdlResponse.responseBody,PANResponseWrapper.class);
                if(nsdlResponse.statusCode == 200){
                    panResponseWrapper.isSuccess = true;
                    panResponseWrapper.responseStr = nsdlResponse.responseBody;
                }else {
                    if(responseWrapper.Fault != null && responseWrapper.Fault.FaultMessage != null){
                        panResponseWrapper.errorMessage = responseWrapper.Fault.FaultMessage.resposne_Message;
                    }
                    else{
                       panResponseWrapper.errorMessage = 'Opps! Something went wrong at API Layer'; 
                    }
                }
            }
            string status = '';
            if(panResponseWrapper.isSuccess){
                status = ABHFL_Constants.SUCCESS;
            }else{
                status = ABHFL_Constants.FAILURE;
            }

            ABCL_IntegrationCommonUtility.caseIntegrationLogger(caseId,
                JSON.serialize(panRequest),
                nsdlResponse.responseBody,
                /*intExtId*/'',
                status);

            return panResponseWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static PANVerificationResponseWrapper verifyPAN(String panInputWrapperStr, String caseId, String intExtId){
        try {

            /*List<ASF_Case_Integration__c> caseInt =  [SELECT Id, Status__c, Case__c, Integration_Ext_Id__c 
                                                      FROM ASF_Case_Integration__c WHERE Case__c =:caseId 
                                                      AND Integration_Ext_Id__c  =:intExtId];
                                                
            if(caseInt.size()>0){
                for(ASF_Case_Integration__c caseInteg : caseInt){
                    caseInteg.Status__c = ABSLI_Constants.CANCELED;
                }
                if(Schema.sObjectType.ASF_Case_Integration__c.isCreateable()){
                    update caseInt;
                }
            }               */                    

            PANVerificationResponseWrapper panResponseWrapper = new PANVerificationResponseWrapper();
            panResponseWrapper.isSuccess = false;
            PANRequestWrapper panRequest = new PANRequestWrapper();
            PANInputWrapper panInputWrapper = (PANInputWrapper)JSON.deserialize(panInputWrapperStr,PANInputWrapper.class);
            panRequest.SOURCE = System.label.ABSLI_ESB_SOURCE_VAL;
            Date dob = Date.valueof(panInputWrapper.dob);
            DateTime dobDateTime = DateTime.newInstance(dob.year(), dob.month(),dob.day());
            panInputWrapper.dob =  dobDateTime.Format('dd/MM/yyyy');
            panInputWrapper.fathername = '';
            panRequest.inputData = new List<PANInputWrapper>{panInputWrapper};
            ABCL_IntegrationCallout.IntegrationResponseWrapper nsdlResponse = ABCL_IntegrationCallout.executeCallout(ABSLI_Constants.PAN_VERIFICATION_INTEGRATION_METADATA,
                                                                                                                    JSON.serialize(panRequest),
                                                                                                                    null);
            if(String.isNotBlank(nsdlResponse.responseBody)){
                PANResponseWrapper responseWrapper = (PANResponseWrapper)JSON.deserialize(nsdlResponse.responseBody,PANResponseWrapper.class);
                if(nsdlResponse.statusCode == 200){
                    Case caseRecord = [Select ABSLI_Case_Detail__c from Case where id =: caseId limit 1];
                    ABSLI_Case_Detail__c caseDetail = new ABSLI_Case_Detail__c();
                    caseDetail.Id = caseRecord.ABSLI_Case_Detail__c;
                    caseDetail.Status_Valid_For_STP__c = true;
                    if(Schema.sObjectType.ABSLI_Case_Detail__c.isUpdateable()){
                        update caseDetail;
                    }
                    panResponseWrapper.isSuccess = true;
                    panResponseWrapper.responseStr = nsdlResponse.responseBody;
                }else {
                    if(responseWrapper.Fault != null && responseWrapper.Fault.FaultMessage != null){
                        panResponseWrapper.errorMessage = responseWrapper.Fault.FaultMessage.resposne_Message;
                    }
                }
            }
            string status = '';
            if(panResponseWrapper.isSuccess){
                status = ABHFL_Constants.SUCCESS;
            }else{
                status = ABHFL_Constants.FAILURE;
            }

            ABCL_IntegrationCommonUtility.caseIntegrationLogger(caseId,
                                                                JSON.serialize(panRequest),
                                                                nsdlResponse.responseBody,
                                                                intExtId,
                                                                status);
            return panResponseWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static PANVerificationResponseWrapper updatePAN(string caseId){
        try {
            PANVerificationResponseWrapper responseWrapper = new PANVerificationResponseWrapper();
            responseWrapper.isSuccess = true;
            Case caseRecord = [Select ABSLI_Case_Detail__c,CCC_External_Id__c from Case where id =: caseId limit 1];
            ABSLI_PanUpdateIntegration panUpdateInt = new ABSLI_PanUpdateIntegration();
            ABSLI_Case_Detail__c caseDetail = new ABSLI_Case_Detail__c();
            caseDetail.Id = caseRecord.ABSLI_Case_Detail__c;
            caseDetail.Status_Valid_For_STP__c = true;
            if(Schema.sObjectType.ABSLI_Case_Detail__c.isUpdateable()){
                update caseDetail;
            }
            //ASF_IntegrationsController.IntegrationWrapper evaluationResponseWrapper = panUpdateInt.evaluate(caseRecord);
            //if(evaluationResponseWrapper.status == ABSLI_Constants.SUCCESS){
            /*    List<ASF_Integration__c> integrationSpec = [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, 
                                                      LastModifiedDate, LastModifiedById, SystemModstamp, Auto_Run_on_Load__c, 
                                                      Case_Stage_Config__c, Display_Name__c, Display_Order__c, External_Id__c, 
                                                      Mandatory_At_Stage_Movement__c, Processing_Class__c, STP_Processing_Class__c, 
                                                      Type__c, UI_Component__c, Visibility_Class__c, When_to_Appear__c, C3ExternalId__c, 
                                                      Query_Fields__c, STP_API_Identifier__c, STP_Config_External_Id__c, STP_Template__c, 
                                                      Priority__c, Run_Integration_From_LWC__c 
                                                      FROM ASF_Integration__c 
                                                      where Processing_Class__c = 'ABSLI_PanUpdateIntegration'
                                                      AND Case_Stage_Config__r.Case_Category_Config__r.CCC_External_Id__c =: caseRecord.CCC_External_Id__c limit 1];
            if(integrationSpec.size() > 0){
                ASF_IntegrationsController.IntegrationWrapper intResponse = ASF_IntegrationsController.runIntegration(integrationSpec[0],caseRecord);                                                     
                if(intResponse.status == ABSLI_Constants.SUCCESS){
                    responseWrapper.isSuccess = true;
                }else{
                    responseWrapper.errorMessage = intResponse.response;
                }               
            }*/

                /*ASF_IntegrationsController.IntegrationWrapper runResponseWrapper = panUpdateInt.run(integrationSpec,caseRecord);
                if(runResponseWrapper.status == ABSLI_Constants.SUCCESS){
                    responseWrapper.isSuccess = true;
                } else {
                    responseWrapper.errorMessage = runResponseWrapper.response;
                }
            }else{
                responseWrapper.errorMessage = evaluationResponseWrapper.response;
            }*/
            return responseWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    public class PANVerificationWrapper{
        @AuraEnabled
        public string name;
        @AuraEnabled
        public string pan;
        @AuraEnabled
        public Date dob;
        @AuraEnabled
        public Boolean panValidationStatus;
        @AuraEnabled
        public string caseExtId;
    }

    public class PANRequestWrapper{
        public String SOURCE;
        public PANInputWrapper[] inputData;
    }

    public class PANInputWrapper{
        public string name;
        public string pan;
        public string dob;
        public string fathername;
    }

    public class PANResponseWrapper{
        public String response_Code;
        public PANOutputWrapper[] outputData;
        public FaultWrapper Fault;
        public String resposne_Message;
    }

    public class PANOutputWrapper {
        public String pan;
        public String pan_status;
        public String name;
        public String fathername;
        public String dob;
        public String seeding_status;
    }

    public class PANErrorResponseWrapper{
        public FaultWrapper Fault;
    }

    class FaultWrapper {
        public String FaultCode;
        public FaultMessageWrapper FaultMessage;
    }

    public class FaultMessageWrapper {
        public String response_Code;
        public String resposne_Message;
    }

    public class PANVerificationResponseWrapper{
        @AuraEnabled
        public String errorMessage;
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String responseStr;
    }
}