force-app/main/default/objects/Lead/fields/ABHFL_Prospect_Type__c.field-meta.xml
<CustomField>
    <fullName>ABHFL_Prospect_Type__c</fullName>
    <label>Prospect Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Non Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/API_Response_Message__c.field-meta.xml
<CustomField>
    <fullName>API_Response_Message__c</fullName>
    <label>API Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Create_Lead_To_CRM_Status__c.field-meta.xml
<CustomField>
    <fullName>Create_Lead_To_CRM_Status__c</fullName>
    <label>Create Lead To CRM Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Distributer_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributer_Name__c</fullName>
    <label>Distributer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>SENP</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/External_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Lead_ID__c</fullName>
    <displayFormat>SFL-{000000000}</displayFormat>
    <externalId>true</externalId>
    <label>External Lead ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PANNO__c.field-meta.xml
<CustomField>
    <fullName>PANNO__c</fullName>
    <label>PANNO</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Preferred_Communication__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Communication__c</fullName>
    <label>Preferred Communication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COMMERCIAL PROPERTY PURCHASE_AHF</fullName>
            </value>
            <value>
                <fullName>CPP_PRIME</fullName>
            </value>
            <value>
                <fullName>HOME LOAN</fullName>
            </value>
            <value>
                <fullName>HOME LOAN_AHF</fullName>
            </value>
            <value>
                <fullName>HOME LOAN_INFORMAL</fullName>
            </value>
            <value>
                <fullName>HOME LOAN_PLUS</fullName>
            </value>
            <value>
                <fullName>LAP_AHF</fullName>
            </value>
            <value>
                <fullName>LEASE RENTAL DISCOUNTING</fullName>
            </value>
            <value>
                <fullName>LEASE RENTAL DISCOUNTING_INST</fullName>
            </value>
            <value>
                <fullName>LOAN AGAINST PROPERTY</fullName>
            </value>
            <value>
                <fullName>LOAN AGAINST PROPERTY_INFORMAL</fullName>
            </value>
            <value>
                <fullName>MICRO CONSTRUCTION FINANCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Prospect_Type__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Type__c</fullName>
    <defaultValue>&quot;Service&quot;</defaultValue>
    <label>Lead Prospect Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Requested_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Loan_Amount__c</fullName>
    <label>Requested Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_System_API__c.field-meta.xml
<CustomField>
    <fullName>Source_System_API__c</fullName>
    <label>Source System API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sourcing_Branch__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Branch__c</fullName>
    <label>Sourcing Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SPOC_Name__c.field-meta.xml
<CustomField>
    <fullName>SPOC_Name__c</fullName>
    <label>SPOC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Sub_Source__c</fullName>
    <label>Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Walk-in</fullName>
            </value>
            <value>
                <fullName>Cross Sell</fullName>
            </value>
            <value>
                <fullName>Phone Inbound</fullName>
            </value>
            <value>
                <fullName>Phone Outbound</fullName>
            </value>
            <value>
                <fullName>Asset Service Desk</fullName>
            </value>
            <value>
                <fullName>Customer Contact Centre</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Grievance Desk</fullName>
            </value>
            <value>
                <fullName>Customer Retention</fullName>
            </value>
            <value>
                <fullName>CIBIL Data</fullName>
            </value>
            <value>
                <fullName>Strategic Partnership</fullName>
            </value>
            <value>
                <fullName>Proactive</fullName>
            </value>
            <value>
                <fullName>Promoter Calling</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sub_Variant__c.field-meta.xml
<CustomField>
    <fullName>Sub_Variant__c</fullName>
    <label>Sub Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>BT+ Top Up</fullName>
            </value>
            <value>
                <fullName>BT - AFFORDABLE REFINANCE</fullName>
            </value>
            <value>
                <fullName>BT APPROVED FI</fullName>
            </value>
            <value>
                <fullName>BT NON-APPROVED FI</fullName>
            </value>
            <value>
                <fullName>BT - REGULAR REFINANCE</fullName>
            </value>
            <value>
                <fullName>GECL</fullName>
            </value>
            <value>
                <fullName>GENERAL PURPOSE LOAN</fullName>
            </value>
            <value>
                <fullName>INSURANCE</fullName>
            </value>
            <value>
                <fullName>LAPBT</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>NEW - AFFORDABLE REFINANCE</fullName>
            </value>
            <value>
                <fullName>NEW - REGULAR REFINANCE</fullName>
            </value>
            <value>
                <fullName>PNI</fullName>
            </value>
            <value>
                <fullName>PRE APPROVED TOP UP</fullName>
            </value>
            <value>
                <fullName>TOP UP (BT+NEW)</fullName>
            </value>
            <value>
                <fullName>TOPUP(NEW)</fullName>
            </value>
            <value>
                <fullName>TOP UP (NEW)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABHFL_LeadCreationAPI.cls
/*********************************************************
*Class        :  ABHFL_LeadCreationAPI 
*Author       :  Vishal Gangwar
*Created Date :  25/01/2024
*Last Modified:  
*Description  :  Sending Lead To External Lead Management System
*********************************************************/

public with sharing class ABHFL_LeadCreationAPI {
    
    /****************************************************************************************************************
    * @LOB - ABHFL
    * @Function - sendLead
    * @param leadId - Lead Id getting from abhfl_SendLeadToCRM Lwc Component.
    * @return - string
    * @description - Invoked from the abhfl_SendLeadToCRM Lwc components to send lead to External Lead management system
    *****************************************************************************************************************/
    @auraEnabled
    public static string sendLead(Id leadId){
        String message; 
        Lead leadObj = [SELECT Id, Company, Email, FirstName, LastName, Employment_Type__c, External_Lead_ID__c, ABHFL_Prospect_Type__c,
                                   MobilePhone, PANNO__c, Preferred_Communication__c, Product__c, Prospect_Type__c,API_Response_Message__c,
                                   RecordType.Name, Requested_Loan_Amount__c, Source_System_API__c, Source_Type__c,Create_Lead_To_CRM_Status__c,
                                   LeadSource, Sourcing_Branch__c, Sub_Source__c, Sub_Variant__c, Variant__c, SPOC_Name__c
                            FROM Lead WHERE Id =: leadId WITH SECURITY_ENFORCED];
            
            If(leadObj != null && checkConditions(leadObj)){
               // Create a PayloadWrapper instance and map the Lead fields
                PayloadWrapper payloadWrp = new PayloadWrapper(leadObj);
                String payload = JSON.serialize(payloadWrp);
                
                system.debug('Payload==='+payload);
                
                ResponseWrapper responseWrapperObj = new ResponseWrapper();
                ABCL_IntegrationCallout.IntegrationResponseWrapper leadCreationWrp = ABCL_IntegrationCallout.executeCallout(ABHFL_Constants.SEND_LEAD_TO_CRM,payload,null);
                responseWrapperObj = responseWrapperObj.parse(leadCreationWrp.responseBody);
                if(responseWrapperObj.StatusCode == '200'){
                    leadObj.API_Response_Message__c = responseWrapperObj.Message;
                    leadObj.Create_Lead_To_CRM_Status__c = 'Success';
                    message = 'Send Lead to CRM is Successful';
                }else{
                    message = responseWrapperObj.Message;
                    leadObj.API_Response_Message__c = responseWrapperObj.Message;
                    leadObj.Create_Lead_To_CRM_Status__c = responseWrapperObj.status;
                    throw new AuraHandledException(message);
                }
            }else{
                message = 'Required fields are missing';
                throw new AuraHandledException(message);
            }
            
        return message;
    }
    
    private static boolean checkConditions(Lead leadObj){
        if(leadObj.Product__c == null || leadObj.ABHFL_Prospect_Type__c == null || leadObj.LeadSource == null || 
           leadObj.LeadSource == null || leadObj.Sub_Source__c == null || leadObj.MobilePhone == null || 
           leadObj.Employment_Type__c == null || leadObj.Sourcing_Branch__c == null || leadObj.Requested_Loan_Amount__c == null){
               return false;
        }
        
        if(leadObj.ABHFL_Prospect_Type__c == 'Individual'){
            if(leadObj.FirstName == null || leadObj.LastName == null){
                return false;
            }
        }
        
        if(leadObj.ABHFL_Prospect_Type__c == 'Non Individual'){
            if(leadObj.Company == null || leadObj.SPOC_Name__c == null){
                return false;
            }
        }
        
        return true;
    }
    
    public class PayloadWrapper {
        public String companyName;
        //public String email;
        public String employmentType;
        public String externalLeadID;
        public String firstName;
        public String lastName;
        public String mobile;
        //public String panNo;
        public String preferredCommunication;
        public String product;
        public String prospectType;
        public Decimal requestedLoanAmount;
        public String sourceSystemAPI;
        public String sourceType;
        public String source;
        public String sourcingBranch;
        public String subSource;
        //public String subVariant;
        //public String variant;
        //public String recordType;
        //public string distributerName;
        public string spocName;
    
        // Constructor to map Lead fields to PayloadWrapper fields
        public PayloadWrapper(Lead leadObj) {
            this.companyName = leadObj.Company;
            //this.email = leadObj.Email;
            this.employmentType = leadObj.Employment_Type__c;
            this.externalLeadID = leadObj.External_Lead_ID__c;
            this.firstName = leadObj.FirstName;
            this.lastName = leadObj.LastName;
            this.mobile = leadObj.MobilePhone;
            //this.panNo = leadObj.PANNO__c;
            this.preferredCommunication = 'SMS,Email';
            this.product = leadObj.Product__c;
            this.prospectType = leadObj.ABHFL_Prospect_Type__c;
            this.requestedLoanAmount = leadObj.Requested_Loan_Amount__c;
            this.sourceSystemAPI = 'SFDC';
            this.sourceType = 'Internal';
            this.source = leadObj.LeadSource;
            this.sourcingBranch = leadObj.Sourcing_Branch__c;
            this.subSource = leadObj.Sub_Source__c;
            //this.subVariant = leadObj.Sub_Variant__c;
            //this.variant = leadObj.Variant__c;
            //this.recordType = leadObj.RecordType.Name;
            //this.distributerName = leadObj.Distributer_Name__c;
            this.spocName = leadObj.SPOC_Name__c;
        }
    }
    
    public class ResponseWrapper{
        public String statusCode;
        public String status;
        public String message;
        
        public ResponseWrapper parse(String json) {
            return (ResponseWrapper) System.JSON.deserialize(json, ResponseWrapper.class);
        }
    }
}