force-app/main/default/objects/ABCL_Observability__e/ABCL_Observability__e.object-meta.xml
<CustomObject>
    <label>ABCL Observability</label>
    <pluralLabel>ABCL Observabilitys</pluralLabel>
</CustomObject>

force-app/main/default/objects/ABCL_Observability__e/fields/Event_Details__c.field-meta.xml
<CustomField>
    <fullName>Event_Details__c</fullName>
    <label>Event Details</label>
    <length>131050</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Retry_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempt__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Virendra - Initial value is 0, and incremented on subsequent retries.</description>
    <label>Retry Attempt</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LAN__c.field-meta.xml
<CustomField>
    <fullName>LAN__c</fullName>
    <label>LAN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>This field will get LOB value from related Asset or Account.</description>
    <formula>IF( ISBLANK( AssetId ) || ISBlank(TEXT(Asset.LOB__c )) , Text( Account.Line_of_Business__c ),  TEXT(Asset.LOB__c ))</formula>
    <label>LOB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sent_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anywhere Service</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Bulk Upload from HO</fullName>
            </value>
            <value>
                <fullName>CAMS FO</fullName>
            </value>
            <value>
                <fullName>Deadline</fullName>
            </value>
            <value>
                <fullName>EMT CNX</fullName>
            </value>
            <value>
                <fullName>EMT HO</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>HO Back office</fullName>
            </value>
            <value>
                <fullName>IGMS</fullName>
            </value>
            <value>
                <fullName>Inbound ABC</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
            </value>
            <value>
                <fullName>Inbound CNX</fullName>
            </value>
            <value>
                <fullName>Inbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>Insurance Repositary website</fullName>
            </value>
            <value>
                <fullName>Insurance Repository</fullName>
            </value>
            <value>
                <fullName>Letters and Faxes</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>Outbound Altruist</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Outbound CNX</fullName>
            </value>
            <value>
                <fullName>Outbound ConnectQ</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Website Redressal</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>IVR Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Text__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_Text__c.field-meta.xml
<CustomField>
    <fullName>Type_Text__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ABCL_ObservabilityBatch.cls
/**
 * @description       : 
 * @author            : nikhil.dhoke@in.ey.com
 * @group             : 
 * @last modified on  : 12-06-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class ABCL_ObservabilityBatch implements Database.Batchable<sObject>,Database.Stateful{

    global ABCL_ObservabilityWrapper observWrapper = new ABCL_ObservabilityWrapper();

	global Database.QueryLocator start(Database.BatchableContext BC) {
        DateTime dt = System.Now().addHours(-1);
        List<String> typeList = new List<String>{'Ebot'};
        List<String> sourceList = new List<String>{'Email'};
        String subType = '';
        String query = 'SELECT Id, Sent_To_Ebot__c, CaseNumber, Nature__c, Type_Text__c, Sub_Type_Text__c, LOB__c, CreatedDate, Status, Origin, Source__c, CCC_External_Id__c, SuppliedEmail , Business_Unit__c, RecordType.Name, LAN__c, isClosed, (Select id, Status__c, Response__c, Type__c, Retry_Attempt__c, CreatedDate  from ASF_Case_Integrations__r Where Type__c IN:typeList) from Case Where Source__c IN:sourceList AND CreatedDate >=:dt Order By CreatedDate desc';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        // Process each batch of records
        List<Case> caseList = new List<Case>();
        Integer successCount = 0;
        Integer notSentToEbotCount = 0;
        ABCL_ObservabilityWrapper.CaseDetailsWrapper caseDetails = new ABCL_ObservabilityWrapper.CaseDetailsWrapper();
        List<ABCL_ObservabilityWrapper.CaseDetailsWrapper> caseDetailsList = new List<ABCL_ObservabilityWrapper.CaseDetailsWrapper>();
        Map<String,List<ASF_Case_Integration__c>> caseIntegrationMap = new Map<String,List<ASF_Case_Integration__c>>();
        //List<String> stringList = new List<String>();
        try {
            if(scope.size()>0){
                observWrapper.totalCases += scope.size();
                for (Case cs : (List<Case>)scope) {
                    if(cs.Status == 'Resolved'){
                        successCount ++; 
                    }
                    else if(cs.Sent_To_Ebot__c == false){
                        notSentToEbotCount ++; 
                    }
                    else if(cs.isClosed == false && cs.Sub_Type_Text__c == '' && cs.ASF_Case_Integrations__r.size()>0){
                        /* if(caseIntegrationMap.containsKey(cs.Id)){
                            caseIntegrationMap.get(cs.Id).addAll(cs.ASF_Case_Integrations__r);
                        }
                        else{
                            caseIntegrationMap.put(cs.Id,cs.ASF_Case_Integrations__r);
                        } */
                        /* Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(cs.ASF_Case_Integrations__r[0].Response__c);
                        String comment = (String)result.get('COMMENT'); */
                        caseDetails.caseNumber = cs.CaseNumber; 
                        caseDetails.lineOfBusiness = cs.LOB__c; 
                        caseDetails.businessUnit = cs.Business_Unit__c;
                        caseDetails.retryAttempt = cs.ASF_Case_Integrations__r[0].Retry_Attempt__c; 
                        caseDetails.caseType = cs.Type_Text__c; 
                        caseDetails.caseSubType = cs.Sub_Type_Text__c; 
                        caseDetails.lan = cs.LAN__c; 
                        caseDetails.status = cs.Status; 
                        caseDetails.source = cs.Source__c; 
                        caseDetails.type = 'Ebot'; 
                        caseDetails.message = ''; 
                        caseDetails.description = cs.ASF_Case_Integrations__r[0].Response__c; //comment; 
                        caseDetails.caseCreatedDate = string.valueOf(cs.CreatedDate); 
                        caseDetails.requestDate = string.valueOf(cs.ASF_Case_Integrations__r[0].CreatedDate);

                        caseDetailsList.add(caseDetails);
                    }
                }
                observWrapper.integrationType = 'Ebot';
                observWrapper.casesNotSentToIntegration += notSentToEbotCount;
                observWrapper.successfullCases += successCount;
                observWrapper.caseDetailsList.addAll(caseDetailsList);
                /* if(caseIntegrationMap.size()>0){

                } */
            }
            
        } catch(Exception e) {
            System.debug('ABCL_ObservabilityBatch execute error - '+ e.getMessage());
        }
    }

    global void finish(Database.BatchableContext BC) {
        //System.debug('List count nik - '+ stringList.size());
        // Publish a platform event after processing all batches
        ABCL_Observability__e event = new ABCL_Observability__e(
            Event_Details__c = JSON.serialize(observWrapper)
        );
        //EventBus.publish(event);
        Database.SaveResult sr = EventBus.publish(event);
        // Inspect publishing result
        if (sr.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
            for(Database.Error err : sr.getErrors()) {
                System.debug('Error returned: ' +err.getStatusCode() +' - ' +err.getMessage());
            }
        }
    }
}