force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Integration_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Ext_Id__c</fullName>
    <label>Integration Ext Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Is_Validation_Success__c.field-meta.xml
<CustomField>
    <fullName>Is_Validation_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Validation Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Rule__c/ASF_Case_Rule__c.object-meta.xml
<CustomObject>
    <label>Case Rule</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Rule__c/fields/Assigned_Error_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Error_Queue_Id__c</fullName>
    <label>Assigned Error Queue Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Rule__c/fields/Assigned_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Queue_Id__c</fullName>
    <label>Assigned Queue Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Rule__c/fields/Case_Stage_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Stage_Config__c</fullName>
    <label>Case Stage Config</label>
    <referenceTo>ASF_Case_Stage_Config__c</referenceTo>
    <relationshipLabel>Case Rules</relationshipLabel>
    <relationshipName>Case_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Checklists</fullName>
            </value>
            <value>
                <fullName>SLA Override</fullName>
            </value>
            <value>
                <fullName>Stage Movement</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/ASF_Case_Stage_Config__c.object-meta.xml
<CustomObject>
    <label>Case Stage Config</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Stage Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Case_Category_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Category_Config__c</fullName>
    <label>Case Category Config</label>
    <referenceTo>ASF_Case_Category_Config__c</referenceTo>
    <relationshipLabel>Case Stage Configs</relationshipLabel>
    <relationshipName>Case_Stage_Configs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Default_Error_Queue__c.field-meta.xml
<CustomField>
    <fullName>Default_Error_Queue__c</fullName>
    <label>Default Error Queue</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Default_Queue__c.field-meta.xml
<CustomField>
    <fullName>Default_Queue__c</fullName>
    <label>Default Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Gateway_Stage__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Stage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gateway Stage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Optional_Stage__c.field-meta.xml
<CustomField>
    <fullName>Optional_Stage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Optional Stage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <label>Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MoveToNext__c.field-meta.xml
<CustomField>
    <fullName>MoveToNext__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MoveToNext</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Pending_Clarification__c.field-meta.xml
<CustomField>
    <fullName>Pending_Clarification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Clarification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/SLA_Threshold_Warning__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>When you change this setting , please note that existing Cases needs to be reedited for new changes to come in.</description>
    <label>SLA Threshold Warning</label>
</CustomObject>

force-app/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Team Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ASF_CaseMovementHelper_Test.cls
@isTest
public class ASF_CaseMovementHelper_Test {
    
    private final static Profile SYSTEMADMIN_PROFILE = [SELECT Id FROM Profile WHERE name='System Administrator' LIMIT 1];
    @testSetup
    static void setUpData(){
        ASF_TestDataFactory.createCaseRecords(1);
        ASF_TestDataFactory.createCaseCategoryConfig();
        List<sObject> ls = Test.loadData(SLA_Threshold_Warning__c.sObjectType, 'testSLAThreshold');
        ASF_TestDataFactory.createC3IntegrationsAndCase();
        //ASF_TestDataFactory.createC3WithPrePopulateIntegrations();
    }
    
    @isTest
    private static void moveToNextStageTest() {
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1]; 
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_02');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_02' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;
        
        Test.startTest();
        ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        Test.stopTest();

        Assert.areEqual('Success', StageMovementResult.status);  
        Assert.areNotEqual(caseRecord.Stage__c, StageMovementResult.nextStageConfig.StageName__c, 'Case moved to Next Stage');  
    }
    
    @isTest
    private static void moveToOptionalStageTest() {
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1];           
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_02');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_02' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;
        
        ASF_Case_Stage_Config__c configRec = [select Id, Optional_Stage__c, StageName__c from ASF_Case_Stage_Config__c where StageName__c= 'In Progress with Recovery' LIMIT 1];
        configRec.Optional_Stage__c = true;
        update configRec;
        
        Test.startTest();
        ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        Test.stopTest();
        Assert.areEqual('Success', StageMovementResult.status);   
        Assert.areNotEqual(caseRecord.Stage__c, StageMovementResult.nextStageConfig.StageName__c, 'Case moved to Next Stage');
    }
    
    // @isTest
    // private static void moveToNextStageTestNegative() {
        
    //     Test.startTest();
    //     ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToNextStage('5005g00000099h1');
    //     ASF_CaseMovementHelper.StageWrapper FrwdMovementResult = ASF_CaseMovementHelper.moveToForwardStage('5005g00000099h1','In Progress with Recovery');
    //     ASF_CaseMovementHelper.StageWrapper BackMovementResult = ASF_CaseMovementHelper.moveToBackwardStage('5005g00000099h1','Closed');
        
    //     Test.stopTest();
    //     Assert.areEqual('Error', StageMovementResult.status);  
    // }

    @isTest
    private static void moveToNextStageIntegrationNegative() {
        
        Case caseRecord = [
                                SELECT Id, CCC_External_Id__c, Stage__c, pending_clarification__c 
                                FROM case 
                                WHERE CCC_External_Id__c = 'CCC-CC-CCLTD-05'];            

        Test.startTest();
        
        ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        system.debug(StageMovementResult);

        caseRecord.MoveToNext__c = true;
        Database.SaveResult sResult = Database.update(caseRecord, false);

        Test.stopTest();
        Assert.isFalse(sResult.isSuccess()); 
        Assert.areEqual(StageMovementResult.errorMessage, sResult.getErrors()[0].getMessage(), 'Error Returned from the Integration Validation should match');
    }

    @isTest
    private static void moveToNextStageApexClass() {
        
        Case caseRecord = [
                                SELECT Id, CCC_External_Id__c, Stage__c, pending_clarification__c 
                                FROM case 
                                WHERE CCC_External_Id__c = 'CCC-CC-CCLTD-05'];            
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_02');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_02' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;

        Test.startTest();
        
        ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        system.debug(StageMovementResult);

        caseRecord.MoveToNext__c = true;
        update caseRecord;

        caseRecord = [
                        SELECT Id, CCC_External_Id__c, Stage__c, pending_clarification__c 
                        FROM case
                        WHERE Id=: caseRecord.Id];           
        system.debug(caseRecord);
        Test.stopTest();
        Assert.areEqual(caseRecord.Stage__c, StageMovementResult.nextStageConfig.StageName__c); 
    }

    @isTest
    private static void moveToNextStageApexClassNegative() {
        
        Case caseRecord = [
                                SELECT Id, CCC_External_Id__c, Stage__c, pending_clarification__c 
                                FROM case 
                                WHERE CCC_External_Id__c = 'CCC-CC-CCLTD-05'];           
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_02');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_02' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;
        
        Test.startTest();
        
        caseRecord.MoveToNext__c = true;
        update caseRecord;

        ASF_TriggerSkipperUtility.resetTriggerRun('Case');
        ASF_CaseQueryHandler.refreshRecords = true;
        ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        system.debug(StageMovementResult);

        caseRecord.MoveToNext__c = true;
        Database.SaveResult sResult = Database.update(caseRecord, false);
        
        Test.stopTest();
        //Assert.isFalse(sResult.isSuccess()); 
        //Assert.areEqual(StageMovementResult.errorMessage, sResult.getErrors()[0].getMessage(), 'Error Returned from the Apex Class should match');
         
    }
    
    @isTest
    private static void moveToNextWithPendingClarfTest() {
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1]; 
        caseRecord.Pending_Clarification__c = TRUE;
        caseRecord.Previous_Stage__c = 'In Progress with Recovery'; //Previous Stage
        update caseRecord;
        
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_01');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_01' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;
        
        Test.startTest();
        ASF_CaseMovementHelper.StageWrapper stageMovementResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        Test.stopTest();
        
        Assert.areEqual('Success', StageMovementResult.status); 
        Assert.areNotEqual(caseRecord.Stage__c, StageMovementResult.nextStageConfig.StageName__c, 'Case moved to Next Stage');
    } 
    @isTest
    private static void moveToNextGatewayTest() {
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, Previous_Stage__c, pending_clarification__c from case LIMIT 1]; 
        caseRecord.Pending_Clarification__c = TRUE;
        update caseRecord;
        
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_01');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_01' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;
        
        List<ASF_Case_Stage_Config__c> configList = [select Id, Gateway_Stage__c, StageName__c, Case_Category_Config__r.CCC_External_Id__c from ASF_Case_Stage_Config__c 
                                              where Case_Category_Config__r.CCC_External_Id__c=: caseRecord.CCC_External_Id__c];
        for(ASF_Case_Stage_Config__c conStage : configList){
            conStage.Gateway_Stage__c = true;
        }
        
        update configList;
        system.debug('test class stage record--'+configList.size()+configList[0].Gateway_Stage__c);
        
        Test.startTest();
        ASF_CaseMovementHelper.StageWrapper gatewayStageResult = ASF_CaseMovementHelper.moveToNextStage(caseRecord);
        Test.stopTest();
        
        //Assert.areEqual('Success', gatewayStageResult.status);  
    } 
    @isTest
    private static void moveToForwardStageTest() {
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1];           
        ASF_TestDataFactory.createCaseIntegration(caseRecord.Id,'ASF_INT_02');
        ASF_Case_Integration__c CaseIntRec = [select Id, Status__c, Is_Validation_Success__c from ASF_Case_Integration__c 
                                              where Integration_Ext_Id__c='ASF_INT_02' LIMIT 1];
        CaseIntRec.Is_Validation_Success__c = true;
        update CaseIntRec;
        
        Test.startTest();
        ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToForwardStage(caseRecord,'In Progress with Recovery');
        Test.stopTest();
        Assert.areEqual('Success', StageMovementResult.status);  
        Assert.areNotEqual(caseRecord.Stage__c, StageMovementResult.nextStageConfig.StageName__c, 'Case moved to Next Stage');
    } 
    // @isTest
    // private static void moveToBackStageTest() {
        
    //     Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1];           
        
    //     Test.startTest();
    //     ASF_CaseMovementHelper.StageWrapper StageMovementResult = ASF_CaseMovementHelper.moveToBackwardStage(caseRecord,'Closed');
    //     Test.stopTest();
    //     Assert.areEqual('Success', StageMovementResult.status);   
    // }


    @isTest
    private static void testGetAssignmentForStageBlank(){
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1];           
        // Find the Assignment for this case

        // No Default Owner Assigned
        ASF_CaseFrameworkHelper.CaseRuleAssignmentInfo info = ASF_CaseMovementHelper.getAssignmentForStage(caseRecord, 'Pending with Initiator');
        system.assertEquals(info.defaultOwnerId, null);
        system.assertEquals(info.defaultErrorOwnerId, null);

    }

    @isTest
    private static void testGetAssignmentForStageGroup(){
        
        Group g1 = new Group(Name='OCC-Test-Group', type='Queue');
        insert g1;
        QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
        insert q1;
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1];           
        // Find the Assignment for this case

        User userRecord = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = SYSTEMADMIN_PROFILE.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='abcdefghijk56@gmail.com');
        insert userRecord;

        System.runAs(userRecord){
            // Assign Group to the Stage
            ASF_Case_Rule__c rule = [
                                        SELECT Id 
                                        FROM ASF_Case_Rule__c 
                                        WHERE Case_Stage_Config__r.StageName__c = 'Pending with Initiator'
                                        AND Type__c = 'Assignment'];
            rule.Assigned_Queue_Id__c = g1.Id;
            rule.Assigned_Error_Queue_Id__c = UserInfo.getUserId();
            update rule;
        }
        
        ASF_CaseFrameworkHelper.CaseRuleAssignmentInfo info = ASF_CaseMovementHelper.getAssignmentForStage(caseRecord, 'Pending with Initiator');
        system.assertEquals(info.defaultOwnerId, g1.Id);
        system.assertEquals(info.defaultErrorOwnerId, userRecord.Id);

    }

    @isTest
    private static void testGetAssignmentForStageDefault(){
        
        Group g1 = new Group(Name='OCC-Test-Group', type='Queue');
        insert g1;
        QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
        insert q1;

        Group g2 = new Group(Name='OCC-Test-Group', type='Queue');
        insert g2;
        QueuesObject q2 = new QueueSObject(QueueID = g2.id, SobjectType = 'Case');
        insert q2;
        
        Case caseRecord = [select Id, CCC_External_Id__c, Stage__c, pending_clarification__c from case LIMIT 1];           
        // Find the Assignment for this case

        User userRecord = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = SYSTEMADMIN_PROFILE.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='abcdefghijk56@gmail.com');
        insert userRecord;

        System.runAs(userRecord){
            // Assign Group to the Stage
            ASF_Case_Stage_Config__c stageConfig = [
                                        SELECT Id 
                                        FROM ASF_Case_Stage_Config__c
                                        WHERE Case_Category_Config__r.CCC_External_Id__c =: caseRecord.CCC_External_Id__c
                                        AND StageName__c = 'Pending with Initiator'];

            stageConfig.Default_Queue__c = g1.Id;
            stageConfig.Default_Error_Queue__c = g2.Id;
            update stageConfig;
        }
        
        ASF_CaseFrameworkHelper.CaseRuleAssignmentInfo info = ASF_CaseMovementHelper.getAssignmentForStage(caseRecord, 'Pending with Initiator');
        system.assertEquals(info.defaultOwnerId, g1.Id);
        system.assertEquals(info.defaultErrorOwnerId, g2.Id);

    }
    
}