force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>ABHI</fullName>
            </value>
            <value>
                <fullName>ABSLAMC</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Overall_Case_Closure_SLA__c.field-meta.xml
<CustomField>
    <fullName>Overall_Case_Closure_SLA__c</fullName>
    <label>Overall Case Closure SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_SLA_History__c/ASF_Case_SLA_History__c.object-meta.xml
<CustomObject>
    <label>Case SLA History</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case SLA Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_SLA_History__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/ASF_Case_Stage_Config__c.object-meta.xml
<CustomObject>
    <label>Case Stage Config</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Stage Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Case_Category_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Category_Config__c</fullName>
    <label>Case Category Config</label>
    <referenceTo>ASF_Case_Category_Config__c</referenceTo>
    <relationshipLabel>Case Stage Configs</relationshipLabel>
    <relationshipName>Case_Stage_Configs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Manual_Stage__c.field-meta.xml
<CustomField>
    <fullName>Manual_Stage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Stage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Query_Fields__c.field-meta.xml
<CustomField>
    <fullName>Query_Fields__c</fullName>
    <label>Query Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/SLA_Target_1_Type__c.field-meta.xml
<CustomField>
    <fullName>SLA_Target_1_Type__c</fullName>
    <label>SLA Target 1 Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Stage_SLA_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_1__c</fullName>
    <label>Stage SLA 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <label>Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Stage_Config__c/fields/Status_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Status_Mapping__c</fullName>
    <label>Status Mapping</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Overall_Case_Closure_SLA__c.field-meta.xml
<CustomField>
    <fullName>Overall_Case_Closure_SLA__c</fullName>
    <label>Overall Case Closure SLA</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress with Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with CS</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>In Progress with Repayment Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Retention</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS</fullName>
            </value>
            <value>
                <fullName>In Progress with TDS Ops</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress with ABFL CIBIL</fullName>
            </value>
            <value>
                <fullName>In Progress with Closure Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Disbursement Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Partner</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipts</fullName>
            </value>
            <value>
                <fullName>In Progress with Receipt Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Sales</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Desk</fullName>
            </value>
            <value>
                <fullName>In Progress with Servicing Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with SRE Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with GRT</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>In Progress with Branch Ops</fullName>
            </value>
            <value>
                <fullName>In Progress with Revenue &amp; Retention</fullName>
            </value>
            <value>
                <fullName>Pending for Business / Credit Approval</fullName>
            </value>
            <value>
                <fullName>Pending for ROI Approval</fullName>
            </value>
            <value>
                <fullName>IO Recommendation</fullName>
            </value>
            <value>
                <fullName>IO Feedback</fullName>
            </value>
            <value>
                <fullName>In Progress with RCU</fullName>
            </value>
            <value>
                <fullName>In Progress with CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_1__c</fullName>
    <label>Stage SLA 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_2__c</fullName>
    <label>Stage SLA Threshold 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_3__c</fullName>
    <label>Stage SLA Threshold 3</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/SLA_Threshold_Warning__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>When you change this setting , please note that existing Cases needs to be reedited for new changes to come in.</description>
    <label>SLA Threshold Warning</label>
</CustomObject>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_1__c</fullName>
    <label>Case SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_2__c</fullName>
    <label>Case SLA Threshold 2</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Case_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Threshold_3__c</fullName>
    <label>Case SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_1__c</fullName>
    <label>Stage SLA Threshold 1</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_2__c</fullName>
    <label>Stage SLA Threshold 2</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Threshold_Warning__c/fields/Stage_SLA_Threshold_3__c.field-meta.xml
<CustomField>
    <fullName>Stage_SLA_Threshold_3__c</fullName>
    <label>Stage SLA Threshold 3</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Team Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ASF_QueueNotificationJob_Test.cls
@isTest 
public class ASF_QueueNotificationJob_Test {
    public static List<String> caseList;
    public static Map<String, Case> caseNumberRecordMap;

    @testSetup 
    static void setup() {
        // Create Parent Group
        Group testGroup = new Group();
        testGroup.name = 'Test SR Queue';
        testGroup.Type = 'Queue'; 
        testGroup.Email = 'abc@testsr.com';
        Insert testGroup; 
        
        System.runAs(new User(Id=UserInfo.getUserId())) {
            QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SObjectType = 'Case');
            insert testQueue;
        }
        
        insert new SLA_Threshold_Warning__c(Case_SLA_Threshold_1__c = 0.5, Case_SLA_Threshold_2__c = 0.7,
                                            Case_SLA_Threshold_3__c = 0.8, Stage_SLA_Threshold_1__c = 0.5,
                                            Stage_SLA_Threshold_2__c = 0.7, Stage_SLA_Threshold_3__c = 0.6);
        
        ASF_Case_Category_Config__c ccc = new ASF_Case_Category_Config__c();
        ccc.Type__c = 'tes';
        ccc.CCC_External_Id__c = '12345';
        ccc.Business_Unit__c = 'ABFL';
        ccc.Sub_Type__c = 'TDC Refund';
        ccc.Overall_Case_Closure_SLA__c = 10;
        insert ccc;
        
        ASF_Case_Stage_Config__c stage1 = new ASF_Case_Stage_Config__c();
        stage1.Case_Category_Config__c = ccc.Id;
        stage1.Order__c = 1;
        stage1.StageName__c  = 'New';
        stage1.Stage_SLA_1__c = 1;
        stage1.Status_Mapping__c = 'New';
        stage1.SLA_Target_1_Type__c = 'Manager';
        stage1.Query_Fields__c = 'Id,Stage__c';
        stage1.Manual_Stage__c = false;
        insert stage1;
        
        Datetime currentTime = Datetime.now();
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
        
        Case caser = new Case();
        caser.Origin = 'Email';
        caser.Subject = 'SR Case';
        caser.Stage__c = 'New';
        caser.BusinessHoursId = bh.Id;
        caser.CCC_External_Id__c = '12345';
        caser.Last_Owner_Change_Date__c = system.now().addHours(-5);
        caser.OwnerId = testGroup.Id;
        insert caser; 
        
        Case testCase1 = new Case();
        testCase1.Origin = 'Email';
        testCase1.Subject = 'SR Case1';
        testCase1.Stage__c = 'New';
        testCase1.BusinessHoursId = bh.Id;
        testCase1.CCC_External_Id__c = '12345';
        testCase1.Last_Owner_Change_Date__c = System.now();
        testCase1.OwnerId = testGroup.Id;
        insert testCase1; 
        
        Case testCase2 = new Case();
        testCase2.Origin = 'Email';
        testCase2.Subject = 'SR Case2';
        testCase2.Stage__c = 'New';
        testCase2.BusinessHoursId = bh.Id;
        testCase2.CCC_External_Id__c = '12345';
        testCase2.Last_Owner_Change_Date__c =Datetime.newInstance(System.now().date().addDays(-70),System.now().time());
        testCase2.OwnerId = testGroup.Id;
        insert testCase2;
        
        testCase2.Last_Owner_Change_Date__c =Datetime.newInstance(System.now().date().addDays(-70),System.now().time());
        update testCase2;
        
        caseList = new List<String>();
        caseList.add(string.valueof(testCase1.Id));
        caseList.add(string.valueof(testCase2.Id));
        
        caseNumberRecordMap = new Map<String, Case>();
        caseNumberRecordMap.put(testCase1.Id, testCase1);
        caseNumberRecordMap.put(testCase2.Id, testCase2);
        
        ASF_Case_SLA_History__c his = new ASF_Case_SLA_History__c();
        his.Case__c = caser.Id;
        his.Stage_Start_Date__c = currentTime.addDays(-2);
        his.BusinessHoursId__c = bh.Id;
        his.Breached_User_Id__c = testGroup.Id;
        his.Stage__c = 'New';
        insert his;
    }
    
    @isTest 
    static void testfetchSRStages() {
        List<Case> fetchedCaseList = [select id, CaseNumber, Type_Text__c, Sub_Type_Text__c, Last_Owner_Change_Date__c from case where Subject = 'SR Case1' OR Subject = 'SR Case2' ];
        List<String> Caseid = new List<String>();
        Map<String, Case> fetchcaseMap = new Map<String,Case>();
        
        for (case cs : fetchedCaseList) {
            Caseid.add(cs.id);
            fetchcaseMap.put(cs.id, cs);
        }
        // Assert that the fetched cases have the expected fields populated
        for (Case cs : fetchedCaseList) {
            System.assertNotEquals(null, cs.CaseNumber, 'Case Number should not be null');
            System.assertNotEquals(null, cs.Last_Owner_Change_Date__c, 'Last Owner Change Date should not be null');
        }
        
        Map<String, Case> fetchedCaseNumberRecordMap = ASF_QueueNotificationJob_Test.caseNumberRecordMap;
        // Assertion to check the size of fetchedCaseList
        System.assertEquals(2, fetchedCaseList.size(), 'Incorrect number of cases retrieved');
        
        Test.startTest();
        ASF_QueueNotificationJob obj = new ASF_QueueNotificationJob();
        ASF_QueueNotificationJob.getTableEmailBody(Caseid, fetchcaseMap);
        obj.execute(null);
        Test.stopTest();
        
        
    }
}