force-app/main/default/objects/ASF_Case_Category_Config__c/ASF_Case_Category_Config__c.object-meta.xml
<CustomObject>
    <description>Case Management Parent Object.</description>
    <label>Case Category Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Case Category Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Category Configs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>CCC External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Is_Transaction_Related__c.field-meta.xml
<CustomField>
    <fullName>Is_Transaction_Related__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for Payment LOB.
TRUE - Consider Customer Id + Case Type + Case Sub Type + Case Category + Transaction ID + Status to do dedupe
FALSE - Consider Customer Id + Case Type + Case Sub Type + Case Category + Status to do dedupe</description>
    <label>Is Transaction Related</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Category_Config__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PAY_Payment_Detail__c.field-meta.xml
<CustomField>
    <fullName>PAY_Payment_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Detail</label>
    <referenceTo>PAY_Payment_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PAY_Payment_Detail__c/PAY_Payment_Detail__c.object-meta.xml
<CustomObject>
    <label>Payment Detail</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PAY_Payment_Detail__c/fields/Txn_ref_no__c.field-meta.xml
<CustomField>
    <fullName>Txn_ref_no__c</fullName>
    <label>Txn ref no</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PAY_CaseDeDupeCheck.cls
public without sharing class PAY_CaseDeDupeCheck {

    public static void runDuplicateCheck(List<Case> cases)
    {
        List<ASF_Case_Category_Config__c> caseCategoryConfigs = new List<ASF_Case_Category_Config__c>();
        Set<String> transactionRelatedCCC = new Set<String>();
        Set<String> nontransactionRelatedCCC = new Set<String>();
        Map<String,Set<Id>> mCCCVsAccountIds = new Map<String,Set<Id>>();
        Map<Id,List<Case>> mAccountIdVsCases = new Map<Id,List<Case>>();
        Map<Id,PAY_Payment_Detail__c> mPayExtension = new Map<Id,PAY_Payment_Detail__c>();
        Set<Id> payExtensionIds = new Set<Id>();
        
		/* Get the CCC External Id from Incoming List of Cases.
		 * Map CCC External Id against List of AccountId.
		 * Map Account Id Vs List of Incoming Cases from the incoming cases.
		 * Set of Payment Detail records Id.
		 */
        
        System.debug(cases);
        for(Case c : cases){
            if(!mCCCVsAccountIds.containsKey(c.CCC_External_Id__c)){
                mCCCVsAccountIds.put(c.CCC_External_Id__c, new Set<Id>());
            } 
            mCCCVsAccountIds.get(c.CCC_External_Id__c).add(c.AccountId);
            
            
            if(!mAccountIdVsCases.containsKey(c.AccountId)){
                mAccountIdVsCases.put(c.AccountId, new List<Case>());
            }
            mAccountIdVsCases.get(c.AccountId).add(c);
            
            payExtensionIds.add(c.PAY_Payment_Detail__c);
        }
        
        /* If there is Payment Detail records present in Incoming List of Cases, query and get the transaction Id for the same.
         */
        
        if(payExtensionIds.size()>0){
            mPayExtension = new Map<Id,PAY_Payment_Detail__c>([SELECT ID,Txn_ref_no__c FROM PAY_Payment_Detail__c WHERE Id =: payExtensionIds]);
            System.debug(mPayExtension);
        }
        
        
        
        // Get Case Category Configuration. 
        caseCategoryConfigs = [SELECT ID,Nature__c,Type__c, Sub_Type__c,Is_Transaction_Related__c,CCC_External_Id__c FROM ASF_Case_Category_Config__c WHERE CCC_External_Id__c =: mCCCVsAccountIds.keySet()];
        
        for(ASF_Case_Category_Config__c ccc : caseCategoryConfigs){
            if(ccc.Is_Transaction_Related__c){
                /* Prepare Collection of TransactionRelated             
                 */
                transactionRelatedCCC.add(ccc.CCC_External_Id__c);
            }
            else{
                /* Prepare Collection of NonTransactionRelated             
                 */                
                nontransactionRelatedCCC.add(ccc.CCC_External_Id__c);
            }
        }
        
       /* Get the list of Cases for Accountids and with Closed = False i.e. take all the cases not resolved or rejected or cancelled or merged.            
        * Check if this is transaction releated
        * 		
       */
        
        for(Case dupeCase: [SELECT ID,CCC_External_Id__c,AccountId,Status,PAY_Payment_Detail__c,PAY_Payment_Detail__r.Txn_ref_no__c,CaseNumber FROM Case WHERE AccountId =: mAccountIdVsCases.keySet() AND CCC_External_Id__c =: mCCCVsAccountIds.keySet() AND isClosed = false]){
            if(transactionRelatedCCC.contains(dupeCase.CCC_External_Id__c )){
                System.debug('I am here....'+dupeCase.Id);
                if(mAccountIdVsCases.containsKey(dupeCase.AccountId)){
                                    System.debug('I am here....2'+dupeCase.Id);
                    if(mAccountIdVsCases.containsKey(dupeCase.AccountId)){
                                                            System.debug('I am here....3'+dupeCase.Id);
                        for(Case c : mAccountIdVsCases.get(dupeCase.AccountId)){
                                                                System.debug('I am here....4'+dupeCase.Id);
                            if(mPayExtension.containsKey(c.PAY_Payment_Detail__c)){
                                                                    System.debug('I am here....5');
                                PAY_Payment_Detail__c currentCasePaymentRecord = mPayExtension.get(c.PAY_Payment_Detail__c);
                                System.debug(dupeCase.PAY_Payment_Detail__r.Txn_ref_no__c +' == '+ currentCasePaymentRecord.Txn_ref_no__c);
                                if(dupeCase.PAY_Payment_Detail__r.Txn_ref_no__c == currentCasePaymentRecord.Txn_ref_no__c){
                                    System.debug('Finally Here....');
                                    // Coming here if the Current Case Transaction Id equals Existing Not Closed Service Request with same transaction Id with the same type and subtype.
                                        c.addError('Duplicate Case found. Case # '+dupeCase.CaseNumber);
                                }
                            }
                        }
                    }
                }
                
            }
            else if(nontransactionRelatedCCC.contains(dupeCase.CCC_External_Id__c)){
                if(mAccountIdVsCases.containsKey(dupeCase.AccountId)){
                    for(Case c : mAccountIdVsCases.get(dupeCase.AccountId)){
                        c.addError('Duplicate Case found. Case # '+dupeCase.CaseNumber);
                    }
                }
            }
        }
        
        
        
    }
    
}