force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/ASF_PriorityEmailAddressesByBU__mdt.object-meta.xml
<CustomObject>
    <description>This is used when customer sends one email to multiple email addresses, then find out the priority Queue by email address configured on Email-To-Case and assign to right queue.</description>
    <label>ASF PriorityEmailAddressesByBU</label>
    <pluralLabel>ASF PriorityEmailAddressesByBU</pluralLabel>
</CustomObject>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Send_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Send_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Based on the Checkbox, it will take a decision whether any email received on this email box to be forwarded for EBot Categorisation or not.</description>
    <label>Send to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interaction.recordType-meta.xml
<RecordType>
    <fullName>Interaction</fullName>
    <active>true</active>
    <businessProcess>EmailProcess</businessProcess>
    <label>Interaction</label>
</RecordType>

force-app/main/default/objects/EmailMessage/fields/Send_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Send_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is used in ASF_Email2CaseHandler based on Priority Email, it will mark Send to EBOT True or False.</description>
    <label>Send to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ASF_SendPreFrameworkCaseToLOBTest.cls
@isTest
public class ASF_SendPreFrameworkCaseToLOBTest {
    private final static Profile SYSTEMADMIN_PROFILE = [SELECT Id FROM Profile WHERE name='System Administrator' LIMIT 1];
    
    
    @IsTest
    static void getPriorityEmailList(){
        Test.startTest();
        List<ASF_PriorityEmailAddressesByBU__mdt> priorityEmails= ASF_SendPreFrameworkCaseToLOB.getPriorityEmailList();
        Test.stopTest();
        System.assertEquals(priorityEmails.size()>0,true , 'Found Priority Emails');
    }
    
    @IsTest
    static void updateCase(){
        Test.startTest();
        ASF_TestDataFactory.createCaseCategoryConfig();
        List<Case> lstCase = ASF_TestDataFactory.createCaseRecords(1);
        Id interactionId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
        for(Case c:lstCase){
            c.RecordTypeId = interactionId;
            c.Origin = 'ABCD Email';
            c.Business_Unit__c = 'ABCD';
            c.suppliedEmail = 'test@sales.com';
        }
        
        update lstCase;
        
        EmailMessage emsg = new EmailMessage();
        emsg.ParentId = lstCase[0].Id;
        emsg.Incoming = true;
        insert emsg;
        
        
        List<ASF_PriorityEmailAddressesByBU__mdt> priorityEmails= ASF_SendPreFrameworkCaseToLOB.getPriorityEmailList();
        ASF_PriorityEmailAddressesByBU__mdt cmdEbotEnabled = new ASF_PriorityEmailAddressesByBU__mdt();
        for(ASF_PriorityEmailAddressesByBU__mdt cmd : priorityEmails){
            if(cmd.Send_to_EBOT__c == true){
                cmdEbotEnabled = cmd;
                break;
            }
        }
        
        ASF_SendPreFrameworkCaseToLOB.updateCase(lstCase[0].Id,cmdEbotEnabled.Id);
        Test.stopTest();
        System.assertEquals(priorityEmails.size()>0,true , 'Found Priority Emails');
    }
    
    
}