force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/ASF_PriorityEmailAddressesByBU__mdt.object-meta.xml
<CustomObject>
    <description>This is used when customer sends one email to multiple email addresses, then find out the priority Queue by email address configured on Email-To-Case and assign to right queue.</description>
    <label>ASF PriorityEmailAddressesByBU</label>
    <pluralLabel>ASF PriorityEmailAddressesByBU</pluralLabel>
</CustomObject>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only Consider Active Configuration in Query</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABSLIG</fullName>
            </value>
            <value>
                <fullName>ABML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Case_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Case_Business_Unit__c</fullName>
    <label>Case Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Case_Origin__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin__c</fullName>
    <label>Case Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Payments Email</fullName>
            </value>
            <value>
                <fullName>ABFL Email</fullName>
            </value>
            <value>
                <fullName>ABHFL Email</fullName>
            </value>
            <value>
                <fullName>ABFL WM CHAT</fullName>
            </value>
            <value>
                <fullName>ABWM Email</fullName>
            </value>
            <value>
                <fullName>ABSLI Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Default_Queue_Dev_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Queue_Dev_Name__c</fullName>
    <description>This is developer name of queue to which case to be assigned</description>
    <label>Default Queue Dev Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Email2CaseAddress__c.field-meta.xml
<CustomField>
    <fullName>Email2CaseAddress__c</fullName>
    <description>From Email-To-Case Routing Address</description>
    <label>Email2CaseAddress</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Priority_Index__c.field-meta.xml
<CustomField>
    <fullName>Priority_Index__c</fullName>
    <label>Priority Index</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ASF_PriorityEmailAddressesByBU__mdt/fields/Send_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Send_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Based on the Checkbox, it will take a decision whether any email received on this email box to be forwarded for EBot Categorisation or not.</description>
    <label>Send to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABFL</fullName>
            </value>
            <value>
                <fullName>ABHFL</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>ABWM</fullName>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
            <value>
                <fullName>ABSLI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sent_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Winning_Email__c.field-meta.xml
<CustomField>
    <fullName>Winning_Email__c</fullName>
    <label>Winning Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EBOT_Internal_Event__e/EBOT_Internal_Event__e.object-meta.xml
<CustomObject>
    <label>EBOT Internal Event</label>
    <pluralLabel>EBOT Internal Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/EBOT_Internal_Event__e/fields/Email_Message_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_ID__c</fullName>
    <label>Email Message ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Send_to_EBOT__c.field-meta.xml
<CustomField>
    <fullName>Send_to_EBOT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is used in ASF_Email2CaseHandler based on Priority Email, it will mark Send to EBOT True or False.</description>
    <label>Send to EBOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Winning_Email__c.field-meta.xml
<CustomField>
    <fullName>Winning_Email__c</fullName>
    <description>This email address is the Priority Email in case of Multiple Email address sent within To address or Cc address</description>
    <label>Winning Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ASF_SendPreFrameworkCaseToLOB.cls
public with sharing class ASF_SendPreFrameworkCaseToLOB {
    @AuraEnabled(cacheable = true)
    public static List<ASF_PriorityEmailAddressesByBU__mdt> getPriorityEmailList(){
        List<ASF_PriorityEmailAddressesByBU__mdt> priorityEmails = [SELECT Id, 
                                                                    DeveloperName, MasterLabel, Label,Active__c, Business_Unit__c, Default_Queue_Dev_Name__c, Email2CaseAddress__c, 
                                                                    Priority_Index__c, Send_to_EBOT__c, Case_Origin__c, Case_Business_Unit__c 
                                                                    FROM ASF_PriorityEmailAddressesByBU__mdt WHERE Active__c = TRUE];
        return priorityEmails;
    }
    @AuraEnabled
    public static void updateCase(Id recId,Id priorityCMId){
        Id newOwnerId;
        ASF_PriorityEmailAddressesByBU__mdt priorityEmail = [SELECT Id, 
                                                             DeveloperName, MasterLabel, Label,Active__c, Business_Unit__c, Default_Queue_Dev_Name__c, Email2CaseAddress__c, 
                                                             Priority_Index__c, Send_to_EBOT__c, Case_Origin__c, Case_Business_Unit__c 
                                                             FROM ASF_PriorityEmailAddressesByBU__mdt WHERE Id =: priorityCMId];
        if(priorityEmail.Default_Queue_Dev_Name__c != null){
            Group grp = [SELECT ID FROM Group WHERE DeveloperName =: priorityEmail.Default_Queue_Dev_Name__c LIMIT 1];
            newOwnerId = grp.Id;
        }
        Case c = new Case(Id=recId);
        c.Business_Unit__c = priorityEmail.Case_Business_Unit__c;
        c.Winning_Email__c = priorityEmail.Email2CaseAddress__c;
        c.Sent_to_EBOT__c = priorityEmail.Send_to_EBOT__c;
        c.Origin = priorityEmail.Case_Origin__c;
        c.OwnerId = newOwnerId;
        try{
            update c;
            
            List<EmailMessage> emails = [SELECT ID FROM EmailMessage WHERE ParentId =: c.Id AND Incoming = TRUE LIMIT 1];
            if(emails.size()>0){
                Map<String, String> fieldsMap = new Map<String, String>();
                fieldsMap.put('Email_Message_ID__c', emails[0].Id);
                Database.SaveResult eventResult = ABCL_CasePlatformEventHandler.publishPlatformEvent('EBOT_Internal_Event__e', fieldsMap);
            }
            
        }
        catch(exception ex){
          throw new AuraException('Error Occured while forwarding email to LOB');
        }
        
    }
    
}