force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Integration_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Ext_Id__c</fullName>
    <label>Integration Ext Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/CCC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CCC_External_Id__c</fullName>
    <description>This field is going to store the CTST External Id.</description>
    <label>CCC External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ASF_CaseIntegrationTriggerHandler_Test.cls
@IsTest
public class ASF_CaseIntegrationTriggerHandler_Test {
    
    @TestSetup
    static void setUpData(){
         ASF_TestDataFactory.createC3WithPrePopulateIntegrations();
        List<Case> cases = ASF_TestDataFactory.createCaseRecords(3);
    }
   
    @isTest
    static void testCancelPendingCaseIntegrations(){
    
        // Run the Integration Once to create Pending First
        List<ASF_Integration__c> prepIntegrations =  ASF_IntegrationsController.getAllIntegrations('CCC-CC-CCLTD-01', 'Pending with Initiator');
        Case caseRec = [
            SELECT Id
            FROM Case
            WHERE CCC_External_Id__c = 'CCC-CC-CCLTD-01' LIMIT 1
        ];
        
        Object retVal = ASF_IntegrationsController.runIntegration(prepIntegrations[0], caseRec);
        
       
        ASF_Case_Integration__c caseIntRec = [
            SELECT Id, Status__c
            FROM ASF_Case_Integration__c
            WHERE Case__c =: caseRec.Id
            AND Integration_Ext_Id__c =: prepIntegrations[0].External_Id__c
        ];
        system.assertEquals('Success', retVal);
        system.assertEquals('Pending', caseIntRec.Status__c);

        // Now Cancel the Integration
        ASF_IntegrationsController.cancelPendingCaseIntegrations(caseRec.Id, prepIntegrations[0].External_Id__c);
        
        caseIntRec = [
            SELECT Id, Status__c
            FROM ASF_Case_Integration__c
            WHERE Id =: caseIntRec.Id
        ];

        system.assertEquals('Canceled', caseIntRec.Status__c);
    } 
}