force-app/main/default/objects/ASF_Case_Integration__c/ASF_Case_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Case Integration</label>
    <nameField>
        <displayFormat>ASF_CInt_{0000}</displayFormat>
        <label>ASF Case Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Case Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ASF Case Integrations</relationshipLabel>
    <relationshipName>ASF_Case_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Case_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Can be blank for Framework Type if Integrations. Need to be populated for generic integrations like eBot</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eBOT</fullName>
            </value>
            <value>
                <fullName>eBOTFeedback</fullName>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>BRE</fullName>
            </value>
            <value>
                <fullName>Litmus</fullName>
            </value>
            <value>
                <fullName>Enach</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/ASF_Integration__c.object-meta.xml
<CustomObject>
    <label>ASF Integration</label>
    <nameField>
        <displayFormat>ASF_Int_{0000}</displayFormat>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASF Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASF_Integration__c/fields/STP_API_Identifier__c.field-meta.xml
<CustomField>
    <fullName>STP_API_Identifier__c</fullName>
    <description>This field is used to store identifier for STP API callouts.</description>
    <label>STP API Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_Config_External_Id__c.field-meta.xml
<CustomField>
    <fullName>STP_Config_External_Id__c</fullName>
    <description>This field is used to check if any child case needs to be created on closure of Case. Used in STP Flows</description>
    <label>STP Config External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_Processing_Class__c.field-meta.xml
<CustomField>
    <fullName>STP_Processing_Class__c</fullName>
    <label>STP Processing Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/STP_Template__c.field-meta.xml
<CustomField>
    <fullName>STP_Template__c</fullName>
    <label>STP Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASF_Integration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Populate</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>UI Card</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>UI Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ABFL_SOQL_Integration.cls
/**
* @Class name       :      ABFL_SOQL_Integration
* @description      :      SOQL Util class for ASF_Case_Integration__c Obj
* @Group            :
* Modification Log  :
* ------------------------------------------------------------------------------------
* Developer                  Version     Date                Description
* ------------------------------------------------------------------------------------
* Aditee                     1.0       13/12/2023              #
*/
public with sharing class ABFL_SOQL_Integration {
	/****************************************************************************************************************
     * @function - getCaseIntegrationInfo
     * @description - SOQL method for getting integration details
     * @param caseid
     * @param type
     * @return Map<Id, Case>
     *****************************************************************************************************************/
    public static List<ASF_Case_Integration__c> getCaseIntegrationInfo(String caseid, String type){
        return [SELECT Name FROM ASF_Case_Integration__c 
                WHERE Case__c = :caseid 
                AND Status__c = :ABFL_Constants.PENDING
                AND Type__c = :type
                WITH SECURITY_ENFORCED];
    } 
    /****************************************************************************************************************
     * @function        getCaseIntegrationInfos
     * @description     SOQL method for getting integration details
     * @param ciIds
     * @param status
     * @return List<ASF_Case_Integration__c>
     *****************************************************************************************************************/
    public static List<ASF_Case_Integration__c> getCaseIntegrationInfos(List<Id> ciIds, String status){
        return [SELECT Name,Case__c FROM ASF_Case_Integration__c 
                WHERE Id IN :ciIds 
                AND Status__c = :status
                WITH SECURITY_ENFORCED];
    } 
    /********************************************************************************************************
    * @function         getIntegrationInfo 
    @author             Salesforce
    * @date             13/12/2023
    * @description      SOQL method for getting integration details
    * @param            externalId
    * @return           case
    *********************************************************************************************************/
    public static ASF_Integration__c getIntegrationInfo(string externalId){
        return [SELECT id, STP_API_Identifier__c, STP_Processing_Class__c, 
                External_Id__c,STP_Config_External_Id__c, STP_Template__c 
                FROM ASF_Integration__c 
                WHERE External_Id__c = :externalId
                WITH SECURITY_ENFORCED];
    } 

    /********************************************************************************************************
    * @function         getCaseIdsToIntegrationRecordsMap 
    * @author           Salesforce
    * @date             13/12/2023
    * @description      SOQL method for getting integration details
    * @param            caseIdSet
    * @param            type
    * @return           Map<Id, ASF_Case_Integration__c>
    *********************************************************************************************************/
    public static Map<Id, ASF_Case_Integration__c> getCaseIdsToIntegrationRecordsMap(Set<Id> caseIdSet, String type) {
        Map<Id, ASF_Case_Integration__c> caseIdToCaseIntMap = new Map<Id, ASF_Case_Integration__c>();

        List<ASF_Case_Integration__c> caseIntRecordsList = [SELECT Name, Case__c
                                                            FROM ASF_Case_Integration__c 
                                                            WHERE Case__c IN :caseIdSet 
                                                            AND Status__c = :ABFL_Constants.PENDING
                                                            AND Type__c = :type
                                                            WITH SECURITY_ENFORCED];

        for(ASF_Case_Integration__c caseIntRecord :caseIntRecordsList) {
            caseIdToCaseIntMap.put(caseIntRecord.Case__c, caseIntRecord);
        }

        return caseIdToCaseIntMap;
    }
}